### PR TITLE
Log command for _execute_and_process_stdout.

### LINKED ISSUE #452: `_execute_and_process_stdout` should log cmd

### PR DESCRIPTION
**Pull request by winterfroststrom**
Fixes #452

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/453)

### CODE REVIEW

**Comment by xpconanfan** [comment]
I don't see how this is related to logging stderr as the issue described.
One of the msg is incorrect?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[mobly/controllers/android_device_lib/adb.py, line 215 at r1](https://reviewable.io/reviews/google/mobly/453#-LDIjCGd2zhkKzp2ablH:-LDIjCGd2zhkKzp2ablI:b-x8c38) ([raw file](https://github.com/google/mobly/blob/73f94e45966ec8566eabae03fc00893e5a13ee33/mobly/controllers/android_device_lib/adb.py#L215)):*
> ```Python
>                     break
>         finally:
>             (unhandled_out, err) = proc.communicate()
> ```

wait, so this does happen?
shouldn't we call the handler with this out instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/453#-:-LDIjnBO4MUgZxYNImBt:blud5im)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 215 at r1](https://reviewable.io/reviews/google/mobly/453#-LDIjCGd2zhkKzp2ablH:-LDIkOBz8aQLOE0ovB8O:brjczjz) ([raw file](https://github.com/google/mobly/blob/73f94e45966ec8566eabae03fc00893e5a13ee33/mobly/controllers/android_device_lib/adb.py#L215)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

wait, so this does happen?
shouldn't we call the handler with this out instead?
</blockquote></details>

I'm not sure?
I'm adding logging here first to try to determine what the underlying problem is

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/453)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 215 at r1](https://reviewable.io/reviews/google/mobly/453#-LDIjCGd2zhkKzp2ablH:-LDIl2971UfZ3LqypsHv:b332s67) ([raw file](https://github.com/google/mobly/blob/73f94e45966ec8566eabae03fc00893e5a13ee33/mobly/controllers/android_device_lib/adb.py#L215)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

I'm not sure?
I'm adding logging here first to try to determine what the underlying problem is
</blockquote></details>

seems like we should pipe all stdout content through the handler as this function promised?
you could add additional logging to signify the existence of stdout from `communicate`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/453)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_lib/adb_test.py, line 156 at r1](https://reviewable.io/reviews/google/mobly/453#-LDImOOR-GL1gRhihxxl:-LDImOOR-GL1gRhihxxm:ba86vyn) ([raw file](https://github.com/google/mobly/blob/73f94e45966ec8566eabae03fc00893e5a13ee33/tests/mobly/controllers/android_device_lib/adb_test.py#L156)):*
> ```Python
>     def test_execute_and_process_stdout_logs_cmd(self, mock_debug_logger,
>                                                  mock_popen):
>         self._mock_execute_and_process_stdout_process(mock_popen)
> ```

this test is relying on the default mock stdout value in `_mock_execute_and_process_stdout_process`, which is difficult to read.
Can we more explicitly set the mock value within the test?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/453)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 215 at r1](https://reviewable.io/reviews/google/mobly/453#-LDIjCGd2zhkKzp2ablH:-LDIsvuPD4jS9CVrpnr5:bcy1d3j) ([raw file](https://github.com/google/mobly/blob/73f94e45966ec8566eabae03fc00893e5a13ee33/mobly/controllers/android_device_lib/adb.py#L215)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

seems like we should pipe all stdout content through the handler as this function promised?
you could add additional logging to signify the existence of stdout from `communicate`?
</blockquote></details>

So, I've never seen this output actually get populated and I'm not sure it is in the case I'm debugging, but okay.

I'm preferring changing the logged command because otherwise you'd get semi-duplicate log lines.

---

*[tests/mobly/controllers/android_device_lib/adb_test.py, line 156 at r1](https://reviewable.io/reviews/google/mobly/453#-LDImOOR-GL1gRhihxxl:-LDItG5yEIdICTRzP1c0:b-896fix) ([raw file](https://github.com/google/mobly/blob/73f94e45966ec8566eabae03fc00893e5a13ee33/tests/mobly/controllers/android_device_lib/adb_test.py#L156)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this test is relying on the default mock stdout value in `_mock_execute_and_process_stdout_process`, which is difficult to read.
Can we more explicitly set the mock value within the test?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/453)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/453#-:-LEBweyyBV-cQJiSKgM7:bnfp4nl)*

**Pull request merged**
