### PR TITLE
Allow logging to start before running tests

### PR DESCRIPTION
**Pull request by winterfroststrom**
For #388

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/389)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mobly/test_runner.py, line 296 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xB1syG8YJ0xAkRupJ:-L4xB1szSIYtZTI8sLqv:bbdckzb) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L296)):*
> ```Python
>         if not self._has_logger:
>             self._start_time = logger.get_log_file_timestamp()
>             self._log_path = os.path.join(self._log_dir, self._test_bed_name,
> ```

seems like we could simply check if `self._log_path` is `None` and do away with `self._has_logger`?

---

*[mobly/test_runner.py, line 395 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xBfAG6LXGuQxnQ0P0:-L4xBfAG6LXGuQxnQ0P1:bpqp2dx) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L395)):*
> ```Python
>             self._write_results_json_str(self._log_path)
>             logging.info(msg.strip())
>             logger.kill_test_logger(logging.getLogger())
> ```

we could put these two lines into a `teardown_logger` to be more consistent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mobly/test_runner.py, line 296 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xB1syG8YJ0xAkRupJ:-L4xE4gcLiketvky5B69:b21i3cd) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L296)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

seems like we could simply check if `self._log_path` is `None` and do away with `self._has_logger`?
</blockquote></details>

What if someone is using this value after the test run though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mobly/test_runner.py, line 296 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xB1syG8YJ0xAkRupJ:-L4xEUZnxx4rfnlEVoGc:b-qjq5nu) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L296)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

What if someone is using this value after the test run though?
</blockquote></details>

which value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mobly/test_runner.py, line 296 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xB1syG8YJ0xAkRupJ:-L4xFXeISxHVVj2ca31C:bjf8wjm) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L296)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

which value?
</blockquote></details>

self._log_path

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 296 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xB1syG8YJ0xAkRupJ:-L4xMCrw37Wj_ZUe0dlg:b-9qn21f) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L296)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

self._log_path
</blockquote></details>

It's a private var, nobody is supposed to use it outside of TestRunner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/test_runner.py, line 511 at r4](https://reviewable.io:443/reviews/google/mobly/389#-L4xQ6q_bdAVnPY799Yi:-L4xQ6q_bdAVnPY799Yj:b7fxw3c) ([raw file](https://github.com/google/mobly/blob/364c7a1430737937767bdaec4cf3410245361ac9/mobly/test_runner.py#L511)):*
> ```Python
>         self._controller_destructors = {}
> 
>     def _write_results_json_str(self, log_path):
> ```

this shouldn't exist.

pls fix your commit history

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/test_runner.py, line 296 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xB1syG8YJ0xAkRupJ:-L4xUTfzObBqfY9Mj-8A:b-byun13) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L296)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It's a private var, nobody is supposed to use it outside of TestRunner?
</blockquote></details>

It's been so long since I looked at this that I forget this wasn't a prexisting variable, changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/test_runner.py, line 293 at r5](https://reviewable.io:443/reviews/google/mobly/389#-L5BdB5BaGJzfOGwV95S:-L5BdB5BaGJzfOGwV95T:b-ngbk78) ([raw file](https://github.com/google/mobly/blob/6066d8683ca777b48e0e5e6139a70361a4710bbf/mobly/test_runner.py#L293)):*
> ```Python
> 
>     def setup_logger(self):
>         """Sets up logging for the next test run."""
> ```

what does "next" imply? was there a previous test run?...

should we be more explicit about the usage, like this can be used when creating a suite?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/test_runner.py, line 395 at r1](https://reviewable.io:443/reviews/google/mobly/389#-L4xBfAG6LXGuQxnQ0P0:-L5BeM8Tkob2FUvpHZjT:b-896fix) ([raw file](https://github.com/google/mobly/blob/aa3e450427f90ff8d7637032749b517876c43c6c/mobly/test_runner.py#L395)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

we could put these two lines into a `teardown_logger` to be more consistent?
</blockquote></details>

Done.

---

*[mobly/test_runner.py, line 511 at r4](https://reviewable.io:443/reviews/google/mobly/389#-L4xQ6q_bdAVnPY799Yi:-L5BeNrfVKJurSVF1Xsk:b-896fix) ([raw file](https://github.com/google/mobly/blob/364c7a1430737937767bdaec4cf3410245361ac9/mobly/test_runner.py#L511)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this shouldn't exist.

pls fix your commit history
</blockquote></details>

Done.

---

*[mobly/test_runner.py, line 293 at r5](https://reviewable.io:443/reviews/google/mobly/389#-L5BdB5BaGJzfOGwV95S:-L5BeRE-zH66cTTK-8n2:b5x6mwf) ([raw file](https://github.com/google/mobly/blob/6066d8683ca777b48e0e5e6139a70361a4710bbf/mobly/test_runner.py#L293)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what does "next" imply? was there a previous test run?...

should we be more explicit about the usage, like this can be used when creating a suite?
</blockquote></details>

Potentially, current behaviour is that the logs from two calls to run setup logging twice. If you can imaging calling this before run, then there would be a "next" and a "previous" in that case.

What do you mean by "when creating a suite"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 293 at r5](https://reviewable.io:443/reviews/google/mobly/389#-L5BdB5BaGJzfOGwV95S:-L5Bf-SL23ujfpn87yu8:ba6fn4p) ([raw file](https://github.com/google/mobly/blob/6066d8683ca777b48e0e5e6139a70361a4710bbf/mobly/test_runner.py#L293)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Potentially, current behaviour is that the logs from two calls to run setup logging twice. If you can imaging calling this before run, then there would be a "next" and a "previous" in that case.

What do you mean by "when creating a suite"?
</blockquote></details>

Users normally shouldn't need to call this themselves.
We are adding this so the logger can be set up in suite right?

Let's at least list that as a sample usage in docstring?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 293 at r5](https://reviewable.io:443/reviews/google/mobly/389#-L5BdB5BaGJzfOGwV95S:-L5BiR0_q-_3hoCyH5og:bfq1izz) ([raw file](https://github.com/google/mobly/blob/6066d8683ca777b48e0e5e6139a70361a4710bbf/mobly/test_runner.py#L293)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Users normally shouldn't need to call this themselves.
We are adding this so the logger can be set up in suite right?

Let's at least list that as a sample usage in docstring?
</blockquote></details>

Updated docstring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 293 at r5](https://reviewable.io:443/reviews/google/mobly/389#-L5BdB5BaGJzfOGwV95S:-L5Bo_LAu6vxaEfNRHQU:b-y3mx54) ([raw file](https://github.com/google/mobly/blob/6066d8683ca777b48e0e5e6139a70361a4710bbf/mobly/test_runner.py#L293)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Updated docstring.
</blockquote></details>

Let's avoid referring to specific implementation details when possible.

How about:

"""

Only use this method if you want to use Mobly's logger before the test run starts.

For example, when creating a suite:

.. code-block:: python

    tr = TestRunner(...)
    tr.setup_logger()
    logging.info(...)
    tr.run()

"""

---

*[mobly/test_runner.py, line 299 at r6](https://reviewable.io:443/reviews/google/mobly/389#-L5BpuagYn_2aBWKCgkx:-L5BpuagYn_2aBWKCgky:b5fcmr6) ([raw file](https://github.com/google/mobly/blob/b8f1e591c00a0aa05be94ae03acb179948193602/mobly/test_runner.py#L299)):*
> ```Python
>         called. For example:
> 
>             tr = new TestRunner(...)
> ```

there is no `new` in python?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 293 at r5](https://reviewable.io:443/reviews/google/mobly/389#-L5BdB5BaGJzfOGwV95S:-L5Bw43QSxZj1TRhb3jy:b71hbig) ([raw file](https://github.com/google/mobly/blob/6066d8683ca777b48e0e5e6139a70361a4710bbf/mobly/test_runner.py#L293)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Let's avoid referring to specific implementation details when possible.

How about:

"""

Only use this method if you want to use Mobly's logger before the test run starts.

For example, when creating a suite:

.. code-block:: python

    tr = TestRunner(...)
    tr.setup_logger()
    logging.info(...)
    tr.run()

"""
</blockquote></details>

Changed, I confused myself with https://github.com/google/mobly/blob/f6b8141ffcf2106f20b7a21af6f266d66e4716da/mobly/suite_runner.py

---

*[mobly/test_runner.py, line 299 at r6](https://reviewable.io:443/reviews/google/mobly/389#-L5BpuagYn_2aBWKCgkx:-L5Bw7AZigVyvezMyl5-:b-896fix) ([raw file](https://github.com/google/mobly/blob/b8f1e591c00a0aa05be94ae03acb179948193602/mobly/test_runner.py#L299)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

there is no `new` in python?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/output_test.py, line 31 at r7](https://reviewable.io:443/reviews/google/mobly/389#-L5BwsGnf6Hua1Vr3OwR:-L5BwsGo613hAqo7I15e:bdh2mua) ([raw file](https://github.com/google/mobly/blob/97e79a5f979e8ea9485035dd821d39f28b72025b/tests/mobly/output_test.py#L31)):*
> ```Python
> 
> 
> def create_mock_test_config(base_mock_test_config):
> ```

why peel this out of the class? it's not meant to be used anywhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/output_test.py, line 31 at r7](https://reviewable.io:443/reviews/google/mobly/389#-L5BwsGnf6Hua1Vr3OwR:-L5C6LCsgs_npVjtENEk:b-63wa2) ([raw file](https://github.com/google/mobly/blob/97e79a5f979e8ea9485035dd821d39f28b72025b/tests/mobly/output_test.py#L31)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why peel this out of the class? it's not meant to be used anywhere else.
</blockquote></details>

Code re-use because I didn't want to copy and paste the config from the other test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/output_test.py, line 31 at r7](https://reviewable.io:443/reviews/google/mobly/389#-L5BwsGnf6Hua1Vr3OwR:-L5C6aJXCdclHh5WPD3w:b-s9mbee) ([raw file](https://github.com/google/mobly/blob/97e79a5f979e8ea9485035dd821d39f28b72025b/tests/mobly/output_test.py#L31)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Code re-use because I didn't want to copy and paste the config from the other test
</blockquote></details>

Sure, but why is it outside of the test class?

This is only meant to be used inside the scope of the test class right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/output_test.py, line 31 at r7](https://reviewable.io:443/reviews/google/mobly/389#-L5BwsGnf6Hua1Vr3OwR:-L5C7VvInxIZI2uiykC8:b95fg4z) ([raw file](https://github.com/google/mobly/blob/97e79a5f979e8ea9485035dd821d39f28b72025b/tests/mobly/output_test.py#L31)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Sure, but why is it outside of the test class?

This is only meant to be used inside the scope of the test class right?
</blockquote></details>

That was a bit arbitrary, I think it's outside of the class in most cases?
So did similarly here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 1 files at r8.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 316 at r8](https://reviewable.io:443/reviews/google/mobly/389#-L5CzVacZPf0icPhsSIu:-L5CzVadnkphGIu-FPeG:b-9c5ga6) ([raw file](https://github.com/google/mobly/blob/04d18ca08005ec0dcf550fd971e8a490366f09df/mobly/test_runner.py#L316)):*
> ```Python
>         """Tears down logging at the end of the test run.
> 
>         This is usually called automatically at the end of 'run' and should not
> ```

Something short should be sufficient since we already explained the context in `setup_logger`, like

"""
Call after `self.run` only if you explicitly called `self.setup_logger`.
"""

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 316 at r8](https://reviewable.io:443/reviews/google/mobly/389#-L5CzVacZPf0icPhsSIu:-L5FUp7srSjxBYpTxDZN:b-annj13) ([raw file](https://github.com/google/mobly/blob/04d18ca08005ec0dcf550fd971e8a490366f09df/mobly/test_runner.py#L316)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Something short should be sufficient since we already explained the context in `setup_logger`, like

"""
Call after `self.run` only if you explicitly called `self.setup_logger`.
"""
</blockquote></details>

That comment is completely inaccurate, there's no reason to call this even if you call setup_logger because that doesn't change the behaviour of run().

I've shortened the docstring anyways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 316 at r8](https://reviewable.io:443/reviews/google/mobly/389#-L5CzVacZPf0icPhsSIu:-L5FVM3b7K2eb0B60wwA:b-jk5yoj) ([raw file](https://github.com/google/mobly/blob/04d18ca08005ec0dcf550fd971e8a490366f09df/mobly/test_runner.py#L316)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

That comment is completely inaccurate, there's no reason to call this even if you call setup_logger because that doesn't change the behaviour of run().

I've shortened the docstring anyways.
</blockquote></details>

You are right, so basically nobody ever need to call it explicitly?

It's also kinda weird to have explicit setup and implicit teardown in `run`

I wonder if there's a better way to organize this... what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 316 at r8](https://reviewable.io:443/reviews/google/mobly/389#-L5CzVacZPf0icPhsSIu:-L5FjubVpfJQuPUnvAnk:b-o22y8m) ([raw file](https://github.com/google/mobly/blob/04d18ca08005ec0dcf550fd971e8a490366f09df/mobly/test_runner.py#L316)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Well, one use case that I did think of was that if you subclass the TestRunner and overrode, you could have multiple invocations of run() that logged to the same place.

For another way to organize it, there's what I originally implemented which was an inner class (or it could be injected instead) which proxied logging.
Not sure if worthwhile though
</blockquote></details>

The inner class adds implicit behaviors and assumptions
I don't see how that helps with this particular problem.

Should we just rename it `_teardown_logger`

---

*[mobly/test_runner.py, line 322 at r9](https://reviewable.io:443/reviews/google/mobly/389#-L5Fk4p9wV_PK6Nlaz1N:-L5Fk2YzNXZ5UW5Ooxfl:b-10ficp) ([raw file](https://github.com/google/mobly/blob/1253c5ee05afc505fce3ca02d5d6385fef53820a/mobly/test_runner.py#L322)):*
> ```Python
>         if self._log_path is not None:
>             logger.kill_test_logger(logging.getLogger())
>             self._has_logger = None
> ```

Set `self._log_path` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 316 at r8](https://reviewable.io:443/reviews/google/mobly/389#-L5CzVacZPf0icPhsSIu:-L5G0WPFR7JTEJGs7rk_:b-896fix) ([raw file](https://github.com/google/mobly/blob/04d18ca08005ec0dcf550fd971e8a490366f09df/mobly/test_runner.py#L316)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

The inner class adds implicit behaviors and assumptions
I don't see how that helps with this particular problem.

Should we just rename it `_teardown_logger`
</blockquote></details>

Done.

---

*[mobly/test_runner.py, line 322 at r9](https://reviewable.io:443/reviews/google/mobly/389#-L5Fk4p9wV_PK6Nlaz1N:-L5G0XEhdYJGmgs1xmyW:b-70510a) ([raw file](https://github.com/google/mobly/blob/1253c5ee05afc505fce3ca02d5d6385fef53820a/mobly/test_runner.py#L322)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Set `self._log_path` instead?
</blockquote></details>

Fixed and also added some unit tests because that would've been a regression

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 322 at r9](https://reviewable.io:443/reviews/google/mobly/389#-L5Fk4p9wV_PK6Nlaz1N:-L5G6hvP8bacTcIDkE_R:bvfhmzu) ([raw file](https://github.com/google/mobly/blob/1253c5ee05afc505fce3ca02d5d6385fef53820a/mobly/test_runner.py#L322)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Fixed and also added some unit tests because that would've been a regression
</blockquote></details>

Should we throw exception if setup is called when a logger is set up, or teardown is called when there is no logger, instead of silently passing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 322 at r9](https://reviewable.io:443/reviews/google/mobly/389#-L5Fk4p9wV_PK6Nlaz1N:-L5G8-pb9hKCtL8AA3b2:b-u30qoh) ([raw file](https://github.com/google/mobly/blob/1253c5ee05afc505fce3ca02d5d6385fef53820a/mobly/test_runner.py#L322)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Should we throw exception if setup is called when a logger is set up, or teardown is called when there is no logger, instead of silently passing?
</blockquote></details>

The first case doesn't make sense because that breaks calling setup logger before run().

The second case, maybe makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 322 at r9](https://reviewable.io:443/reviews/google/mobly/389#-L5Fk4p9wV_PK6Nlaz1N:-L5GFVlLPAwUDJ___MCC:bari2l3) ([raw file](https://github.com/google/mobly/blob/1253c5ee05afc505fce3ca02d5d6385fef53820a/mobly/test_runner.py#L322)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

The first case doesn't make sense because that breaks calling setup logger before run().

The second case, maybe makes sense.

</blockquote></details>

Can we restructure the code to reduce nesting?
Start with the check
```
if not condition:
  raise ...
```

---

*[mobly/test_runner.py, line 307 at r10](https://reviewable.io:443/reviews/google/mobly/389#-L5GFhyt-CMMiaYmgINF:-L5GFhyt-CMMiaYmgING:bou0rs2) ([raw file](https://github.com/google/mobly/blob/b366b2e54fd1aa93757a99fa15d26706fed09915/mobly/test_runner.py#L307)):*
> ```Python
> 
>         """
>         if self._log_path is None:
> ```

Reduce nesting?

```
if self._log_path:
  return
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 322 at r9](https://reviewable.io:443/reviews/google/mobly/389#-L5Fk4p9wV_PK6Nlaz1N:-L5GGebgttdMzjt-od7H:b-896fix) ([raw file](https://github.com/google/mobly/blob/1253c5ee05afc505fce3ca02d5d6385fef53820a/mobly/test_runner.py#L322)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Can we restructure the code to reduce nesting?
Start with the check
```
if not condition:
  raise ...
```
</blockquote></details>

Done.

---

*[mobly/test_runner.py, line 307 at r10](https://reviewable.io:443/reviews/google/mobly/389#-L5GFhyt-CMMiaYmgINF:-L5GGe4_08XYs6ZWH0x0:b-896fix) ([raw file](https://github.com/google/mobly/blob/b366b2e54fd1aa93757a99fa15d26706fed09915/mobly/test_runner.py#L307)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Reduce nesting?

```
if self._log_path:
  return
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 327 at r11](https://reviewable.io:443/reviews/google/mobly/389#-L5GmUr7EWC7f8QNpP3w:-L5GmUr7EWC7f8QNpP3x:b-cjrjx9) ([raw file](https://github.com/google/mobly/blob/e5db9235e87fec1cf9de22eb75425c90da6c8067/mobly/test_runner.py#L327)):*
> ```Python
>         if self._log_path is None:
>             raise Error(
>                 'TestRunner\'s _teardown_logger called before setup_logger!')
> ```

Use "TestRunner._teardown_logger" instead of the `\`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_runner.py, line 327 at r11](https://reviewable.io:443/reviews/google/mobly/389#-L5GmUr7EWC7f8QNpP3w:-L5GpLsjHcGwC1YYGBlC:b-896fix) ([raw file](https://github.com/google/mobly/blob/e5db9235e87fec1cf9de22eb75425c90da6c8067/mobly/test_runner.py#L327)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Use "TestRunner._teardown_logger" instead of the `\`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r10, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/389#-:-L5GqYTADbaltRCHkoeg:bnfp4nl)*

**Pull request merged**
