### PR TITLE
Implement get_devices

### PR DESCRIPTION
**Pull request by winterfroststrom**
Adds get_devices convenience function.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/357)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 339 at r1](https://reviewable.io:443/reviews/google/mobly/357#-KwhbYK2aMZtRYoILVxe:-KwhbYK2aMZtRYoILVxf:byi6xjr) ([raw file](https://github.com/google/mobly/blob/4094e3972f08c6bd0e0cfca890194de16bb04d64/mobly/controllers/android_device.py#L339)):*
> ```Python
> 
> 
> def get_device(ads, **kwargs):
> ```

To lower maintenance cost, let's not keep two versions of pretty much the same function in the long run.
How about:
In docstring, mark this as "deprecated" and "will be removed in 1.8", direct ppl to use the new API. When syncing, change all internal usages to the new one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/357)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 339 at r1](https://reviewable.io:443/reviews/google/mobly/357#-KwhbYK2aMZtRYoILVxe:-KwhxrMRrVkTvN1fvdbl:bvw17u1) ([raw file](https://github.com/google/mobly/blob/4094e3972f08c6bd0e0cfca890194de16bb04d64/mobly/controllers/android_device.py#L339)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

To lower maintenance cost, let's not keep two versions of pretty much the same function in the long run.
How about:
In docstring, mark this as "deprecated" and "will be removed in 1.8", direct ppl to use the new API. When syncing, change all internal usages to the new one.
</blockquote></details>

How do I mark something as deprecated via docstring?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/357)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 339 at r1](https://reviewable.io:443/reviews/google/mobly/357#-KwhbYK2aMZtRYoILVxe:-Kwi6u1qP9lVbl7o-6U3:bnuvksx) ([raw file](https://github.com/google/mobly/blob/4094e3972f08c6bd0e0cfca890194de16bb04d64/mobly/controllers/android_device.py#L339)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

How do I mark something as deprecated via docstring?
</blockquote></details>

I usually do it like this
https://github.com/google/mobly/blob/ec37cec8a66f929bafc1db12f76ac793bcb9a679/mobly/base_test.py#L54

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/357)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 339 at r1](https://reviewable.io:443/reviews/google/mobly/357#-KwhbYK2aMZtRYoILVxe:-KwiArxzxHZbay7aI-zv:b-p1i752) ([raw file](https://github.com/google/mobly/blob/4094e3972f08c6bd0e0cfca890194de16bb04d64/mobly/controllers/android_device.py#L339)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I usually do it like this
https://github.com/google/mobly/blob/ec37cec8a66f929bafc1db12f76ac793bcb9a679/mobly/base_test.py#L54
</blockquote></details>

added comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/357)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 339 at r2](https://reviewable.io:443/reviews/google/mobly/357#-KwiBoNYQcGTYjWxNhWs:-KwiBoNYQcGTYjWxNhWt:burzf20) ([raw file](https://github.com/google/mobly/blob/b00bf894faf55d77067f23c229fe20239d17b5e9/mobly/controllers/android_device.py#L339)):*
> ```Python
> 
> 
> def get_device(ads, **kwargs):
> ```

how about changing the deprecated to use the new one underneath to reduce code dup?

---

*[mobly/controllers/android_device.py, line 538 at r2](https://reviewable.io:443/reviews/google/mobly/357#-KwiBZRqzUFPLvza35mq:-KwiBZRqzUFPLvza35mr:b-j0asdm) ([raw file](https://github.com/google/mobly/blob/b00bf894faf55d77067f23c229fe20239d17b5e9/mobly/controllers/android_device.py#L538)):*
> ```Python
>         * Unplug USB so device loses connection.
>         * ADB connection over WiFi and WiFi got disconnected.
>         * Any other type of USB disconnection, as long as snippet session can be
> ```

this line is 81 char

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/357)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 339 at r2](https://reviewable.io:443/reviews/google/mobly/357#-KwiBoNYQcGTYjWxNhWs:-KwiE2DeXs3U9928aAUG:b-dhm5yy) ([raw file](https://github.com/google/mobly/blob/b00bf894faf55d77067f23c229fe20239d17b5e9/mobly/controllers/android_device.py#L339)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

how about changing the deprecated to use the new one underneath to reduce code dup?
</blockquote></details>

Isn't it already doing that?

---

*[mobly/controllers/android_device.py, line 538 at r2](https://reviewable.io:443/reviews/google/mobly/357#-KwiBZRqzUFPLvza35mq:-KwiEOfXwJvKJ9finQ-O:b-896fix) ([raw file](https://github.com/google/mobly/blob/b00bf894faf55d77067f23c229fe20239d17b5e9/mobly/controllers/android_device.py#L538)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this line is 81 char
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/357)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 339 at r2](https://reviewable.io:443/reviews/google/mobly/357#-KwiBoNYQcGTYjWxNhWs:-Kwn3hVQhCeAQX0JShjl:b-za53zg) ([raw file](https://github.com/google/mobly/blob/b00bf894faf55d77067f23c229fe20239d17b5e9/mobly/controllers/android_device.py#L339)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Isn't it already doing that?
</blockquote></details>

Oops, got confused. sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/357#-:-Kwn41PSHcIY5LbxEesq:bnfp4nl)*

**Pull request merged**
