### PR TITLE
Fix some style errors.

### PR DESCRIPTION
**Pull request by kdart**
Extraneous whitespace and mutable initializer variables.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/230)

### CODE REVIEW

**Comment by kdart** [comment]
I signed the CLA.

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/230#-:-Kmhzy3ClYBLtRGxDs73:bnfp4nl)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/230#-:-Kmi-AFJZQANHq8_6Qjl:bnfp4nl)*

**Comment by adorokhine** [comment]
Thanks! The bot is still showing that you haven't signed the CLA. Does https://cla.developers.google.com/ show you've signed this particular one?

**Comment by kdart** [comment]
Oh, I see. I used the wrong email address on the commit. :-(

**Comment by kdart** [comment]
Try again with new updated email.

**Pull request merged**
