### PR TITLE
Implement a simple runner for test suites.

### PR DESCRIPTION
**Pull request by adorokhine**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/171)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Unit tests are failing for py3, pls fix.

**Comment by adorokhine** [comment]
Done.

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[mobly/suite_runner.py, line 36 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4tM0qopo0w-ji6jL:-KgR4tM0qopo0w-ji6jM:b-4az2kj) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L36)):*
> ```Python
> 
>         from mobly import suite_runner
>         ...
> ```

also include the import lines for test modules.

---

*[mobly/suite_runner.py, line 38 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4zpDDMUpni7jRU3p:-KgR4zpDDMUpni7jRU3q:b-akkegd) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L38)):*
> ```Python
>         ...
>         if __name__ == '__main__':
>             suite_runner.run(my_test_1.MyTest1, my_test_2.MyTest2)
> ```

"my_test_1" and "MyTest1" violate the naming convention?

---

*[mobly/suite_runner.py, line 61 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR3GewUNRLzzC8ABxr:-KgR3GewUNRLzzC8ABxs:bnwaqye) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L61)):*
> ```Python
>         metavar='[ClassA[.test_a] ClassB[.test_b] ...]',
>         help='A list of test classes and optional test methods to execute.')
>     parser.add_argument(
> ```

I'd suggest not having this in the initial version to avoid confusion from OEMs.
If there's a clear need, we could add it back.

---

*[mobly/suite_runner.py, line 108 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR3VobWtmGjoEipJnJ:-KgR3VobWtmGjoEipJnK:b8yz9m7) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L108)):*
> ```Python
> 
>     Returns:
>         (list of tuple) identifiers for TestRunner. For the above example:
> ```

identify the type and purpose of each element in the tuple?
"Test1" is a bit misleading since it doesn't follow the naming convention of test classes...

---

*[mobly/suite_runner.py, line 116 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4Cpu9sIpNoBQLMGI:-KgR4Cpu9sIpNoBQLMGJ:bb6ef2p) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L116)):*
> ```Python
>     """
>     # Create a map from test class name to list of methods
>     tests = collections.OrderedDict()
> ```

Shouldn't this be called `test_identifiers`?

---

*[mobly/suite_runner.py, line 122 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR3zgr9NKd4-oiNGij:-KgR3zgr9NKd4-oiNGik:bcp6m59) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L122)):*
> ```Python
>                 (test_class, test_method) = test_case.split('.')
>                 if test_class not in tests:
>                     tests[test_class] = [test_method]
> ```

so this would set tests[test_class] to `['']` instead of `None`?

---

*[tests/mobly/suite_runner_test.py, line 23 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4OQjVAysfNfCL2Q2:-KgR4OQjVAysfNfCL2Q3:b-s2d703) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/tests/mobly/suite_runner_test.py#L23)):*
> ```Python
> 
> 
> class Integration2Test(IntegrationTest.IntegrationTest):
> ```

should this be in `tests.lib` instead?
so `test_runner_test.py` could use it too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171)*

**Comment by adorokhine** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[mobly/suite_runner.py, line 36 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4tM0qopo0w-ji6jL:-KgR80BHPz4H_SHOJ6iY:b-pxzljw) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L36)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

also include the import lines for test modules.
</blockquote></details>

Done.We o

---

*[mobly/suite_runner.py, line 38 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4zpDDMUpni7jRU3p:-KgR80gw4wBDzhsdzcZH:bs7wumx) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L38)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"my_test_1" and "MyTest1" violate the naming convention?
</blockquote></details>

Done. 

---

*[mobly/suite_runner.py, line 61 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR3GewUNRLzzC8ABxr:-KgR81PVw5r4SwqSlfwK:b69ko73) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I'd suggest not having this in the initial version to avoid confusion from OEMs.
If there's a clear need, we could add it back.
</blockquote></details>

sg, can it be dropped from test_runner too?

---

*[mobly/suite_runner.py, line 108 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR3VobWtmGjoEipJnJ:-KgR8cBZJxaPtRlJVKbx:b-896fix) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L108)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

identify the type and purpose of each element in the tuple?
"Test1" is a bit misleading since it doesn't follow the naming convention of test classes...
</blockquote></details>

Done.

---

*[mobly/suite_runner.py, line 116 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4Cpu9sIpNoBQLMGI:-KgR8oaFwqDhBmR5AZ_5:b-bw3eam) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L116)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Shouldn't this be called `test_identifiers`?
</blockquote></details>

test_identifiers is a list of tuples, but this is a dict mapping strings to list of strings. This dict is transformed into test_identifiers by calling list(tests.items()) as the last step.

---

*[mobly/suite_runner.py, line 122 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR3zgr9NKd4-oiNGij:-KgR92VQC8skA3AgmLHs:b-xjn0ji) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L122)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

so this would set tests[test_class] to `['']` instead of `None`?
</blockquote></details>

At this point in the code, test_method must be set (it's under the `if '.' in test_case if statement). The case you mention is handled by `# no test method; run all tests in this class.`

---

*[tests/mobly/suite_runner_test.py, line 23 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4OQjVAysfNfCL2Q2:-KgRAdRbUSYwXdsjPjtL:b-896fix) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/tests/mobly/suite_runner_test.py#L23)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should this be in `tests.lib` instead?
so `test_runner_test.py` could use it too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/suite_runner.py, line 61 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR3GewUNRLzzC8ABxr:-KgRBcO5ktRT6DiMMW-V:b-x21nld) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L61)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

sg, can it be dropped from test_runner too?
</blockquote></details>

Not sure if we want to touch that since it requires more work.
No strong preference.

---

*[mobly/suite_runner.py, line 116 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4Cpu9sIpNoBQLMGI:-KgREj9zKQm7Ic1mesYG:bosj3qn) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L116)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

test_identifiers is a list of tuples, but this is a dict mapping strings to list of strings. This dict is transformed into test_identifiers by calling list(tests.items()) as the last step.
</blockquote></details>

Can we have a more specific name for it though?
`tests` is very generic term and it's not clear what this var is at first glance.
Also it's not clear whether these are actual tests funcs or just names.

---

*[mobly/suite_runner.py, line 71 at r3](https://reviewable.io:443/reviews/google/mobly/171#-KgRF0p-VgyBVnOR5m64:-KgRF0p0oxeAjkuwNOLd:b-ann4xk) ([raw file](https://github.com/google/mobly/blob/9951122c2b4608b547d6a1ad43878b7e83287946/mobly/suite_runner.py#L71)):*
> ```Python
> 
>     # Choose which tests to run
>     test_identifiers = _compute_test_identifiers(test_classes, args.test_case)
> ```

should we do a type check on elements of `test_classes` before proceeding to parse them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171)*

**Comment by adorokhine** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/suite_runner.py, line 116 at r2](https://reviewable.io:443/reviews/google/mobly/171#-KgR4Cpu9sIpNoBQLMGI:-KgRUCuOJBXMMKXA5PK4:b-896fix) ([raw file](https://github.com/google/mobly/blob/d9bd75085b98bd3a5afb312c077f92e37ea69163/mobly/suite_runner.py#L116)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Can we have a more specific name for it though?
`tests` is very generic term and it's not clear what this var is at first glance.
Also it's not clear whether these are actual tests funcs or just names.
</blockquote></details>

Done.

---

*[mobly/suite_runner.py, line 71 at r3](https://reviewable.io:443/reviews/google/mobly/171#-KgRF0p-VgyBVnOR5m64:-KgRTOEKpEOq_a7ecdMj:b-32bbyz) ([raw file](https://github.com/google/mobly/blob/9951122c2b4608b547d6a1ad43878b7e83287946/mobly/suite_runner.py#L71)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should we do a type check on elements of `test_classes` before proceeding to parse them?
</blockquote></details>

Not sure what the motivation here is; Python is duck typed so as long as it implements __name__ it should be fine right?
https://en.wikipedia.org/wiki/Duck_typing#In_Python

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/suite_runner.py, line 71 at r3](https://reviewable.io:443/reviews/google/mobly/171#-KgRF0p-VgyBVnOR5m64:-KgRVa3yh7xQonPtpUio:b-w9dshh) ([raw file](https://github.com/google/mobly/blob/9951122c2b4608b547d6a1ad43878b7e83287946/mobly/suite_runner.py#L71)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Not sure what the motivation here is; Python is duck typed so as long as it implements __name__ it should be fine right?
https://en.wikipedia.org/wiki/Duck_typing#In_Python
</blockquote></details>

So we can fail early and give user a useful error message.
`test_runner._find_test_class` does this.

e.g. If somebody puts a unit test class here, it'll be nice to directly throw an error as opposed to failing later due to attribute error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171)*

**Comment by adorokhine** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/suite_runner.py, line 71 at r3](https://reviewable.io:443/reviews/google/mobly/171#-KgRF0p-VgyBVnOR5m64:-KgR_LLcWD2iPfIkFbYM:b2zooy5) ([raw file](https://github.com/google/mobly/blob/9951122c2b4608b547d6a1ad43878b7e83287946/mobly/suite_runner.py#L71)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

So we can fail early and give user a useful error message.
`test_runner._find_test_class` does this.

e.g. If somebody puts a unit test class here, it'll be nice to directly throw an error as opposed to failing later due to attribute error.
</blockquote></details>

It sounds like you don't like duck typing. Maybe python isn't the best choice of language for you? :) Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/suite_runner.py, line 71 at r3](https://reviewable.io:443/reviews/google/mobly/171#-KgRF0p-VgyBVnOR5m64:-KgR_Y3PvyuByOvKsmd7:b-ljc5t9) ([raw file](https://github.com/google/mobly/blob/9951122c2b4608b547d6a1ad43878b7e83287946/mobly/suite_runner.py#L71)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

It sounds like you don't like duck typing. Maybe python isn't the best choice of language for you? :) Done.
</blockquote></details>

Just this one......

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171)*

**Comment by xpconanfan** [comment]
Let's also update the tutorial to include this usage?
Doesn't have to be in this PR.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171#-:-KgR_iL_PO8s8GqpnzkF:b-ykzcu5)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/171#-:-KgR_q8lFVEnsttwHrZF:bnfp4nl)*

**Pull request merged**
