### PR TITLE
Fix the bug that event client is broken after reboot

### LINKED ISSUE #820: Android snippet client should clean event client when stopping
Android snippet client should set `self._event_client` to None when it is requested to stop. Otherwsie, after device reboot, the snippet client will still use the broken event client instead of creating a new one.

### PR DESCRIPTION
**Pull request by mhaoli**
Fixes #820.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/821)

### CODE REVIEW

**Review by xpconanfan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/821)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mhaoli and @xpconanfan)

___
*[`mobly/controllers/android_device_lib/jsonrpc_client_base.py` line 274 at r1](https://reviewable.io/reviews/google/mobly/821#-N2D3c4fBRMf-8k4ZHk5:-N2D3c4g5xsV3odqqxP4:b-ijnjtj) ([raw file](https://github.com/google/mobly/blob/e45626f677f240bcf24f38c8fcf7b167521cd085/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L274)):*
> ```Python
>       self.host_port = None
> 
>   def stop_event_client(self):
> ```

Should this be `_stop...` since the start one is `_start...`?

**Review by mhaoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/821)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @xpconanfan)

___
*[`mobly/controllers/android_device_lib/jsonrpc_client_base.py` line 274 at r1](https://reviewable.io/reviews/google/mobly/821#-N2D3c4fBRMf-8k4ZHk5:-N2FzaW-DFj40dCILhKb:bwd0o3b) ([raw file](https://github.com/google/mobly/blob/e45626f677f240bcf24f38c8fcf7b167521cd085/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L274)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Should this be `_stop...` since the start one is `_start...`?
</blockquote></details>

Moved this function to subclass and made it a protected function.

**Review by xpconanfan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/821)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mhaoli and @xpconanfan)

___
*[`mobly/controllers/android_device_lib/snippet_client.py` line 256 at r2](https://reviewable.io/reviews/google/mobly/821#-N2Kxgxs0Hpzy21iXZfy:-N2Kxgxs0Hpzy21iXZfz:baa5fk7) ([raw file](https://github.com/google/mobly/blob/6e2f5def87329e1e38ab4c856efffa94d9a34cb8/mobly/controllers/android_device_lib/snippet_client.py#L256)):*
> ```Python
>     self._stop_event_client()
> 
>   def _stop_event_client(self):
> ```

should stop come after start?

**Comment by xpconanfan** [comment]
Force merge as tests for 3.6 have been removed

**Pull request merged**
