### PR TITLE
Remove psutil usages in utils_test.

### PR DESCRIPTION
**Pull request by eric100lin**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/783)

### CODE REVIEW

**Review by booneng — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/783)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eric100lin, @xianyuanjia, and @xpconanfan)

___
*[tests/mobly/utils_test.py, line 164 at r1](https://reviewable.io/reviews/google/mobly/783#-Mr_8TrbE6qLCGxM-NBj:-Mr_8Trc0u1KJZQ8GHZw:b-idxbie) ([raw file](https://github.com/google/mobly/blob/3466a74fa6d871bf6fef01ed46387ba6a8c35166/tests/mobly/utils_test.py#L164)):*
> ```Python
>       p = utils.start_standing_subprocess(self.sleep_cmd(4))
>       self.assertTrue(_is_process_running(p.pid))
>       os.kill(p.pid, signal.SIGTERM)
> ```

Isn't the process already killed by _is_process_running? Or SIG_DFL doesn't kill the process?



_Code quote:_
```Python
 os.kill(p.pid, signal.SIGTERM)
```

**Review by eric100lin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/783)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @booneng, @xianyuanjia, and @xpconanfan)

___
*[tests/mobly/utils_test.py, line 164 at r1](https://reviewable.io/reviews/google/mobly/783#-Mr_8TrbE6qLCGxM-NBj:-Mr_9AsJ1Zmz05rFxlWp:bwb2qbj) ([raw file](https://github.com/google/mobly/blob/3466a74fa6d871bf6fef01ed46387ba6a8c35166/tests/mobly/utils_test.py#L164)):*
<details><summary><i>Previously, booneng (boon) wrote…</i></summary><blockquote>

Isn't the process already killed by _is_process_running? Or SIG_DFL doesn't kill the process?
</blockquote></details>

signal.SIG_DFL do not kill the process, it check the process is running or not.



_Code quote:_
```Python
signal.SIG_DFL
```

**Review by booneng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/783)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eric100lin, @xianyuanjia, and @xpconanfan)

___
*[tests/mobly/utils_test.py, line 164 at r1](https://reviewable.io/reviews/google/mobly/783#-Mr_8TrbE6qLCGxM-NBj:-Mr_Cpga-ktYmc5LjKpV:by43jfv) ([raw file](https://github.com/google/mobly/blob/3466a74fa6d871bf6fef01ed46387ba6a8c35166/tests/mobly/utils_test.py#L164)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

signal.SIG_DFL do not kill the process, it check the process is running or not.
</blockquote></details>

why not use poll() to check if the process is still running?

**Review by eric100lin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/783)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @booneng, @xianyuanjia, and @xpconanfan)

___
*[tests/mobly/utils_test.py, line 164 at r1](https://reviewable.io/reviews/google/mobly/783#-Mr_8TrbE6qLCGxM-NBj:-Mr_Et1qDQpU-Fr4a2j-:bluhisa) ([raw file](https://github.com/google/mobly/blob/3466a74fa6d871bf6fef01ed46387ba6a8c35166/tests/mobly/utils_test.py#L164)):*
<details><summary><i>Previously, booneng (boon) wrote…</i></summary><blockquote>

why not use poll() to check if the process is still running?
</blockquote></details>

When using `self.assertIsNotNone(p.poll())`, it doesn't work and blocking until command exit on gLinux.

**Review by booneng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/783)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @xianyuanjia and @xpconanfan)

**Pull request merged**
