### PR TITLE
Fix snippet client for NBU devices.

### LINKED ISSUE #174: Unable to launch MBS on xiaomi devices
Could it be that the recent changes in shell has broken the fragile regex matching of adb output...
This happened on mac:
```
$ snippet_shell.py com.google.android.mobly.snippet.bundled
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/snippet_shell.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 64, in <module>
    SnippetShell(args.package[0]).main(args.serial)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 91, in main
    self.start_console()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 76, in start_console
    self._start_services(console_env)
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 41, in _start_services
    self._ad.load_snippet(name='snippet', package=self._package)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 629, in load_snippet
    self._start_jsonrpc_client(client)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 660, in _start_jsonrpc_client
    client.check_app_installed()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/snippet_client.py", line 110, in check_app_installed
    target_name = match.group(3)
AttributeError: 'NoneType' object has no attribute 'group'
```

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #174

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/175)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 250 at r1](https://reviewable.io:443/reviews/google/mobly/175#-KgacVfCeAQGSYPypFTX:-KgacVfCeAQGSYPypFTY:bf8qlly) ([raw file](https://github.com/google/mobly/blob/061a4ed4fc46cf746ccc47580fa601fc87c67ff2/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L250)):*
> ```Python
>             # tools used in grep cmd like `tr`.
>             return self._adb.shell(
>                 adb_shell_cmd, shell=True).decode('utf-8').rstrip()
> ```

I'm afraid this will break Windows support, as not all host operating systems have the cli tools used in grep cmd like 'grep'. :)

I think we'll need to either:
a) expose the shell arg in _adb_grep_wrapper so that you as a test writer can decide where the grep runs, or
b) run grep commands on device with a limited set of commands only, and do all subsequent processing in code on the python side. eg instead of tr, do just the grep command and then use str.replace() in python instead of tr.

Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/175)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 250 at r1](https://reviewable.io:443/reviews/google/mobly/175#-KgacVfCeAQGSYPypFTX:-Kgadbq6zka5ajdRVSBa:b6o9kom) ([raw file](https://github.com/google/mobly/blob/061a4ed4fc46cf746ccc47580fa601fc87c67ff2/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L250)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I'm afraid this will break Windows support, as not all host operating systems have the cli tools used in grep cmd like 'grep'. :)

I think we'll need to either:
a) expose the shell arg in _adb_grep_wrapper so that you as a test writer can decide where the grep runs, or
b) run grep commands on device with a limited set of commands only, and do all subsequent processing in code on the python side. eg instead of tr, do just the grep command and then use str.replace() in python instead of tr.

Thoughts?
</blockquote></details>

Seems too much trouble to users for a test to decide to grep or not.

Seems like the only way is to get the output and do `re` match in python and not use grep?
Do you remember why we didn't do that...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/175)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 250 at r1](https://reviewable.io:443/reviews/google/mobly/175#-KgacVfCeAQGSYPypFTX:-KgaeYwSatmuf5xgOrto:b-3v7zk3) ([raw file](https://github.com/google/mobly/blob/061a4ed4fc46cf746ccc47580fa601fc87c67ff2/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L250)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Seems too much trouble to users for a test to decide to grep or not.

Seems like the only way is to get the output and do `re` match in python and not use grep?
Do you remember why we didn't do that...
</blockquote></details>

Doing all the matching in python sgtm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/175)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 250 at r1](https://reviewable.io:443/reviews/google/mobly/175#-KgacVfCeAQGSYPypFTX:-KgqVR18iz5papakFkFC:bb6un1j) ([raw file](https://github.com/google/mobly/blob/061a4ed4fc46cf746ccc47580fa601fc87c67ff2/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L250)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Doing all the matching in python sgtm
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/175)*

**Comment by adorokhine** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 113 at r2](https://reviewable.io:443/reviews/google/mobly/175#-Kgqr_MCQCk-Erjj7Q20:-Kgqr_MCQCk-Erjj7Q21:b5si6cx) ([raw file](https://github.com/google/mobly/blob/11dd141e2c758d99262b3f4f21dd98d1c532abc8/mobly/controllers/android_device_lib/snippet_client.py#L113)):*
> ```Python
>         # same as the snippet package.
>         if target_name != self.package:
>             out = self._adb.shell(r'pm list package')
> ```

r prefix no longer needed, here and elsewhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/175)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/175#-:-Kgr1DpDhCJ-Lw0gxryr:bnfp4nl)*

**Pull request merged**
