### PR TITLE
Add a data type for callback event.

### LINKED ISSUE #129: Create an `event` type on the client side
So instead of dealing with the dict and key access:
```
{u'callbackId': u'2-2', u'data': {u'isSuccess': True}, u'name': u'status', u'time': 1487989424790}
```
We could have some sort of structure:
```
event.data -> {'isSuccess': True}
event.name -> 'status'
event.creation_time -> 1487989424790
```

### PR DESCRIPTION
**Pull request by xpconanfan**
fixes #129

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/134)

### CODE REVIEW

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 59 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafhOKadEKJiLgP7gH:-KeafhOLrEIcl4RQ0eT3:b-kx858c) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L59)):*
> ```Python
>         self.ret_value = ret_value
> 
>     def _msgToEvent(self, raw_event):
> ```

Our Python style is lowercase_with_underscores.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 63 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafmHMPALFwnwIopJG:-KeafmHMPALFwnwIopJH:b-akwad4) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L63)):*
> ```Python
>             callback_id=raw_event['callbackId'],
>             name=raw_event['name'],
>             creation_tie=raw_event['time'],
> ```

tie? I don't think this would run; can you test this?

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 66 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafukV0V8RVakOJdMM:-KeafukV0V8RVakOJdMN:b-9nmx1w) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L66)):*
> ```Python
>             data=raw_event['data'])
> 
>     def waitAndGet(self, event_name, timeout=None):
> ```

Should be lowercase_with_underscores right? (and elsewhere)

---

*[mobly/controllers/android_device_lib/snippet_event.py, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/134#-Keag8VONgs_comAMvjD:-Keag8VONgs_comAMvjE:b-8q37n6) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/snippet_event.py#L1)):*
> ```Python
> #/usr/bin/env python3.4
> ```

1. Don't quite understand why we are creating new files without the bang. Is it supposed to be there or isn't it?
2. Since this isn't a main class and isn't intended to be executed directly, no bang line is needed.

---

*[mobly/controllers/android_device_lib/snippet_event.py, line 23 at r1](https://reviewable.io:443/reviews/google/mobly/134#-Keag5vDpkhj42nrEfqp:-Keag5vEcTvkA8DeVpq_:bkaa4h2) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/snippet_event.py#L23)):*
> ```Python
> class SnippetEvent(object):
>     """The class that represents callback events for mobly snippet library.
>     
> ```

Whitespace on indented line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/134)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 63 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafmHMPALFwnwIopJG:-Keaih1W4qlZRt5zcACw:b-896fix) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L63)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

tie? I don't think this would run; can you test this?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 66 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafukV0V8RVakOJdMM:-KeagrCsfOUTVWNCG-J2:bohdahi) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L66)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Should be lowercase_with_underscores right? (and elsewhere)
</blockquote></details>

Hmm, should we?
This class deals with data from Java side and is closely tied with the Java method names, it seems make sense to use camel case here.

```
callback = ad.spt.doAsyncStuff()
callback.waitAndGet('blahEvent')
```

---

*[mobly/controllers/android_device_lib/snippet_event.py, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/134#-Keag8VONgs_comAMvjD:-Keah2cmy_OYwhjiO1-o:b-896fix) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/snippet_event.py#L1)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

1. Don't quite understand why we are creating new files without the bang. Is it supposed to be there or isn't it?
2. Since this isn't a main class and isn't intended to be executed directly, no bang line is needed.
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/snippet_event.py, line 23 at r1](https://reviewable.io:443/reviews/google/mobly/134#-Keag5vDpkhj42nrEfqp:-Keah30E7XriE80Se1Ju:b-896fix) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/snippet_event.py#L23)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Whitespace on indented line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/134)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 63 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafmHMPALFwnwIopJG:-Kealgjf9qegfnk_UPvi:bdakz5s) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L63)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did we have a unit test capable of catching this?

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 66 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafukV0V8RVakOJdMM:-Kealn3xeLpy4qz8xwFz:b-6e7p7t) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L66)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, should we?
This class deals with data from Java side and is closely tied with the Java method names, it seems make sense to use camel case here.

```
callback = ad.spt.doAsyncStuff()
callback.waitAndGet('blahEvent')
```
</blockquote></details>

For the method names that map directly to the java side like waitAndGet <-> eventWaitAndGet, sg.
For unrelated method names like _msgToEvent we should maintain our python convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/134)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 59 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafhOKadEKJiLgP7gH:-Keb0Fl52Y_09mhX2EcR:b-896fix) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L59)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Our Python style is lowercase_with_underscores.
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 63 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafmHMPALFwnwIopJG:-Keb0GMXDLBQkBPF_jDB:b-896fix) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L63)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Did we have a unit test capable of catching this?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 66 at r1](https://reviewable.io:443/reviews/google/mobly/134#-KeafukV0V8RVakOJdMM:-Keb0GybKDoO7No6vN6E:b-896fix) ([raw file](https://github.com/google/mobly/blob/ac07cff0770546fe6ffc9087d423d3236400775c/mobly/controllers/android_device_lib/callback_handler.py#L66)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

For the method names that map directly to the java side like waitAndGet <-> eventWaitAndGet, sg.
For unrelated method names like _msgToEvent we should maintain our python convention.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/134)*

**Comment by adorokhine** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_lib/callback_handler_test.py, line 42 at r3](https://reviewable.io:443/reviews/google/mobly/134#-Keb3TNWhm1veWNWxwy0:-Keb3TNWhm1veWNWxwy1:b-kkxbju) ([raw file](https://github.com/google/mobly/blob/b3d6d78c2855411ed3ec35a3f3e01eba7ebc3291/tests/mobly/controllers/android_device_lib/callback_handler_test.py#L42)):*
> ```Python
>         mock_event_client.eventWaitAndGet = mock.Mock(return_value=MOCK_RAW_EVENT)
>         handler = callback_handler.CallbackHandler(MOCK_CALLBACK_ID,
>                                                    mock_event_client, None, None)
> ```

Can you change this to kwargs so the meaning of the two Nones is clearer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/134)*

**Comment by xpconanfan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_lib/callback_handler_test.py, line 42 at r3](https://reviewable.io:443/reviews/google/mobly/134#-Keb3TNWhm1veWNWxwy0:-KebLP7CiCjz4E8MrI22:b-896fix) ([raw file](https://github.com/google/mobly/blob/b3d6d78c2855411ed3ec35a3f3e01eba7ebc3291/tests/mobly/controllers/android_device_lib/callback_handler_test.py#L42)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can you change this to kwargs so the meaning of the two Nones is clearer?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/134)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/134#-:-KebPTqrpHKK-5HOzqt1:bnfp4nl)*

**Pull request merged**
