### PR TITLE
Add retry and repeat number to test result record

### PR DESCRIPTION
**Pull request by booneng**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/861)

### CODE REVIEW

**Comment by xpconanfan** [comment]
I'm not sure why we need to add this now if everything worked without these before.

We need to be extra careful about adding more fields in the result record and making public API changes.

**Review by booneng — COMMENTED** [review]
We have several users who generate tests and append digits to the test case name and have some monitoring setups that depend on it. In these cases, when parsing the test_summary.yaml, it is impossible to distinguish between user added digits or if it is a Mobly repeated case. This is blocking some of the new stuff.

> *[Reviewable](https://reviewable.io/reviews/google/mobly/861#-:-NKuZ9ke03e7W0Jn6fr_:b3kfuwy)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @xpconanfan)

**Comment by booneng** [comment]
>

**Comment by booneng** [comment]
> I'm not sure why we need to add this now if everything worked without these before.
> 
> We need to be extra careful about adding more fields in the result record and making public API changes.

We have several users who generate tests and append digits to the test case name and have some monitoring setups that depend on it. In these cases, when parsing the test_summary.yaml, it is impossible to distinguish between user added digits or if it is a Mobly repeated case. This is blocking some of the new stuff.

**Review by xpconanfan — COMMENTED** [review]
The use case requirement sounds reasonable
but the solution is a little cumbersome.

Basically it's fair to express info specific to repeat/retry, and we already have `RECORD_RETRY_PARENT` which is in the same category.
But we can't keep adding new field for this area as we go. Let's think about how to handle this in a more efficient and proper design? I'm ok with deprecating `RECORD_RETRY_PARENT` if the new expression can capture all we need.

> *[Reviewable](https://reviewable.io/reviews/google/mobly/861#-:-NKxKI6-8e7tQWeK_m7v:b-cpip3m)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @booneng)

**Pull request closed without merging**
