### PR TITLE
Use a constant for the 'adb' command instead of hardcoding it.

### PR DESCRIPTION
**Pull request by adorokhine**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/201)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 23 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsQFm6JCsudhoAHYE:-KjOsQFm6JCsudhoAHYF:bwjvt5g) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L23)):*
> ```Python
> 
> # Command to use for running ADB commands.
> ADB = 'adb'
> ```

This doesn't cover standing adb calls like `adb logcat`, which are started directly with Popen.

I don't understand why this is required? If MH can set the adb path correctly, so could some user?

---

*[mobly/controllers/android_device_lib/adb.py, line 121 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsbeGN-5O7GRitYm0:-KjOsbeGN-5O7GRitYm1:b-o8ncqm) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L121)):*
> ```Python
>         if shell:
>             if self.serial:
>                 adb_cmd = '"%s" -s "%s" %s %s' % (ADB, self.serial, name, args)
> ```

why the extra quotation mark?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/201)*

**Comment by adorokhine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 23 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsQFm6JCsudhoAHYE:-KjOwox2lrcjCtlzp7No:bu4sn4m) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L23)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This doesn't cover standing adb calls like `adb logcat`, which are started directly with Popen.

I don't understand why this is required? If MH can set the adb path correctly, so could some user?
</blockquote></details>

I've updated the usage for logcat as well. Take a look at android_device.py in the same PR.

It's nice to have commands as constants instead of hardcoded strings.

---

*[mobly/controllers/android_device_lib/adb.py, line 121 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsbeGN-5O7GRitYm0:-KjOwy1tKrnDvCXteIa6:b-pndg9) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L121)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why the extra quotation mark?
</blockquote></details>

In case the full adb path contains spaces. This is pretty common on Windows. ("Program Files")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/201)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 23 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsQFm6JCsudhoAHYE:-KjP4zswkwAAZIC87u4l:bxqz39) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L23)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I've updated the usage for logcat as well. Take a look at android_device.py in the same PR.

It's nice to have commands as constants instead of hardcoded strings.
</blockquote></details>

Can we add apis in adb proxy to start long standing adb cmds instead of changing case by case?
This will allow users to take advantage of it too.

I think snippet client also needs this.

---

*[mobly/controllers/android_device_lib/adb.py, line 121 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsbeGN-5O7GRitYm0:-KjOxy22GVEnq45mPuKF:b-b412bx) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L121)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

In case the full adb path contains spaces. This is pretty common on Windows. ("Program Files")
</blockquote></details>

Add a commend?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/201)*

**Comment by adorokhine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 23 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsQFm6JCsudhoAHYE:-KjPAMzaoAWM4u7oUVoH:b-q3r48p) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L23)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Can we add apis in adb proxy to start long standing adb cmds instead of changing case by case?
This will allow users to take advantage of it too.

I think snippet client also needs this.
</blockquote></details>

Sure; mind if I do that in another PR? I'd prefer to start small and pull the hardcoded string into a constant first.

---

*[mobly/controllers/android_device_lib/adb.py, line 121 at r1](https://reviewable.io:443/reviews/google/mobly/201#-KjOsbeGN-5O7GRitYm0:-KjPAlA04TMCSN-wqzWB:b-896fix) ([raw file](https://github.com/google/mobly/blob/93920a518798e90a864e06370445fdabb1895914/mobly/controllers/android_device_lib/adb.py#L121)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Add a commend?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/201)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/201#-:-KjPCFtPNt1YDB08uSch:bnfp4nl)*

**Pull request merged**
