### PR TITLE
Initialize dicts for TestRunConfig's dict values.

### PR DESCRIPTION
**Pull request by mderu**
Defaults the controller and user_params to empty dictionaries in TestRunConfig.

These defaults prevent users from needing to check if they are None
first, in case the runner left these values unset.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/651)

### CODE REVIEW

**Comment by mderu** [comment]
___
*[tests/mobly/config_parser_test.py, line 14 at r1](https://reviewable.io/reviews/google/mobly/651#-LrpUaEx0wKe7h8Tb_bs:-LrpUaEx0wKe7h8Tb_bt:b-d36awt) ([raw file](https://github.com/google/mobly/blob/dda897e98e7db146ad423758d347b404d8f059bf/tests/mobly/config_parser_test.py#L14)):*
> ```Python
> # See the License for the specific language governing permissions and
> # limitations under the License.
> ```

Note: the changes in each line are due to the line endings of this file being \r\n instead of \n. These are separate commits, but are in the same pull request.

**Comment by mderu** [comment]
___
*[tests/mobly/config_parser_test.py, line 14 at r1](https://reviewable.io/reviews/google/mobly/651#-LrpUaEx0wKe7h8Tb_bs:-LrpUnZY-bdfdGJbHAEk:ba8i7rj) ([raw file](https://github.com/google/mobly/blob/dda897e98e7db146ad423758d347b404d8f059bf/tests/mobly/config_parser_test.py#L14)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why are we changing the line ending?
</blockquote></details>

Because they aren't in line with the rest of the files in Mobly.

**Comment by xpconanfan** [comment]
Please sync and rebase against master HEAD, then push again (use force if necessary)

**Comment by mderu** [comment]
> For future reference, the correct way is to upload a formatting PR to fix the large scale lint issues, then upload the code change.
> Will let this one in since it's a pretty small change.
> 
> > _[Reviewable](https://reviewable.io/reviews/google/mobly/651#-:-LryxcsO09mgNc7nkiki:b-z2spu8)_ status: 0 of 2 files reviewed, all discussions resolved (waiting on @mderu)

I was trying to find a way to upload two PRs that depend on one another, but it doesn't seem possible in GitHub. In this PR, the formatting change is a separate commit from the code change. If you merge into master without squashing, these two changes will remain separate within the git history.

**Comment by mderu** [comment]
Fixing history, needs work.

**Comment by mderu** [comment]
Splitting into multiple PRs.

**Pull request closed without merging**
