### PR TITLE
Wrap `socket.error` with `DeviceError` so it includes device id.

### LINKED ISSUE #350: Socket errors thrown from device obj are not marked with device tag
We should wrap `socket.error` with a child class of `DeviceError`.

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #350 

This change is [Reviewable](https://reviewable.io/reviews/google/mobly/370)

### CODE REVIEW

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 235 at r1](https://reviewable.io:443/reviews/google/mobly/370#-L-9d-dMsJ0eNBIdJUTW:-L-9d-dMsJ0eNBIdJUTX:bcwp9vd) ([raw file](https://github.com/google/mobly/blob/c13a3033e97e525cd7103d0d768192d3714fa029/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L235)):*
> responges
responses? but still seem a little strangely worded.  "The raw response byte string" probably enough?

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 238 at r1](https://reviewable.io:443/reviews/google/mobly/370#-L-9dCpFULz5yH1DthCW:-L-9dCpFULz5yH1DthCX:bbjoqjv) ([raw file](https://github.com/google/mobly/blob/c13a3033e97e525cd7103d0d768192d3714fa029/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L238)):*
> occured
occurred

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 264 at r1](https://reviewable.io:443/reviews/google/mobly/370#-L-9exfHRP94635w8gzf:-L-9exfHRP94635w8gzg:b5nva90) ([raw file](https://github.com/google/mobly/blob/c13a3033e97e525cd7103d0d768192d3714fa029/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L264)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>         self._client.write(
>             json.dumps({
>                 'cmd': command,
>                 'uid': uid
>             }).encode("utf8") + b'\n')
>         self._client.flush()
</details>
To keep consistency, how about putting try/except around _client operations instead of just the read so that similar DeviceError can be raise in case write() or flush() raises?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/370)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 235 at r1](https://reviewable.io:443/reviews/google/mobly/370#-L-9d-dMsJ0eNBIdJUTW:-L-9gr3YNipnmnxD7xjU:b-896fix) ([raw file](https://github.com/google/mobly/blob/c13a3033e97e525cd7103d0d768192d3714fa029/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L235)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

> responges
responses? but still seem a little strangely worded.  "The raw response byte string" probably enough?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 238 at r1](https://reviewable.io:443/reviews/google/mobly/370#-L-9dCpFULz5yH1DthCW:-L-9gsOE2F6c3PMaUo8b:b-896fix) ([raw file](https://github.com/google/mobly/blob/c13a3033e97e525cd7103d0d768192d3714fa029/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L238)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

> occured
occurred
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 264 at r1](https://reviewable.io:443/reviews/google/mobly/370#-L-9exfHRP94635w8gzf:-L-9ixsf9D11S8A8so_G:b-896fix) ([raw file](https://github.com/google/mobly/blob/c13a3033e97e525cd7103d0d768192d3714fa029/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L264)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

>         self._client.write(
>             json.dumps({
>                 'cmd': command,
>                 'uid': uid
>             }).encode("utf8") + b'\n')
>         self._client.flush()
To keep consistency, how about putting try/except around _client operations instead of just the read so that similar DeviceError can be raise in case write() or flush() raises?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/370)*

**Comment by k2fong** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 302 at r2](https://reviewable.io:443/reviews/google/mobly/370#-L-DwE2b_LT5tnsQ6Afz:-L-DwE2b_LT5tnsQ6Ag-:b-troe8s) ([raw file](https://github.com/google/mobly/blob/1838a01cc1979c11295895336ac1e7fb55cb763a/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L302)):*
> ```Python
>             data = {'id': apiid, 'method': method, 'params': args}
>             request = json.dumps(data)
>             self._client_send(request.encode("utf8") + b'\n')
> ```

nit, how about handling the encoding and b'\n' inside _client_send()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/370#-:-L-DwULXkkig71kPppui:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 302 at r2](https://reviewable.io:443/reviews/google/mobly/370#-L-DwE2b_LT5tnsQ6Afz:-L-Dy-6cfaBrKXmtE3UY:b-896fix) ([raw file](https://github.com/google/mobly/blob/1838a01cc1979c11295895336ac1e7fb55cb763a/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L302)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

nit, how about handling the encoding and b'\n' inside _client_send()?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/370)*

**Pull request merged**
