### PR TITLE
Fix abort class in `setup_test` and procedure functions.

### LINKED ISSUE #322: `signals.TestAbortClass` does not work in `setup_test` and `on_xxxx` methods
It is valid to abort the class at any stage of a test.

E.g. If we find out in `on_fail` that a test failed due to a fatal error like snippet_client losing socket connection, it is reasonable for the test to abort all subsequent tests in the class instead of continue running and failing more tests when we know they will fail.

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #322

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/323)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW8dICenAvZlCo5EPy:-KsW8dICenAvZlCo5EPz:bc0xqwv) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L321)):*
> ```Python
>             # will not be modified.
>             func(copy.deepcopy(tr_record))
>         except (signals.TestAbortAll, signals.TestAbortClass):
> ```

How about having one of these subclass the other or both of them subclassing from something like `signals.TestAbort`. It seems their handling is often very similar.

---

*[mobly/base_test.py, line 349 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW89wWCGfYzGYozVN4:-KsW89wWCGfYzGYozVN5:b-pgdkr0) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L349)):*
> ```Python
>                 try:
>                     self._setup_test(test_name)
>                 except (signals.TestAbortAll, signals.TestAbortClass):
> ```

Why is this needed? Wouldn't they be raised anyway?

---

*[mobly/base_test.py, line 368 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW8_r_xwSxCOA91u5X:-KsW8_r_xwSxCOA91u5Y:bxthl54) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L368)):*
> ```Python
>                 try:
>                     self._teardown_test(test_name)
>                 except signals.TestAbortAll:
> ```

Does this need the same treatment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/mobly/base_test_test.py, line 780 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsLbUjtTowbfMVKVkYq:-KsLbUjuEJrAru-PfJfg:bbi2jmz) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/tests/mobly/base_test_test.py#L780)):*
> ```Python
>         bt_cls.run(test_names=["test_1", "test_2", "test_3"])
>         self.assertEqual(len(bt_cls.results.skipped), 2)
>         self.assertEqual(bt_cls.results.summary_str(),
> ```

consider asserting on values from bt_cls.summary_dict() instead or similar len comparison above on the other summary results.  plus 'skipped' check is redundant and test will be more susceptible to format changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/base_test.py, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW8dICenAvZlCo5EPy:-KsfESx857NKFKpEj7F0:b-896fix) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L321)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

How about having one of these subclass the other or both of them subclassing from something like `signals.TestAbort`. It seems their handling is often very similar.
</blockquote></details>

Done.

---

*[mobly/base_test.py, line 349 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW89wWCGfYzGYozVN4:-Ksf7OVznst44Y5kUKvg:b-7xle7c) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L349)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Why is this needed? Wouldn't they be raised anyway?
</blockquote></details>

So they don't fall to the next `except` and get converted to TestError.

---

*[mobly/base_test.py, line 368 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW8_r_xwSxCOA91u5X:-KsfERkA9Kclo_q7SjRj:b-896fix) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L368)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Does this need the same treatment?
</blockquote></details>

Done.

---

*[tests/mobly/base_test_test.py, line 780 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsLbUjtTowbfMVKVkYq:-Ksf73Vo1RhZ2v9ji8if:b-1fg0vl) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/tests/mobly/base_test_test.py#L780)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

consider asserting on values from bt_cls.summary_dict() instead or similar len comparison above on the other summary results.  plus 'skipped' check is redundant and test will be more susceptible to format changes.
</blockquote></details>

We specifically chose to verify this string as it is user-facing.
Since the string has all the info, we don't need a separate check for the dict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by dthkao** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/base_test.py, line 349 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW89wWCGfYzGYozVN4:-KsgL-Sv8l0YmluAy2mm:bit11dr) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L349)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

So they don't fall to the next `except` and get converted to TestError.
</blockquote></details>

The next except only catches TestFailure though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by k2fong** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/mobly/base_test_test.py, line 780 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsLbUjtTowbfMVKVkYq:-KsioSRefUXtm5KaI4Rf:b-wtk41s) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/tests/mobly/base_test_test.py#L780)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

We specifically chose to verify this string as it is user-facing.
Since the string has all the info, we don't need a separate check for the dict.
</blockquote></details>

If that's the case, it will seem like verification for this summary string should be its own test that properly test out the various values reported from this summary string (if it doesn't exist already).  But probably outside the scope of this review. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/base_test.py, line 349 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW89wWCGfYzGYozVN4:-KsivUyUSfXVYTMfozsQ:b31vzk8) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L349)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

The next except only catches TestFailure though?
</blockquote></details>

Done.

Oops, somehow I thought it was TestSignal...

---

*[tests/mobly/base_test_test.py, line 780 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsLbUjtTowbfMVKVkYq:-KsivZ92ZwohGN6R-Jzq:bvadmfs) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/tests/mobly/base_test_test.py#L780)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

If that's the case, it will seem like verification for this summary string should be its own test that properly test out the various values reported from this summary string (if it doesn't exist already).  But probably outside the scope of this review. 
</blockquote></details>

No, each test expects a different summaryve string with different info.
It's a lot easier to just verify the final product than each field every time here in `base_test_test`.

We have per-field checks in `record_test`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by dthkao** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW8dICenAvZlCo5EPy:-Ksjg0vsD3X1FsX0rjFU:bpfivby) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L321)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

TestAbortSignal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/323#-KsW8dICenAvZlCo5EPy:-KsjhytFPELpCYP1O8qw:b-896fix) ([raw file](https://github.com/google/mobly/blob/4fb6d1a9cee058cf24bf5a7c8d76f355862f0388/mobly/base_test.py#L321)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

TestAbortSignal?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/323#-:-KsjlHk5nrYhSRvee85q:bnfp4nl)*

**Pull request merged**
