### PR TITLE
Add a list of test names to summary.

### LINKED ISSUE #271: add a prefix document to test_summary.yaml with requested tests
This could be dumped before any test cases are run

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #271

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/279)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/279#-KqFgaA3dUDwcpw4Ygiu:-KqFgaA3dUDwcpw4Ygiv:b-wjrgfc) ([raw file](https://github.com/google/mobly/blob/b6686bb09105a416b5155a0cceac1a06272cc3ec/mobly/records.py#L429)):*
> ```Python
>         return json_str
> 
>     def get_requested_test_names(self):
> ```

What prevents someone from accessing self.requested? (As we do?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/279)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/279#-KqFgaA3dUDwcpw4Ygiu:-KqOodMnUi49SWUftmdp:bh7y1z9) ([raw file](https://github.com/google/mobly/blob/b6686bb09105a416b5155a0cceac1a06272cc3ec/mobly/records.py#L429)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

What prevents someone from accessing self.requested? (As we do?)
</blockquote></details>

test does not have access to the record object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/279)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/279#-KqFgaA3dUDwcpw4Ygiu:-KqOptsgc7YNqR5aNy-L:b1fqnmy) ([raw file](https://github.com/google/mobly/blob/b6686bb09105a416b5155a0cceac1a06272cc3ec/mobly/records.py#L429)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

How/where is this function used, then?
</blockquote></details>

It's used by Mobly itself. Are you seeing all the diffs in your view?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/279)*

**Comment by dthkao** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/279#-KqFgaA3dUDwcpw4Ygiu:-KqOr4mFdxohb-QvcJXD:b-dhv434) ([raw file](https://github.com/google/mobly/blob/b6686bb09105a416b5155a0cceac1a06272cc3ec/mobly/records.py#L429)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It's used by Mobly itself. Are you seeing all the diffs in your view?
</blockquote></details>

I am. There's no new usage of it in the diff?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/279)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/279#-KqFgaA3dUDwcpw4Ygiu:-KqOrZNzcJvlKNzBYhl-:b-m8finj) ([raw file](https://github.com/google/mobly/blob/b6686bb09105a416b5155a0cceac1a06272cc3ec/mobly/records.py#L429)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I am. There's no new usage of it in the diff?
</blockquote></details>

Hmmmm, you're right.
I think the idea behind this was to keep the job of serializing this results object in this class, but I didn't finish the job...

All the other entries are dicts, whereas the test names are just a list.
So we need a key to be associated with the list.
I was gonna put the key in this method, but somehow ended up with the current implementation, sorry...

Will upload a new patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/279)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/279#-KqFgaA3dUDwcpw4Ygiu:-KqOvJCDVXkFJwXFKZeT:b-896fix) ([raw file](https://github.com/google/mobly/blob/b6686bb09105a416b5155a0cceac1a06272cc3ec/mobly/records.py#L429)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmmmm, you're right.
I think the idea behind this was to keep the job of serializing this results object in this class, but I didn't finish the job...

All the other entries are dicts, whereas the test names are just a list.
So we need a key to be associated with the list.
I was gonna put the key in this method, but somehow ended up with the current implementation, sorry...

Will upload a new patch.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/279)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/279#-:-KqOzAiQYu8XZTFQYYdN:bnfp4nl)*

**Pull request merged**
