### PR TITLE
APIs to add additional blocks in test summary file

### PR DESCRIPTION
**Pull request by xpconanfan**
So tests can write additional relevant data to summary file.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/376)

### CODE REVIEW

**Comment by dthkao** [comment]
Is this still a thing?

**Comment by dthkao** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 342 at r1](https://reviewable.io:443/reviews/google/mobly/376#-L5E0jt2sGwdEBZbI_M7:-L5E0jt2sGwdEBZbI_M8:behan9l) ([raw file](https://github.com/google/mobly/blob/0457a60f7be190760bf27e418f0433725f6e6526/mobly/base_test.py#L342)):*
> ```Python
>         debugging or post-test analysis.
> 
>         Each call adds a new entry to the summary file, with no guarantee of
> ```

This no guarantee part scares me. Could it possibly affect downstream parsers of test_summary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/376)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 342 at r1](https://reviewable.io:443/reviews/google/mobly/376#-L5E0jt2sGwdEBZbI_M7:-L5HFgGiHXPtu_keml0x:by8aipr) ([raw file](https://github.com/google/mobly/blob/0457a60f7be190760bf27e418f0433725f6e6526/mobly/base_test.py#L342)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

This no guarantee part scares me. Could it possibly affect downstream parsers of test_summary?
</blockquote></details>

The order of the entries are not guaranteed by design, except maybe the first entry which is the test list.
Parsers should iterate through each record and group them by type when parsing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/376)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 342 at r1](https://reviewable.io:443/reviews/google/mobly/376#-L5E0jt2sGwdEBZbI_M7:-L5Ha_65qaHq61qwJyrf:bt326sl) ([raw file](https://github.com/google/mobly/blob/0457a60f7be190760bf27e418f0433725f6e6526/mobly/base_test.py#L342)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

The order of the entries are not guaranteed by design, except maybe the first entry which is the test list.
Parsers should iterate through each record and group them by type when parsing.
</blockquote></details>

Fair enough. Not for this PR, but maybe we should document the test_summary schema more officially (possbly in a docstring in records.py?)

---

*[mobly/base_test.py, line 345 at r1](https://reviewable.io:443/reviews/google/mobly/376#-L5HaRZpT82g6Q6cfUwd:-L5HaRZpT82g6Q6cfUwe:b-omh5n7) ([raw file](https://github.com/google/mobly/blob/0457a60f7be190760bf27e418f0433725f6e6526/mobly/base_test.py#L345)):*
> ```Python
>         its position among the summary file entries.
> 
>         The content should be a dict. If absent timestamp field is added for
> ```

comma after absent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/376#-:-L5HbtCbsHd1GTpmwYR0:bnfp4nl)*

**Comment by k2fong** [comment]
:lgtm:

Sorry, must have missed this review while I was out.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/records.py, line 119 at r1](https://reviewable.io:443/reviews/google/mobly/376#-L5HiMccS3LdEkS133rx:-L5HiMccS3LdEkS133ry:bsxsjlc) ([raw file](https://github.com/google/mobly/blob/0457a60f7be190760bf27e418f0433725f6e6526/mobly/records.py#L119)):*
>         with self._lock:
>             new_content = copy.deepcopy(content)
>             new_content['Type'] = entry_type.value
Doesn't seem like the above new_content operations needs to be protected?

Also, will help to comment the resource _lock is protecting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/376#-:-L5HiquGBJrv9l1ifs4W:b1dwf3b)*

**Comment by k2fong** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/records.py, line 119 at r1](https://beta.reviewable.io/reviews/google/mobly/376#-L5HiMccS3LdEkS133rx:-L9NqePDDahqqEeavyJ3:b-ldr67k) ([raw file](https://github.com/google/mobly/blob/0457a60f7be190760bf27e418f0433725f6e6526/mobly/records.py#L119)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Before this change, only Mobly itself triggers this operation.
Now this dump operation can be triggered by users by adding extra info blocks, hence the lock.
We've found concurrent writes to the save file can cause corruption.
</blockquote></details>

I was just referring to the two new_content operations.  I don't believe those needs to be protected.  Just trying to reduce the critical session as much as possible.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/376)*

**Comment by k2fong** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/376#-:-L9O06sN1yGxtdt8f7Ks:bnfp4nl)*

**Comment by matty3** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 338 at r3](https://beta.reviewable.io/reviews/google/mobly/376#-L9Rhv786hRbGfTmt5bh:-L9Rhv79ATBF3wCt090L:bw52ev4) ([raw file](https://github.com/google/mobly/blob/3238af83ad596a06544aff8d79b85bd8ba1d29fe/mobly/base_test.py#L338)):*
> ```Python
>             tr_record.add_error(func.__name__, e)
> 
>     def record_data(self, content):
> ```

Is content associated to any particular test case/test class? If the user creates a test that pumps out a lot of this kind of data, it would be helpful to group them somehow.

---

*[tests/mobly/base_test_test.py, line 1654 at r3](https://beta.reviewable.io/reviews/google/mobly/376#-L9RiqAcAWaJz6Xzy5NQ:-L9RiqAcAWaJz6Xzy5NR:bok6rge) ([raw file](https://github.com/google/mobly/blob/3238af83ad596a06544aff8d79b85bd8ba1d29fe/tests/mobly/base_test_test.py#L1654)):*
> ```Python
>                     continue
>                 hit = True
>                 self.assertEqual(c['a'], content['a'])
> ```

Let's add a check to make sure timestamp exists.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/376)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[mobly/base_test.py, line 338 at r3](https://beta.reviewable.io/reviews/google/mobly/376#-L9Rhv786hRbGfTmt5bh:-L9RjO4JD3fIHw_n48e-:b-7zc6yh) ([raw file](https://github.com/google/mobly/blob/3238af83ad596a06544aff8d79b85bd8ba1d29fe/mobly/base_test.py#L338)):*
<details><summary><i>Previously, matty3 (Matthew) wrote…</i></summary><blockquote>

Is content associated to any particular test case/test class? If the user creates a test that pumps out a lot of this kind of data, it would be helpful to group them somehow.
</blockquote></details>

It is not.
This can be used to dump anything. users can choose to add info about test or class if they want to.

---

*[mobly/records.py, line 119 at r1](https://beta.reviewable.io/reviews/google/mobly/376#-L5HiMccS3LdEkS133rx:-L9RjcWn6DIjicxpbFCq:b-896fix) ([raw file](https://github.com/google/mobly/blob/0457a60f7be190760bf27e418f0433725f6e6526/mobly/records.py#L119)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

I was just referring to the two new_content operations.  I don't believe those needs to be protected.  Just trying to reduce the critical session as much as possible.
</blockquote></details>

Done.

---

*[tests/mobly/base_test_test.py, line 1654 at r3](https://beta.reviewable.io/reviews/google/mobly/376#-L9RiqAcAWaJz6Xzy5NQ:-L9Rk3i_3QbSR9UBnO9z:b-c02bh4) ([raw file](https://github.com/google/mobly/blob/3238af83ad596a06544aff8d79b85bd8ba1d29fe/tests/mobly/base_test_test.py#L1654)):*
<details><summary><i>Previously, matty3 (Matthew) wrote…</i></summary><blockquote>

Let's add a check to make sure timestamp exists.
</blockquote></details>

What timestamp? no timestamp exists in the first place

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/376)*

**Comment by matty3** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/mobly/base_test_test.py, line 1654 at r3](https://beta.reviewable.io/reviews/google/mobly/376#-L9RiqAcAWaJz6Xzy5NQ:-L9RkpcZ9UpzfmVyntxB:b-59floy) ([raw file](https://github.com/google/mobly/blob/3238af83ad596a06544aff8d79b85bd8ba1d29fe/tests/mobly/base_test_test.py#L1654)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

What timestamp? no timestamp exists in the first place
</blockquote></details>

It's not. But in base_test.py#record_data() you include logic that checks it's existence. And if not, then it adds it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/376)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/mobly/base_test_test.py, line 1654 at r3](https://beta.reviewable.io/reviews/google/mobly/376#-L9RiqAcAWaJz6Xzy5NQ:-L9Rm5G_4UfFmn4Otmhb:b-4kjy75) ([raw file](https://github.com/google/mobly/blob/3238af83ad596a06544aff8d79b85bd8ba1d29fe/tests/mobly/base_test_test.py#L1654)):*
<details><summary><i>Previously, matty3 (Matthew) wrote…</i></summary><blockquote>

It's not. But in base_test.py#record_data() you include logic that checks it's existence. And if not, then it adds it.
</blockquote></details>

Ah i totally forgot about that....
Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/376)*

**Comment by matty3** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/376#-:-L9RtyV466XxaOQV5MPi:bnfp4nl)*

**Pull request merged**
