### PR TITLE
Fix some documentation style issue to get rid of sphinx warning

### PR DESCRIPTION
**Pull request by ygw11223**
This is to remove warnings and errors in #119

Added napoleon, which contains parser for Google doc style, to extensions in conf.py . This should solve a large number of errors. Also made other changes such as adding error type under raises, code blocks, blank lines to avoid error from sphinx.

Now there should be 0 error or warning when generating docs through sphinx

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/339)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[mobly/base_test.py, line 129 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQPtgtgMH6gSJ2SZlM:-KvQPtgtgMH6gSJ2SZlN:b-jlv4ax) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/base_test.py#L129)):*
> ```Python
> 
>         Raises:
>             Error: It is raised if a required user params is not provided.
> ```

Remove "It is raised if", here and all other places

---

*[mobly/base_test.py, line 471 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQ3WO4QbfITKHZW8K:-KvQQ3WO4QbfITKHZW8L:b-1hv8vr) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/base_test.py#L471)):*
> ```Python
>         """Gets the names of existing tests in the class.
> 
>         A method in the class is considered a test if its name is
> ```

if its name starts with `test_`

---

*[mobly/test_runner.py, line 198 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQDJt--JsiEGjxu42:-KvQQDJt--JsiEGjxu43:bifjs15) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/test_runner.py#L198)):*
> ```Python
>             ID, version, or anything that could be useful for describing the
>             test bed and debugging.
>             
> ```

what's this

---

*[mobly/test_runner.py, line 393 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQLnO8g50_j4oK6ef:-KvQQLnO8g50_j4oK6eg:bkp7xdl) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/test_runner.py#L393)):*
> ```Python
> 
>         Raises:
>             ControllerError: It is raised if no corresponding config can
> ```

If `required` is True, it's raised when...
Otherwise, it's raised when...

---

*[mobly/controllers/android_device.py, line 507 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQgJ9kw4Lp9PqcDtT:-KvQQgJAWlJvJkJxhffh:b-guhkp) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device.py#L507)):*
> ```Python
>         method:
> 
>         - Power measurement: Using Monsoon device to measure battery consumption
> ```

is there a standard way to mark "List"?

---

*[mobly/controllers/android_device.py, line 1019 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQlQ8S-5W4_ppmsXd:-KvQQlQ8S-5W4_ppmsXe:b354p86) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device.py#L1019)):*
> ```Python
> 
>     Usage:
>     
> ```

what's this?

---

*[mobly/controllers/android_device_lib/event_dispatcher.py, line 263 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQvAczIc3v_TDCszj:-KvQQvAczIc3v_TDCszk:b-wrc04y) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device_lib/event_dispatcher.py#L263)):*
> ```Python
> 
>         Returns:
>             Pop events whose names match a regex pattern.
> ```

Remove "Pop"

---

*[mobly/controllers/android_device_lib/event_dispatcher.py, line 312 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQR2pwX2eefsnfaUZe:-KvQR2pwX2eefsnfaUZf:bujset3) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device_lib/event_dispatcher.py#L312)):*
> ```Python
>             A queue storing all the events of the specified name.
>             None if timed out.
>             Number of seconds to wait for the operation.
> ```

this sentence seems out of place

---

*[mobly/controllers/android_device_lib/fastboot.py, line 31 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQR9uPn2Ob5xIX5K7C:-KvQR9uPn2Ob5xIX5K7D:b-z1bntw) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device_lib/fastboot.py#L31)):*
> ```Python
> 
>     Raises:
>         Exception: It is raised if an error occurred during the command execution.
> ```

over 80 chars

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by ygw11223** [comment]
Review status: 0 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[mobly/base_test.py, line 129 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQPtgtgMH6gSJ2SZlM:-KvQh313yUjgD9dYfM_k:b-896fix) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/base_test.py#L129)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Remove "It is raised if", here and all other places
</blockquote></details>

Done.

---

*[mobly/base_test.py, line 471 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQ3WO4QbfITKHZW8K:-KvQh8FfT8AV_eHlPg79:b-k6nyg5) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/base_test.py#L471)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

if its name starts with `test_`
</blockquote></details>

Added * to avoid error.

---

*[mobly/test_runner.py, line 198 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQDJt--JsiEGjxu42:-KvQhGdRwEsAJbe6lLFu:bhofej8) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/test_runner.py#L198)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what's this
</blockquote></details>

Deleted

---

*[mobly/test_runner.py, line 393 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQLnO8g50_j4oK6ef:-KvQhKc3fiHEFKWTRLKH:b3216qa) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/test_runner.py#L393)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

If `required` is True, it's raised when...
Otherwise, it's raised when...
</blockquote></details>

Made to a list.

---

*[mobly/controllers/android_device.py, line 507 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQgJ9kw4Lp9PqcDtT:-KvQhOcGOPmGRA2wAfLZ:b-tje0xf) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device.py#L507)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

is there a standard way to mark "List"?
</blockquote></details>

Using * to make a list.

---

*[mobly/controllers/android_device.py, line 1019 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQlQ8S-5W4_ppmsXd:-KvQhUolEjnrNFpy-1ey:bhofej8) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device.py#L1019)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

Deleted

---

*[mobly/controllers/android_device_lib/event_dispatcher.py, line 263 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQQvAczIc3v_TDCszj:-KvQhZLiqd17B8RaBg1E:b-896fix) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device_lib/event_dispatcher.py#L263)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Remove "Pop"
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/event_dispatcher.py, line 312 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQR2pwX2eefsnfaUZe:-KvQhaApJ8pX1HLhmrC4:bss4a2b) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device_lib/event_dispatcher.py#L312)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this sentence seems out of place
</blockquote></details>

Removed.

---

*[mobly/controllers/android_device_lib/fastboot.py, line 31 at r1](https://reviewable.io:443/reviews/google/mobly/339#-KvQR9uPn2Ob5xIX5K7C:-KvQhccIoUTq_uIuHm21:b-896fix) ([raw file](https://github.com/google/mobly/blob/782478833f5fefb253e163d324f4ed528294f39d/mobly/controllers/android_device_lib/fastboot.py#L31)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

over 80 chars
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by xpconanfan** [comment]
Review status: 0 of 17 files reviewed at latest revision, 10 unresolved discussions.

---

*[mobly/asserts.py, line 173 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQvoYkX5nMxo8Tgbg1:-KvQvoYkX5nMxo8Tgbg2:b-g4hogr) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/asserts.py#L173)):*
> ```Python
>     Raises:
>         signals.TestAbortClass: Abort all subsequent tests in a
>             test class.
> ```

looks like this line can be merged to the previous line?
Let's reduce the number of lines when possible at all places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by xpconanfan** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[mobly/base_test.py, line 499 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQw3bzsxA9Y91GLZux:-KvQw3bzsxA9Y91GLZuy:b-web8nt) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/base_test.py#L499)):*
> ```Python
>         Raises:
>             Error: The test name does not follow naming convention 'test_*'.
>                 This can only be caused by user input here.
> ```

Remove "here"

---

*[mobly/controllers/android_device.py, line 320 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQwDb_IYKR62t02chl:-KvQwDb_IYKR62t02chm:bsgze01) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/controllers/android_device.py#L320)):*
> ```Python
>     Raises:
>         Error: None or more than one device is
>             matched.
> ```

merge line

---

*[mobly/controllers/android_device.py, line 669 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQwHuRCSFsreCsHIaq:-KvQwHuRCSFsreCsHIar:bsgze01) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/controllers/android_device.py#L669)):*
> ```Python
>         Raises:
>             Error: The config is trying to overwrite
>                 an existing attribute.
> ```

merge line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by ygw11223** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[mobly/asserts.py, line 173 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQvoYkX5nMxo8Tgbg1:-KvVPWEQd_ujaNWQBIVj:b-896fix) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/asserts.py#L173)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

looks like this line can be merged to the previous line?
Let's reduce the number of lines when possible at all places.
</blockquote></details>

Done.

---

*[mobly/base_test.py, line 499 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQw3bzsxA9Y91GLZux:-KvVPd5SP4r_iat7Ekpe:b-896fix) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/base_test.py#L499)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Remove "here"
</blockquote></details>

Done.

---

*[mobly/controllers/android_device.py, line 320 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQwDb_IYKR62t02chl:-KvVPfpQ-LdC4aQ9CRr7:b-896fix) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/controllers/android_device.py#L320)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

merge line
</blockquote></details>

Done.

---

*[mobly/controllers/android_device.py, line 669 at r2](https://reviewable.io:443/reviews/google/mobly/339#-KvQwHuRCSFsreCsHIaq:-KvVPgpxlcx2_uA9JXqz:b-896fix) ([raw file](https://github.com/google/mobly/blob/d1b023081bae821e317cc8c6601ed700309f0108/mobly/controllers/android_device.py#L669)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

merge line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by xpconanfan** [comment]
Review status: 0 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/controllers/sniffer.py, line 25 at r3](https://reviewable.io:443/reviews/google/mobly/339#-KvW0SqJj_3rYZEMG7Ob:-KvW0SqJj_3rYZEMG7Oc:b-8t9psb) ([raw file](https://github.com/google/mobly/blob/e811fe17653a389270b8f3de89a34a1d03d10cff/mobly/controllers/sniffer.py#L25)):*
> ```Python
>     expected keys are:
> 
>         Type: A first-level type of sniffer. Planned to be 'local' for sniffers
> ```

looks like this should be a proper list

---

*[mobly/controllers/attenuator_lib/minicircuits.py, line 86 at r3](https://reviewable.io:443/reviews/google/mobly/339#-KvW0hKN5FT2ho7Mt5lA:-KvW0hKN5FT2ho7Mt5lB:b-l0ql1k) ([raw file](https://github.com/google/mobly/blob/e811fe17653a389270b8f3de89a34a1d03d10cff/mobly/controllers/attenuator_lib/minicircuits.py#L86)):*
> ```Python
> 
>         Raises:
>             Error: The underlying telnet connection to the
> ```

fill the 80 chars of the previous line before making a new line in this group.

---

*[mobly/controllers/attenuator_lib/minicircuits.py, line 115 at r3](https://reviewable.io:443/reviews/google/mobly/339#-KvW0cqYIM0RwicS0hiv:-KvW0cqYIM0RwicS0hiw:b-k00bsy) ([raw file](https://github.com/google/mobly/blob/e811fe17653a389270b8f3de89a34a1d03d10cff/mobly/controllers/attenuator_lib/minicircuits.py#L115)):*
> ```Python
> 
>         Raises:
>             Error: The underlying telnet connection to the
> ```

fill the 80 chars of the previous line before making a new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by ygw11223** [comment]
Review status: 0 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/controllers/sniffer.py, line 25 at r3](https://reviewable.io:443/reviews/google/mobly/339#-KvW0SqJj_3rYZEMG7Ob:-KvYGiU6swgXcfL1ys-r:b-896fix) ([raw file](https://github.com/google/mobly/blob/e811fe17653a389270b8f3de89a34a1d03d10cff/mobly/controllers/sniffer.py#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

looks like this should be a proper list
</blockquote></details>

Done.

---

*[mobly/controllers/attenuator_lib/minicircuits.py, line 86 at r3](https://reviewable.io:443/reviews/google/mobly/339#-KvW0hKN5FT2ho7Mt5lA:-KvYGsy8xBZxKcd-LNwT:b-896fix) ([raw file](https://github.com/google/mobly/blob/e811fe17653a389270b8f3de89a34a1d03d10cff/mobly/controllers/attenuator_lib/minicircuits.py#L86)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

fill the 80 chars of the previous line before making a new line in this group.
</blockquote></details>

Done.

---

*[mobly/controllers/attenuator_lib/minicircuits.py, line 115 at r3](https://reviewable.io:443/reviews/google/mobly/339#-KvW0cqYIM0RwicS0hiv:-KvYGw_9GmGDAMyd-569:b-896fix) ([raw file](https://github.com/google/mobly/blob/e811fe17653a389270b8f3de89a34a1d03d10cff/mobly/controllers/attenuator_lib/minicircuits.py#L115)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

fill the 80 chars of the previous line before making a new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 17 files at r1.
Review status: 1 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/sniffer.py, line 187 at r4](https://reviewable.io:443/reviews/google/mobly/339#-KvYJyDfi3v7qYBVjnjE:-KvYJyDfi3v7qYBVjnjF:b-94tcid) ([raw file](https://github.com/google/mobly/blob/0e7eacdc97a48bfebe097551483e3c34539476c9/mobly/controllers/sniffer.py#L187)):*
> ```Python
> 
>             * Explicitly: call either stop_capture() or wait_for_capture()
> ```

don't need this empty line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by ygw11223** [comment]
Review status: 1 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/sniffer.py, line 187 at r4](https://reviewable.io:443/reviews/google/mobly/339#-KvYJyDfi3v7qYBVjnjE:-Kv_pJ4kV_jRitxaKdn_:b-896fix) ([raw file](https://github.com/google/mobly/blob/0e7eacdc97a48bfebe097551483e3c34539476c9/mobly/controllers/sniffer.py#L187)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

don't need this empty line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 4 of 17 files at r1, 7 of 11 files at r2, 3 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/339#-:-Kva9PIYLCRyB0DoCvdY:bnfp4nl)*

**Pull request merged**
