### PR TITLE
Add a tutorial example for new generated tests.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/207)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/tutorial.md, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/207#-KjyljbFlEW86VT9rGY8:-KjyljbGkN8mIx-kscqR:bywi2vl) ([raw file](https://github.com/google/mobly/blob/02b739ffb4f7c6047fb101ee07fa03d9486252ca/docs/tutorial.md#L321)):*
> ```Markdown
> 
>  
> **many_greetings_test.py**
> ```

Can you add comments to this explaining what the test is doing and what people should look at? It's hard to understand a big code dump like this. The only explanatory comment seems to be about min_num which is not really relevant here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/207)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/tutorial.md, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/207#-KjyljbFlEW86VT9rGY8:-KjywlVVkYt9o1JiTUP0:b-gv0nww) ([raw file](https://github.com/google/mobly/blob/02b739ffb4f7c6047fb101ee07fa03d9486252ca/docs/tutorial.md#L321)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can you add comments to this explaining what the test is doing and what people should look at? It's hard to understand a big code dump like this. The only explanatory comment seems to be about min_num which is not really relevant here.
</blockquote></details>

The paragraphs before this code explains what the test does.
What else would you like to see?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/207)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/tutorial.md, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/207#-KjyljbFlEW86VT9rGY8:-KjzeyMo4rGYV4UH7kS6:bem3nbq) ([raw file](https://github.com/google/mobly/blob/02b739ffb4f7c6047fb101ee07fa03d9486252ca/docs/tutorial.md#L321)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

The paragraphs before this code explains what the test does.
What else would you like to see?
</blockquote></details>

I would like to see comments in the code to the effect of:
- setup_generated_tests is a method invoked by the framework before setup_class; its purpose is to invoke generate_tests
- generate_tests generates testcases for each argument that was passed in. It may only be called from setup_generated_tests.
- You can load controllers before calling self.generate_tests here if needed, but most tests shouldn't need to access controllers.
- The name func will be called with the same arguments as your test logic func. Its return value will be the name of the testcase.
- You can select a generated test for execution by passing the --test_case arg: example
- This test makes a toast on the device with one of the greetings from the messages list. Each greeting gets its own testcase.

I want to add comments that make it a user-friendly explanatory tutorial rather than a code dump.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/207)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/tutorial.md, line 321 at r1](https://reviewable.io:443/reviews/google/mobly/207#-KjyljbFlEW86VT9rGY8:-Kk-9TIuA1I4o_z_6hVt:b-g13b4j) ([raw file](https://github.com/google/mobly/blob/02b739ffb4f7c6047fb101ee07fa03d9486252ca/docs/tutorial.md#L321)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I would like to see comments in the code to the effect of:
- setup_generated_tests is a method invoked by the framework before setup_class; its purpose is to invoke generate_tests
- generate_tests generates testcases for each argument that was passed in. It may only be called from setup_generated_tests.
- You can load controllers before calling self.generate_tests here if needed, but most tests shouldn't need to access controllers.
- The name func will be called with the same arguments as your test logic func. Its return value will be the name of the testcase.
- You can select a generated test for execution by passing the --test_case arg: example
- This test makes a toast on the device with one of the greetings from the messages list. Each greeting gets its own testcase.

I want to add comments that make it a user-friendly explanatory tutorial rather than a code dump.


</blockquote></details>

While it's good to have these info, I'd rather not repeat the same info already covered by the doc strings of `setup_generated_tests` and `generate_tests`. Could we link to the doc string or is there a better way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/207)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/207#-:-KkIkXXcClc0yffHgKPz:bnfp4nl)*

**Pull request merged**
