### PR TITLE
Fix the issue where ad.ed is None after load_sl4a()

### PR DESCRIPTION
**Pull request by l-meng**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/235)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 78 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nWbSZ65LXQhvnTXP:-Kn1nWbSZ65LXQhvnTXQ:b89t297) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L78)):*
> ```Python
>         # Retry connect and also start event client
>         self._retry_connect()
>         self.ed = self._start_event_client()
> ```

Any way we can reuse the same code between this and restore_app_connection?

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn1nRh1EgKxxlPLyMpR:b-xo23s6) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
> ```Python
>             self._retry_connect()
>         except:
>             # Failed to connect to app (could because of reboot), restart app.
> ```

The comment says 'restart app' but I don't see any code which would actually restart it, just stopping it, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by l-meng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 78 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nWbSZ65LXQhvnTXP:-Kn1pAM6yyd_3cnaY_oL:bip92x0) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L78)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Any way we can reuse the same code between this and restore_app_connection?
</blockquote></details>

Handle connect and reconnect is different in the way that:
for connect: stop app, try connect and if fails (no exception), restarts the app
for re-connect: try connect and if it fails, raise exception.

I think they already shared the code on the level of retry_connect

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn1pcHg7UnJ_FMB4bx5:b-896fix) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

The comment says 'restart app' but I don't see any code which would actually restart it, just stopping it, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn1pXRhW08cZBHhZ3Sb:bfas3d9) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think the new comment is accurate; if `stop_app succeeds` (which it usually will since it's just a stop call), this will not raise an exception but continue to `start_event_client` afaics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by l-meng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn1qLOM36q9TgyzJcAw:b-896fix) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I don't think the new comment is accurate; if `stop_app succeeds` (which it usually will since it's just a stop call), this will not raise an exception but continue to `start_event_client` afaics.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn1qzUZ_PROn5ieAr8o:b-dwgsqm) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like we're wrapping one AppRestoreConnectionError in another with a slightly different message? Can we move this message into retry_connect() and delete the wrapper?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by l-meng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn1vsX1Q0-mj4zQeDcW:b58zt4v) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Looks like we're wrapping one AppRestoreConnectionError in another with a slightly different message? Can we move this message into retry_connect() and delete the wrapper?
</blockquote></details>

Now these two functions have 2 lines of code the same/
Not sure worth to make it a common call?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn1xRgE3PcCRRc1I1vE:b-xeg6x9) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

Now these two functions have 2 lines of code the same/
Not sure worth to make it a common call?
</blockquote></details>

If you mean whether we should stick `self._start_event_client()` into `retry_connect`, feel free. Makes sense but no strong preference on my side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 78 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nWbSZ65LXQhvnTXP:-Kn5OjxeL1_PgB5OsLAT:b6q8w2j) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L78)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

Handle connect and reconnect is different in the way that:
for connect: stop app, try connect and if fails (no exception), restarts the app
for re-connect: try connect and if it fails, raise exception.

I think they already shared the code on the level of retry_connect



</blockquote></details>

This no longer seems to be the case below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by l-meng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 78 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nWbSZ65LXQhvnTXP:-Kn5d4i7-hqmYGGw1UzJ:b-ofzpwk) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L78)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

This no longer seems to be the case below?
</blockquote></details>

Fixed according to discussion with David

---

*[mobly/controllers/android_device_lib/sl4a_client.py, line 100 at r1](https://reviewable.io:443/reviews/google/mobly/235#-Kn1nRh1EgKxxlPLyMpQ:-Kn5d9KEmcrR5mLFclek:b-896fix) ([raw file](https://github.com/google/mobly/blob/c5ca86a7b28518ebd9a0b77a3bb012d9641ac311/mobly/controllers/android_device_lib/sl4a_client.py#L100)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

If you mean whether we should stick `self._start_event_client()` into `retry_connect`, feel free. Makes sense but no strong preference on my side.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by dthkao** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 145 at r2](https://reviewable.io:443/reviews/google/mobly/235#-Kn5hCbWsrLSXFxkLkKn:-Kn5hCbWsrLSXFxkLkKo:b1u3qyz) ([raw file](https://github.com/google/mobly/blob/8d0874c477dee3c32a8ba933e1120bb4b2b96593/mobly/controllers/android_device_lib/snippet_client.py#L145)):*
> ```Python
>             AppRestoreConnectionError: When the app was not able to be started.
>         """
>         self.host_port = port or utils.get_available_host_port()
> ```

Should we be removing this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by l-meng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 145 at r2](https://reviewable.io:443/reviews/google/mobly/235#-Kn5hCbWsrLSXFxkLkKn:-Kn5hcdrncFJOkzfvyaF:bb6un1j) ([raw file](https://github.com/google/mobly/blob/8d0874c477dee3c32a8ba933e1120bb4b2b96593/mobly/controllers/android_device_lib/snippet_client.py#L145)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Should we be removing this? 
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/235#-:-Kn6fZDSo1lXzA425vm5:bnfp4nl)*

**Pull request merged**
