### PR TITLE
Add a --verbose argument to the test_runner to set DEBUG logging level

### PR DESCRIPTION
**Pull request by DeltaEvo**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/840)

### CODE REVIEW

**Review by xpconanfan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/840)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @DeltaEvo and @xpconanfan)

___
*[`mobly/logger.py` line 178 at r1](https://reviewable.io/reviews/google/mobly/840#-N6XHLWH6XmSUUGWHV9S:-N6XHLWH6XmSUUGWHV9T:bj5lyfh) ([raw file](https://github.com/google/mobly/blob/70bed018a48494a9e9636eef3ba2bf9c64af7d8f/mobly/logger.py#L178)):*
> ```Python
>   level to files.
> 
>   Args:
> ```

update the docstring section
___
*[`mobly/logger.py` line 254 at r1](https://reviewable.io/reviews/google/mobly/840#-N6XHHVM7su-XXLBXAYA:-N6XHHVM7su-XXLBXAYB:bj5lyfh) ([raw file](https://github.com/google/mobly/blob/70bed018a48494a9e9636eef3ba2bf9c64af7d8f/mobly/logger.py#L254)):*
> ```Python
>     specific to a test class.
> 
>   Args:
> ```

update the docstring section
___
*[`mobly/test_runner.py` line 302 at r1](https://reviewable.io/reviews/google/mobly/840#-N6XGwXDDrx1vo_dPI70:-N6XGwXDDrx1vo_dPI71:b-x3m3pz) ([raw file](https://github.com/google/mobly/blob/70bed018a48494a9e9636eef3ba2bf9c64af7d8f/mobly/test_runner.py#L302)):*
> ```Python
> 
>     Args:
>       alias: optional string, the name of the latest log alias directory to
> ```

update the docstring with the new arg.

**Review by DeltaEvo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/840)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @xpconanfan)

___
*[`mobly/logger.py` line 178 at r1](https://reviewable.io/reviews/google/mobly/840#-N6XHLWH6XmSUUGWHV9S:-N6h8gbQ50dEaZw8ALee:b-896fix) ([raw file](https://github.com/google/mobly/blob/70bed018a48494a9e9636eef3ba2bf9c64af7d8f/mobly/logger.py#L178)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

update the docstring section
</blockquote></details>

Done.
___
*[`mobly/logger.py` line 254 at r1](https://reviewable.io/reviews/google/mobly/840#-N6XHHVM7su-XXLBXAYA:-N6h8h9p0EaqBYlbE0xx:b-896fix) ([raw file](https://github.com/google/mobly/blob/70bed018a48494a9e9636eef3ba2bf9c64af7d8f/mobly/logger.py#L254)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

update the docstring section
</blockquote></details>

Done.
___
*[`mobly/test_runner.py` line 302 at r1](https://reviewable.io/reviews/google/mobly/840#-N6XGwXDDrx1vo_dPI70:-N6h8hmvCmP9egsAI3cN:b-896fix) ([raw file](https://github.com/google/mobly/blob/70bed018a48494a9e9636eef3ba2bf9c64af7d8f/mobly/test_runner.py#L302)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

update the docstring with the new arg.
</blockquote></details>

Done.

**Review by xpconanfan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/840)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DeltaEvo and @xpconanfan)

___
*[`mobly/logger.py` line 180 at r2](https://reviewable.io/reviews/google/mobly/840#-N6lJr-y6K3wqHdyDoIZ:-N6lJr-y6K3wqHdyDoI_:b7bi40f) ([raw file](https://github.com/google/mobly/blob/27b02d2eca2dd9ad4854b6e0769b8e33ff9907fc/mobly/logger.py#L180)):*
> ```Python
>   Args:
>     log_path: Location of the log file.
>     console_level: Log level threshold used for log messages printed
> ```

clarify the valid values for this arg? same for the others
___
*[`mobly/logger.py` line 264 at r2](https://reviewable.io/reviews/google/mobly/840#-N6lK3vA1Il6Stz7q9RA:-N6lK3vA1Il6Stz7q9RB:b-v6njn2) ([raw file](https://github.com/google/mobly/blob/27b02d2eca2dd9ad4854b6e0769b8e33ff9907fc/mobly/logger.py#L264)):*
> ```Python
>       storage system (e.g. ZIP files) does not properly support
>       shortcut/symlinks.
>     console_level: optional number, log level threshold used for log
> ```

We expect this to be specific enum values under the `logging` module right?
So "number" is not accurate.
___
*[`mobly/logger.py` line 264 at r2](https://reviewable.io/reviews/google/mobly/840#-N6lKV129d7zXppkfBiQ:-N6lKV129d7zXppkfBiR:b-s56gse) ([raw file](https://github.com/google/mobly/blob/27b02d2eca2dd9ad4854b6e0769b8e33ff9907fc/mobly/logger.py#L264)):*
> ```Python
>       storage system (e.g. ZIP files) does not properly support
>       shortcut/symlinks.
>     console_level: optional number, log level threshold used for log
> ```

"threshold" -> "level"?



_Code quote:_
```Python
threshold
```

**Review by DeltaEvo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/840)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DeltaEvo and @xpconanfan)

___
*[`mobly/logger.py` line 264 at r2](https://reviewable.io/reviews/google/mobly/840#-N6lKV129d7zXppkfBiQ:-N6lNnBqDHtsxdCrMCtC:bnsld36) ([raw file](https://github.com/google/mobly/blob/27b02d2eca2dd9ad4854b6e0769b8e33ff9907fc/mobly/logger.py#L264)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"threshold" -> "level"?
</blockquote></details>

The "level" is already mentioned in this comment, do you want me to put "log level level used for a log" or to remove threshold ?
___
*[`mobly/logger.py` line 264 at r2](https://reviewable.io/reviews/google/mobly/840#-N6lK3vA1Il6Stz7q9RA:-N6lNzay8mosylzve7he:b-kj8oc3) ([raw file](https://github.com/google/mobly/blob/27b02d2eca2dd9ad4854b6e0769b8e33ff9907fc/mobly/logger.py#L264)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

We expect this to be specific enum values under the `logging` module right?
So "number" is not accurate.
</blockquote></details>

What do you think I should put here then as the values under the `logging` module are numbers ?

**Review by xpconanfan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/840)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @DeltaEvo and @xpconanfan)

___
*[`mobly/test_runner.py` line 305 at r2](https://reviewable.io/reviews/google/mobly/840#-N78YOVV9Ql4Wtc1ho0y:-N78YOVV9Ql4Wtc1ho0z:b1pe30h) ([raw file](https://github.com/google/mobly/blob/27b02d2eca2dd9ad4854b6e0769b8e33ff9907fc/mobly/test_runner.py#L305)):*
> ```Python
>         create. If a falsy value is specified, then the directory will not
>         be created.
>       console_level: optional number, log level threshold used for log
> ```

“number” is a little abstract.
Would it make more sense to refer to the `logging` levels instead of "number"?

**Review by DeltaEvo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/840)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @DeltaEvo and @xpconanfan)

___
*[`mobly/test_runner.py` line 305 at r2](https://reviewable.io/reviews/google/mobly/840#-N78YOVV9Ql4Wtc1ho0y:-N7pkqqj3S6xCpqT4n91:b-896fix) ([raw file](https://github.com/google/mobly/blob/27b02d2eca2dd9ad4854b6e0769b8e33ff9907fc/mobly/test_runner.py#L305)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

“number” is a little abstract.
Would it make more sense to refer to the `logging` levels instead of "number"?
</blockquote></details>

Done.

**Review by xpconanfan — APPROVED** [review]

**Pull request merged**
