### PR TITLE
Adding mobly to rtd_requirements.txt

### PR DESCRIPTION
**Pull request by yusufm**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/127)

### CODE REVIEW

**Comment by adorokhine** [comment]
- Is there a way to test this prior to submission to make sure we've got everything?
- Won't this cause pip to install the latest release of mobly instead of what we're actually testing?

**Comment by xpconanfan** [comment]
regarding 2: do we want to pull docs from HEAD?
perhaps it's better to version the docs with releases, like flask does.

**Comment by adorokhine** [comment]
Our tutorials all render at HEAD right? So what the user would see when following the tutorial wouldn't match what the user saw in the api docs right?

**Comment by xpconanfan** [comment]
Tutorials change much less frequently than API docs and requires much less update than API docs.
I think this is why readthedocs actually indexes md files as well, so they can be versioned, now it makes sense...
Perhaps it's better to point users to readthedocs by default so everything is versioned...

**Comment by adorokhine** [comment]
You mean you can get to docs/tutorial.md on readthedocs.org, and it points to the latest release? If so, sgtm, can we add a link to that on the readme?

**Comment by xpconanfan** [comment]
Yes, we can have readthedocs grab md files per release.
Will add after it's ready. Yusuf would need to make some changes to include them.

**Pull request merged**
