### PR TITLE
Install package 'absl-py' for testing

### PR DESCRIPTION
**Pull request by syaoranx**
To execute pytest with named_parameters, need absl-py install first.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/685)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Why do we need `absl`?

**Comment by syaoranx** [comment]
> Why do we need `absl`?

To implement this [comment](https://github.com/google/mobly/pull/683#discussion_r509017718) with named_parameters for the same uni test.

Build fails [here](https://travis-ci.org/github/google/mobly/jobs/739527507) without absl.

**Review by xpconanfan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/685)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @syaoranx)

___
*[setup.py, line 22 at r1](https://reviewable.io/reviews/google/mobly/685#-MKiAUWV1Nrk74F29U4-:-MKiAUWV1Nrk74F29U40:b7elypi) ([raw file](https://github.com/google/mobly/blob/5f1ba38ba112f6106555b7f6ee6f88ed87ddb6d0/setup.py#L22)):*
> ```Python
> install_requires = [
>     'future', 'portpicker', 'psutil>=5.4.4', 'pyserial', 'pyyaml',
>     'timeout_decorator', 'absl-py'
> ```

You should use the parameterized test in `pytest` lib which we already depend on.

For future ref, test-only deps should be added to `tests_require`, not here.

**Comment by xpconanfan** [comment]
Discussed offline, this is not needed at the moment.

**Pull request closed without merging**
