### PR TITLE
Support the use of usb id as device identifier for AndroidDevice.

### PR DESCRIPTION
**Pull request by xpconanfan**
This is needed because for devices that use the fake serial "ABCDEF012345678", users may use the usb id as the identifier instead of the serial.

This change is [Reviewable](https://reviewable.io/reviews/google/mobly/204)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 92 at r1](https://reviewable.io:443/reviews/google/mobly/204#-Kjl_qU_P6IKiJPeSbOn:-Kjl_qU_P6IKiJPeSbOo:b-9wrmvk) ([raw file](https://github.com/google/mobly/blob/83ed47a7c308db278c734a70d29215c022f8b4e8/mobly/controllers/android_device.py#L92)):*
> ```Python
>     else:
>         raise Error("No valid config found in: %s" % configs)
>     valid_ad_identifiers = list_adb_devices() + list_adb_devices_by_usb_id()
> ```

Just to confirm, `adb -s <usb id> logcat` will work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 92 at r1](https://reviewable.io:443/reviews/google/mobly/204#-Kjl_qU_P6IKiJPeSbOn:-KjnOBUl85fcbCyILEdp:bh2mjdb) ([raw file](https://github.com/google/mobly/blob/83ed47a7c308db278c734a70d29215c022f8b4e8/mobly/controllers/android_device.py#L92)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Just to confirm, `adb -s <usb id> logcat` will work?
</blockquote></details>

Yes, "usb:x.x.x-x" is equivalent to serial for `-s`.
I implemented a similar change in MH a while back ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 92 at r1](https://reviewable.io:443/reviews/google/mobly/204#-Kjl_qU_P6IKiJPeSbOn:-Kjsd0CMcXALo-Kyj_eT:bh5tal9) ([raw file](https://github.com/google/mobly/blob/83ed47a7c308db278c734a70d29215c022f8b4e8/mobly/controllers/android_device.py#L92)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Yes, "usb:x.x.x-x" is equivalent to serial for `-s`.
I implemented a similar change in MH a while back ;)
</blockquote></details>

Is this confirmed for older versions of adb as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 92 at r1](https://reviewable.io:443/reviews/google/mobly/204#-Kjl_qU_P6IKiJPeSbOn:-KjsdJ5a5OP-UBMLqjjU:b-gf7v0x) ([raw file](https://github.com/google/mobly/blob/83ed47a7c308db278c734a70d29215c022f8b4e8/mobly/controllers/android_device.py#L92)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Is this confirmed for older versions of adb as well?
</blockquote></details>

What old version are you referring to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 92 at r1](https://reviewable.io:443/reviews/google/mobly/204#-Kjl_qU_P6IKiJPeSbOn:-KjsjK8V89Wyfh5OWMrC:b74sp1b) ([raw file](https://github.com/google/mobly/blob/83ed47a7c308db278c734a70d29215c022f8b4e8/mobly/controllers/android_device.py#L92)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

What old version are you referring to?
</blockquote></details>

This works with Android devices with low versions like KK if that's what you mean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 92 at r1](https://reviewable.io:443/reviews/google/mobly/204#-Kjl_qU_P6IKiJPeSbOn:-KjsmZRRvRoUfHqDYYMD:b-394cft) ([raw file](https://github.com/google/mobly/blob/83ed47a7c308db278c734a70d29215c022f8b4e8/mobly/controllers/android_device.py#L92)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This works with Android devices with low versions like KK if that's what you mean.
</blockquote></details>

I'm not sure where the cutoff should be drawn but if it works on adb 1.0.31 (public ubuntu Trusty repo ships this), sgtm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 92 at r1](https://reviewable.io:443/reviews/google/mobly/204#-Kjl_qU_P6IKiJPeSbOn:-Kjsnd_gEYtEKB3bhSz3:bvtpx5f) ([raw file](https://github.com/google/mobly/blob/83ed47a7c308db278c734a70d29215c022f8b4e8/mobly/controllers/android_device.py#L92)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I'm not sure where the cutoff should be drawn but if it works on adb 1.0.31 (public ubuntu Trusty repo ships this), sgtm.
</blockquote></details>

Looking at the adb doc, the `-s` option has been there for a while.
And Mobly's system requirement lists adb 1.0.36+, so I think we are good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204)*

**Comment by dthkao** [comment]
Aha, did not realize we had that requirement. Sound good.

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/204#-:-KjtZ4_f6tH7VGpc2X53:bnfp4nl)*

**Pull request merged**
