### PR TITLE
Add an API to unload a single snippet.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/463)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @xpconanfan, @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LF4YluiBwamyzcVyrJa:bf47d4h) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

> ```
> stop_app
> ```

Do we care if this raises an error?
</blockquote></details>

Hmm, what do you mean by "care"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom, @dthkao, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LF4fUgL6Wj50qX3WDZv:b-a67lrm) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, what do you mean by "care"?
</blockquote></details>

Specifically, load_snippet has error handling logic, but this doesn't really.

So is it okay for DeviceError to just get thrown here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @xpconanfan, @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LF4mWOM-hcdcNhk60nv:b49i59d) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Specifically, load_snippet has error handling logic, but this doesn't really.

So is it okay for DeviceError to just get thrown here?
</blockquote></details>

load handles that error bc load tries to start something, so if that thing is half started, we make an attempt to kill it so there is no leak.
But this one is trying to kill something, so that logic doesn't really apply here

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom, @dthkao, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LF4t-xo6a7DYc5QdsiY:b8itfej) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

load handles that error bc load tries to start something, so if that thing is half started, we make an attempt to kill it so there is no leak.
But this one is trying to kill something, so that logic doesn't really apply here
</blockquote></details>

So if it kills something that is already dead, then won't this raise an error and not delete the attribute?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom, @dthkao, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LF4tLH33AlilRmuKdfh:b-v9eczm) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

So if it kills something that is already dead, then won't this raise an error and not delete the attribute?
</blockquote></details>

Yeah, that is the case.

The reasoning is, if we remove the attr first and stop_app fails, we won't be able to call unload properly again...

So I'm thinking we only want to remove when stop_app does not raise?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LFJGyrl336m4XFRCvgT:b-r3tjg7) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Yeah, that is the case.

The reasoning is, if we remove the attr first and stop_app fails, we won't be able to call unload properly again...

So I'm thinking we only want to remove when stop_app does not raise?
</blockquote></details>

wait, if this errors if the snippet isn't running via a crash or something, then doesn't that mean you can't actually unload it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LF4u2t44ESw3u3WkNfM:bjggx13) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

wait, if this errors if the snippet isn't running via a crash or something, then doesn't that mean you can't actually unload it?
</blockquote></details>

yeah, there is no great option here...

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LFJP-T31n98XTmsEMxW:bdanwgk) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

yeah, there is no great option here...
</blockquote></details>

You could specify an ignore errors flag which defaults to false?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LFJXPfV95cPtApQh4Ry:b4g2kqc) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

You could specify an ignore errors flag which defaults to false?
</blockquote></details>

That's a bit too much usage overhead for a simple unload...
I guess the lesser of two evil is to always remove the attr. If `stop_app` throws, then there's no point in attempting the call again?
If the snippet has already died at this point, then it's good to raise an error notifying users that the snippet exited unexpectedly, even if it's an extra error

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LFOilVj-QPmIPYtS7LD:b-kcvpqf) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

That's a bit too much usage overhead for a simple unload...
I guess the lesser of two evil is to always remove the attr. If `stop_app` throws, then there's no point in attempting the call again?
If the snippet has already died at this point, then it's good to raise an error notifying users that the snippet exited unexpectedly, even if it's an extra error

</blockquote></details>

What about just removing the attribute and requiring stop_app to be called manually before this?

Otherwise seems fine to me

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LFOjI5p1u9UpkyX9dC_:b-fef956) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

What about just removing the attribute and requiring stop_app to be called manually before this?

Otherwise seems fine to me
</blockquote></details>

eh, that kinda defeats the purpose of adding an API for unload...

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LFOy_Yy79IVLannqUAq:b-b1oawa) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

eh, that kinda defeats the purpose of adding an API for unload...
</blockquote></details>

Okay, then just always removing should be fine

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dthkao, @winterfroststrom, and @k2fong)

---

*[mobly/controllers/android_device.py, line 919 at r1](https://reviewable.io/reviews/google/mobly/463#-LF4Ycph8RYuHhsjRXsZ:-LFPFC_dBWDoSrIIJozy:b-896fix) ([raw file](https://github.com/google/mobly/blob/597606e2c6a244c1a8a00730234981f1296ad284/mobly/controllers/android_device.py#L919)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Okay, then just always removing should be fine
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463)*

**Comment by winterfroststrom** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @dthkao, @winterfroststrom, and @k2fong)

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/463#-:-LFPhJxT7XqkT86MSplh:bnfp4nl)*

**Pull request merged**
