### PR TITLE
Fixed function name change

### PR DESCRIPTION
**Pull request by l-meng**
Refactor function name

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/233)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/monsoon.py, line 820 at r1](https://reviewable.io:443/reviews/google/mobly/233#-Kn118JoBdbLlLtm5CzC:-Kn118JoBdbLlLtm5CzD:b-g9975a) ([raw file](https://github.com/google/mobly/blob/89a1e5a128b130a1234e39aafaead892b75c87ef/mobly/controllers/monsoon.py#L820)):*
> ```Python
>         self.usb("auto")
>         time.sleep(1)
>         with self.dut.handle_reboot():
> ```

Monsoon should be usb_disconnect and not reboot, shouldn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/233)*

**Comment by l-meng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/monsoon.py, line 820 at r1](https://reviewable.io:443/reviews/google/mobly/233#-Kn118JoBdbLlLtm5CzC:-Kn13T5SV0nhWatfZKSU:b-896fix) ([raw file](https://github.com/google/mobly/blob/89a1e5a128b130a1234e39aafaead892b75c87ef/mobly/controllers/monsoon.py#L820)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Monsoon should be usb_disconnect and not reboot, shouldn't it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/233)*

**Comment by adorokhine** [comment]
:lgtm: leaving second lgtm and merge to David while Ang's out

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/233#-:-Kn13XWSZspTx1aAwFMD:b-utroyo)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/233#-:-Kn174-m5KRC3WOwKmdr:bnfp4nl)*

**Pull request merged**
