### PR TITLE
Add waitForEvent in CallbackHandler.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/142)

### CODE REVIEW

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 87 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b446Gg0tcSXqNrKB:-Kf9b447yX-bublOFHyH:bu9l2d0) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L87)):*
> ```Python
> 
>     def waitForEvent(self, event_name, predicate, timeout=120):
>         """Wait for an event of a specific name that satisfies the predict.
> ```

predict

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 88 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b05omVSQQJHVxBjh:-Kf9b05omVSQQJHVxBji:bd455vw) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L88)):*
> ```Python
>     def waitForEvent(self, event_name, predicate, timeout=120):
>         """Wait for an event of a specific name that satisfies the predict.
>   
> ```

Trailing whitespace (yapf?)

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 97 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b9AACO4mrK6vz6k7:-Kf9b9AACO4mrK6vz6k8:b-ydv2t5) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L97)):*
> ```Python
>   
>         Note all events of the same name that are received but don't satisfy
>         the predicate will be disregarded and not be available for further
> ```

disregarded -> discarded

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 116 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9bQNkHNtl2wqA5xMK:-Kf9bQNkHNtl2wqA5xML:bx2o1ju) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L116)):*
> ```Python
>         while time.time() <= deadline:
>             # Calculate the max timeout for the next event rpc call.
>             rpc_timeout = deadline - time.time()
> ```

Race condition: if time is 50ms and deadline is 51ms, but it takes 2ms to make it from the while loop condition to the subtraction, rpc_timeout will end up negative.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 122 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9bjHsEdo-DwJeKNx7:-Kf9bjHt4t-nvYIigo4z:b-hugky6) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L122)):*
> ```Python
>                 # Ignoring TimeoutError since we need to throw one with a more
>                 # specific message.
>                 continue
> ```

Not break?

---

*[tests/mobly/controllers/android_device_lib/callback_handler_test.py, line 79 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9bmnSoZN4oPy-GDgM:-Kf9bmnSoZN4oPy-GDgN:b-38dvc0) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/tests/mobly/controllers/android_device_lib/callback_handler_test.py#L79)):*
> ```Python
>             ret_value=None,
>             method_name=None)
>         expected_msg = 'Timed out after 0.01s waiting for an "AsyncTaskResult" event that satisfies the predicate "some_condition".'
> ```

I thought mobly had an 80 char line width limit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142)*

**Comment by xpconanfan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 87 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b446Gg0tcSXqNrKB:-Kf9imyMwSyPKh24kRq7:b-896fix) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L87)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

predict
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 88 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b05omVSQQJHVxBjh:-Kf9ipGB_kjzks7k5Lhg:b-896fix) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L88)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Trailing whitespace (yapf?)
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 97 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b9AACO4mrK6vz6k7:-Kf9iseJ3kEWnXgEPCa7:b-896fix) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L97)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

disregarded -> discarded
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 116 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9bQNkHNtl2wqA5xMK:-Kf9j45wnmmKANwtyg2U:btaespn) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L116)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Race condition: if time is 50ms and deadline is 51ms, but it takes 2ms to make it from the while loop condition to the subtraction, rpc_timeout will end up negative.
</blockquote></details>

Done.
The unit here is 'second' though, is it possible to take that long?

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 122 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9bjHsEdo-DwJeKNx7:-Kf9kcYQNRgOxK3Cff0E:b-896fix) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L122)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Not break?
</blockquote></details>

Done.

---

*[tests/mobly/controllers/android_device_lib/callback_handler_test.py, line 79 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9bmnSoZN4oPy-GDgM:-Kf9jyrqSUWyYTkskSad:bq9f2wq) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/tests/mobly/controllers/android_device_lib/callback_handler_test.py#L79)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I thought mobly had an 80 char line width limit?
</blockquote></details>

yapf doesn't automatically break continuous long strings...
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142)*

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 88 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b05omVSQQJHVxBjh:-Kf9ltZBPHLpv1k-1V8H:b-ed4yft) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L88)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

 Trailing whitespace is still present.

---

*[tests/mobly/controllers/android_device_lib/callback_handler_test.py, line 100 at r2](https://reviewable.io:443/reviews/google/mobly/142#-Kf9mJWJqeuAyBJzKaEW:-Kf9mJWL-igQ5WWsL799:b-d4v4x6) ([raw file](https://github.com/google/mobly/blob/4b3d790c799f6fe510fd8cc009eabb9eb45b9482/tests/mobly/controllers/android_device_lib/callback_handler_test.py#L100)):*
> ```Python
> 
>         def some_condition(event):
>             return False
> ```

Are you making a separate def for this on purpose? Would be much shorter as just handler.waitForEvent('AsyncTaskResult', lambda _: False, 0.01)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142)*

**Comment by xpconanfan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 88 at r1](https://reviewable.io:443/reviews/google/mobly/142#-Kf9b05omVSQQJHVxBjh:-Kf9pBlxtO0_-uBQOTyf:bem50wc) ([raw file](https://github.com/google/mobly/blob/ef6fa048d2004b9ae3ab01bc3499f7c93d387614/mobly/controllers/android_device_lib/callback_handler.py#L88)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

 Trailing whitespace is still present.
</blockquote></details>

Done.
Interesting, yapf failed to remove these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/controllers/android_device_lib/callback_handler_test.py, line 100 at r2](https://reviewable.io:443/reviews/google/mobly/142#-Kf9mJWJqeuAyBJzKaEW:-Kf9pWN5-Ktq3Aa02Bwp:b-4wdzzd) ([raw file](https://github.com/google/mobly/blob/4b3d790c799f6fe510fd8cc009eabb9eb45b9482/tests/mobly/controllers/android_device_lib/callback_handler_test.py#L100)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Are you making a separate def for this on purpose? Would be much shorter as just handler.waitForEvent('AsyncTaskResult', lambda _: False, 0.01)
</blockquote></details>

Yeah, this way it looks more like a real use case with name `some_condition`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142)*

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 86 at r3](https://reviewable.io:443/reviews/google/mobly/142#-Kf9pvxRnC2-vZLVW9AB:-Kf9pvxRnC2-vZLVW9AC:b-3ifclj) ([raw file](https://github.com/google/mobly/blob/c106051b6eeae7782b1875a65684442492b29aee/mobly/controllers/android_device_lib/callback_handler.py#L86)):*
> ```Python
>         return snippet_event.from_dict(raw_event)
> 
>     def waitForEvent(self, event_name, predicate, timeout=120):
> ```

Should this be a constant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 86 at r3](https://reviewable.io:443/reviews/google/mobly/142#-Kf9pvxRnC2-vZLVW9AB:-KfA5-xMruy9Mp4Cr8Ep:b-896fix) ([raw file](https://github.com/google/mobly/blob/c106051b6eeae7782b1875a65684442492b29aee/mobly/controllers/android_device_lib/callback_handler.py#L86)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Should this be a constant?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/142#-:-KfABmyUOUDhkOTSRIs8:bnfp4nl)*

**Pull request merged**
