### PR TITLE
Fix event client handling under new startup process.

### LINKED ISSUE #221: `snippet_client._start_event_client` crashes
because of the extra `host_port` arg.

This crashes all tests that use `@AsyncRpc`.

We should add some unit tests for this...

### PR DESCRIPTION
**Pull request by adorokhine**
* Fix bug
* Updates to jsonrpc unit tests
* Fix all incorrect uses of `assertRaises`

For #215 
Fixes #221

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/222)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 142 at r1](https://reviewable.io:443/reviews/google/mobly/222#-KlQEEpQJ3ucg8uTkN-j:-KlQEEpQJ3ucg8uTkN-k:b-3m5zkq) ([raw file](https://github.com/google/mobly/blob/c20b6f1ba95f9939858dffa423fdf1bf7fef3d44/mobly/controllers/android_device_lib/snippet_client.py#L142)):*
> ```Python
>         event_client = SnippetClient(
>             package=self.package, adb_proxy=self._adb, log=self.log)
>         event_client.host_port = self.host_port
> ```

(Not sure if this is within the scope of this PR.)
Should we add a unit test that makes sure the `event_client` uses the same `host_port` as the parent client that created the event client?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/222)*

**Comment by adorokhine** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 142 at r1](https://reviewable.io:443/reviews/google/mobly/222#-KlQEEpQJ3ucg8uTkN-j:-KlQKWYfOqcjaBOZtZA1:b-896fix) ([raw file](https://github.com/google/mobly/blob/c20b6f1ba95f9939858dffa423fdf1bf7fef3d44/mobly/controllers/android_device_lib/snippet_client.py#L142)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

(Not sure if this is within the scope of this PR.)
Should we add a unit test that makes sure the `event_client` uses the same `host_port` as the parent client that created the event client?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/222)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 231 at r2](https://reviewable.io:443/reviews/google/mobly/222#-KlR02OhSVsXA6sC48Qq:-KlR02OhSVsXA6sC48Qr:b-y4rdz8) ([raw file](https://github.com/google/mobly/blob/4de916df19009682c2e51d5f4a5bc8e9bb5279e0/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L231)):*
> ```Python
> 
>     @mock.patch('socket.create_connection')
>     def test_rpc_call_async(self, mock_create_connection):
> ```

Hmm, this seems identical to `test_rpc_call_increment_counter`. Am I missing something?...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/222)*

**Comment by adorokhine** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 231 at r2](https://reviewable.io:443/reviews/google/mobly/222#-KlR02OhSVsXA6sC48Qq:-KlR17AzZtpMMrBdbnHW:b5qk4v) ([raw file](https://github.com/google/mobly/blob/4de916df19009682c2e51d5f4a5bc8e9bb5279e0/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L231)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, this seems identical to `test_rpc_call_increment_counter`. Am I missing something?...
</blockquote></details>

Whoops, good catch! I started creating a new test here but decided to put it in snippet_client instead. This code shouldn't have been committed. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/222)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 148 at r3](https://reviewable.io:443/reviews/google/mobly/222#-KlR208gYCLqbHRd_csT:-KlR208gYCLqbHRd_csU:b-creb0e) ([raw file](https://github.com/google/mobly/blob/bb85ca2966791baecca17e2cb251c09ded139d07/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L148)):*
> ```Python
> 
>     @mock.patch('socket.create_connection')
>     def test_connect_no_response(self, mock_create_connection):
> ```

Hmm, why is this test being removed in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/222)*

**Comment by adorokhine** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 148 at r3](https://reviewable.io:443/reviews/google/mobly/222#-KlR208gYCLqbHRd_csT:-KlR2xtrn1hhmrQ9gju9:bmpx7qh) ([raw file](https://github.com/google/mobly/blob/bb85ca2966791baecca17e2cb251c09ded139d07/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L148)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, why is this test being removed in this PR?
</blockquote></details>

`assertRaises` was being used incorrectly here (msg is what it prints if it triggers, not what it checks against). Upon fixing the bug it turned out that it's actually returning NO_RESPONSE_FROM_SERVER instead of NO_RESPONSE_FROM_HANDSHAKE, which makes sense because by the time you've finished connect, handshake has already completed.

NO_RESPONSE_FROM_SERVER is already being tested by `test_rpc_no_response`, and in fact the code seems to be the same.

Handshake errors from connect are already being tested by `test_connect_handshake`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/222)*

**Comment by xpconanfan** [comment]
:lgtm:

Thanks for fixing this!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/222#-:-KlR48Z-pox3K3INMlFn:b-kym177)*

**Pull request merged**
