### PR TITLE
Make a logging statement more contextual.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/704)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/704)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[mobly/base_test.py, line 608 at r1](https://reviewable.io/reviews/google/mobly/704#-MQq07Bb5L-lAYW-3uXN:-MQq07Bb5L-lAYW-3uXO:b2iv3t6) ([raw file](https://github.com/google/mobly/blob/0dc568e236a5a3c3432601f29d4f2b051e31ee72/mobly/base_test.py#L608)):*
> ```Python
>           raise
>         except Exception as e:
>           logging.exception('Exception occurred in the `teardown_test` of %s',
> ```

Better to add a dot at the end.

**Review by xpconanfan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/704)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[mobly/base_test.py, line 608 at r1](https://reviewable.io/reviews/google/mobly/704#-MQq07Bb5L-lAYW-3uXN:-MQqBk641GuOIbmqO_fl:b-896fix) ([raw file](https://github.com/google/mobly/blob/0dc568e236a5a3c3432601f29d4f2b051e31ee72/mobly/base_test.py#L608)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

Better to add a dot at the end.
</blockquote></details>

Done.

**Review by eric100lin — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/704#-:-MQqC-Pf3GRTwU3lx5Pl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eric100lin)

**Review by eric100lin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/mobly/704#-:-MQqDOxE4enQfUBx01o2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eric100lin)

**Pull request merged**
