### PR TITLE
Add support for `max_consecutive_error` in `repeat`.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/740)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/740)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @xpconanfan)

___
*[mobly/base_test.py, line 705 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvKO5KE1iPM9F2seZp:-MZvKO5KE1iPM9F2seZq:btnle5w) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L705)):*
> ```
> R
> ```
Better to add a trailing commas.
https://google.github.io/styleguide/pyguide.html#s3.4.1-trailing-commas
___
*[mobly/base_test.py, line 712 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvKcBhAA8QiUJbqVX3:-MZvKcBhAA8QiUJbqVX4:b-4jd1t7) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L712)):*
> ```
> %s
> ```
Is %d more fit here?
___
*[mobly/base_test.py, line 713 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvKykU6FM0W1TfMeWd:-MZvKykU6FM0W1TfMeWe:b-2pvskc) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L713)):*
> ```
> aborting the remaining iterations
> ```
Not sure that if we show how many remaining iterations will make it more helpful or not?
ex: aborting the remaining %d iterations

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/740)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @xpconanfan)

___
*[mobly/base_test.py, line 680 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvNbrt09_XUjsIM9_i:-MZvNbrt09_XUjsIM9_j:b-ei9liq) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L680)):*
> ```
> test test
> ```
is this duplicate? how about "Repeatedly execute the test."?

**Review by xpconanfan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/740)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @eric100lin and @xpconanfan)

___
*[mobly/base_test.py, line 705 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvKO5KE1iPM9F2seZp:-MZvNSI24fzsOMZ7VRwL:b-896fix) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L705)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> R
> ```
Better to add a trailing commas.
https://google.github.io/styleguide/pyguide.html#s3.4.1-trailing-commas
</blockquote></details>

Done.
___
*[mobly/base_test.py, line 712 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvKcBhAA8QiUJbqVX3:-MZvOzvaEXJXJVzJwYBt:b-896fix) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L712)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> %s
> ```
Is %d more fit here?
</blockquote></details>

Done.
___
*[mobly/base_test.py, line 713 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvKykU6FM0W1TfMeWd:-MZvP1BlEDHuUotcQ6SH:b-ydonj4) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L713)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> aborting the remaining iterations
> ```
Not sure that if we show how many remaining iterations will make it more helpful or not?
ex: aborting the remaining %d iterations
</blockquote></details>

Done. Good idea!

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/740)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @eric100lin and @xpconanfan)

___
*[mobly/base_test.py, line 688 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvPsII4of9c8rCyQlu:-MZvPsII4of9c8rCyQlv:b-heiutz) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L688)):*
> ```
> ,
> ```
It's better to add some words for this args.

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/740)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @xpconanfan)

___
*[tests/mobly/base_test_test.py, line 2370 at r2](https://reviewable.io/reviews/google/mobly/740#-MZvQSOK02aaSHtcRfJu:-MZvQSOK02aaSHtcRfJv:bbwu1x9) ([raw file](https://github.com/google/mobly/blob/348092629df90bd51e0bc5a7724610cd0c76690b/tests/mobly/base_test_test.py#L2370)):*
> ```
> )
> ```
Better to add a trailing commas.
https://google.github.io/styleguide/pyguide.html#s3.4.1-trailing-commas

**Review by xpconanfan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/740)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @eric100lin and @xpconanfan)

___
*[mobly/base_test.py, line 680 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvNbrt09_XUjsIM9_i:-MZvQKaN5MX9mTfHpnhH:b-896fix) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L680)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> test test
> ```
is this duplicate? how about "Repeatedly execute the test."?
</blockquote></details>

Done.
___
*[mobly/base_test.py, line 688 at r1](https://reviewable.io/reviews/google/mobly/740#-MZvPsII4of9c8rCyQlu:-MZvQJd9AP_o-zZtYUnY:b-896fix) ([raw file](https://github.com/google/mobly/blob/05bcec456b88587b051e746ba99047bde085018f/mobly/base_test.py#L688)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> ,
> ```
It's better to add some words for this args.
</blockquote></details>

Done.
___
*[tests/mobly/base_test_test.py, line 2370 at r2](https://reviewable.io/reviews/google/mobly/740#-MZvQSOK02aaSHtcRfJu:-MZvRnyhDjDSFrCVVYU7:b-896fix) ([raw file](https://github.com/google/mobly/blob/348092629df90bd51e0bc5a7724610cd0c76690b/tests/mobly/base_test_test.py#L2370)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> )
> ```
Better to add a trailing commas.
https://google.github.io/styleguide/pyguide.html#s3.4.1-trailing-commas
</blockquote></details>

Done.

**Review by eric100lin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/mobly/740#-:-MZvSQcv2RPSuNfHfM9Z:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @xpconanfan)

**Review by eric100lin — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/740)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xpconanfan)

**Pull request merged**
