### PR TITLE
Don't try symlinking log dir if the OS doesn't support it.

### PR DESCRIPTION
**Pull request by adorokhine**
Issue #151

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/152)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/logger.py, line 174 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOtboJi_8AF5gOt3CR:-KfOtboJi_8AF5gOt3CS:be7wvfs) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L174)):*
> ```Python
>     log.log_path = log_path
>     logging.log_path = log_path
>     return log
> ```

why is this added?

---

*[mobly/logger.py, line 215 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOuYX5YDUkybMCScDG:-KfOuYX5YDUkybMCScDH:b-qcmr2e) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L215)):*
> ```Python
>     logger = _setup_test_logger(log_path, prefix, filename)
>     logger.info('Logs are being written to: "%s"', log_path)
>     if hasattr(os, 'symlink'):
> ```

wouldn't the more pythonic way be letting it fail and catch the exception?

---

*[mobly/logger.py, line 219 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOti8S-2zWuli4rqKL:-KfOti8S-2zWuli4rqKM:bz9f3jl) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L219)):*
> ```Python
>     else:
>       logger.warn(
>           'Not creating "latest" log alias due to lack of OS symlink support')
> ```

It would be kinda difficult to find the result without 'latest', we should try to support it as much as possible. It'll also make our output format consistent.

Should we make a copy instead of a symlink if symlink is not supported?

Also it looks like the recent three versions of Window do support symlink, before that, there were 'shortcut'. So I think it is possible to achieve a similar effect on windows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/logger.py, line 214 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOuk8eWXk-akp2ovVD:-KfOuk8eWXk-akp2ovVE:bc873gt) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L214)):*
> ```Python
>     create_dir(log_path)
>     logger = _setup_test_logger(log_path, prefix, filename)
>     logger.info('Logs are being written to: "%s"', log_path)
> ```

could this just use `logging`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/logger.py, line 174 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOtboJi_8AF5gOt3CR:-KfP-o_7DqhsigpzKwqE:bwtgaqp) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L174)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why is this added?
</blockquote></details>

Because the return value of this function was already being assigned to a variable, so that variable was only set to None.
Removed this line and the assignment and used `logging` instead.

---

*[mobly/logger.py, line 214 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOuk8eWXk-akp2ovVD:-KfP0-XC55SF0sDv7nqJ:b-896fix) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L214)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

could this just use `logging`?
</blockquote></details>

Done.

---

*[mobly/logger.py, line 215 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOuYX5YDUkybMCScDG:-KfP01-r2T9FEJ5PQBa6:b-63vgcq) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L215)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

wouldn't the more pythonic way be letting it fail and catch the exception?
</blockquote></details>

This code has changed.

---

*[mobly/logger.py, line 219 at r1](https://reviewable.io:443/reviews/google/mobly/152#-KfOti8S-2zWuli4rqKL:-KfP02BGAbidE-FiLjBw:b-896fix) ([raw file](https://github.com/google/mobly/blob/8db4a080e1783fa5b6105d063b96f6a0fd30b9f9/mobly/logger.py#L219)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It would be kinda difficult to find the result without 'latest', we should try to support it as much as possible. It'll also make our output format consistent.

Should we make a copy instead of a symlink if symlink is not supported?

Also it looks like the recent three versions of Window do support symlink, before that, there were 'shortcut'. So I think it is possible to achieve a similar effect on windows.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/logger.py, line 211 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPUpmH7DeqddXb-rc_:-KfPUpmH7DeqddXb-rca:bd28jb6) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/logger.py#L211)):*
> ```Python
>     utils.create_dir(log_path)
>     _setup_test_logger(log_path, prefix, filename)
>     logging.info('Logs are being written to: "%s"', log_path)
> ```

Perhaps the log msg here should be something more generic like "Test output are streamed to %s"
Since it is not just the logs that are written there.

---

*[mobly/utils.py, line 97 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPV3D-LFPvsHv2x_Pw:-KfPV3D-LFPvsHv2x_Px:b-f5gt8y) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/utils.py#L97)):*
> ```Python
> 
> 
> def create_alias(target_path, link_path):
> ```

should `link_path` be called `alias_path`, or should this be called `create_link`?
Either is fine as long as it's consistent.

---

*[mobly/utils.py, line 101 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPTD7OaclvSCvO9UH0:-KfPTD7OaclvSCvO9UH1:b-izhaq5) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/utils.py#L101)):*
> ```Python
> 
>     On Unix, this is implemented via symlink. On Windows, this is done by
>     creating a Windows shortcut file.
> ```

No `Args` section in docstring?

---

*[mobly/utils.py, line 108 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPUY3tu8LIgojStMVo:-KfPUY3tu8LIgojStMVp:b-jzdf8k) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/utils.py#L108)):*
> ```Python
>         os.remove(link_path)
>     if platform.system() == 'Windows':
>         from win32com import client
> ```

Googling `win32com` seems to imply that it is an extra package that needs to be installed separately?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r2, 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/logger.py, line 211 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPUpmH7DeqddXb-rc_:-KfSWyjiyQppkDOGyNdP:b-896fix) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/logger.py#L211)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Perhaps the log msg here should be something more generic like "Test output are streamed to %s"
Since it is not just the logs that are written there.
</blockquote></details>

Done.

---

*[mobly/utils.py, line 97 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPV3D-LFPvsHv2x_Pw:-KfSXHKG9nHITU0323aG:b-896fix) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/utils.py#L97)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should `link_path` be called `alias_path`, or should this be called `create_link`?
Either is fine as long as it's consistent.
</blockquote></details>

Done.

---

*[mobly/utils.py, line 101 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPTD7OaclvSCvO9UH0:-KfSXSjfXGrtarzGXeCs:b-896fix) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/utils.py#L101)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

No `Args` section in docstring?
</blockquote></details>

Done.

---

*[mobly/utils.py, line 108 at r2](https://reviewable.io:443/reviews/google/mobly/152#-KfPUY3tu8LIgojStMVo:-KfSaezd3wk57dcL687B:b-896fix) ([raw file](https://github.com/google/mobly/blob/94a499421ccf7174400c71f38ac6bf335f073f7d/mobly/utils.py#L108)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Googling `win32com` seems to imply that it is an extra package that needs to be installed separately?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by xpconanfan** [comment]
Reviewed 2 of 2 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup.py, line 40 at r3](https://reviewable.io:443/reviews/google/mobly/152#-KfSbLj36erW0qj3n0zE:-KfSbLj36erW0qj3n0zF:bdt78wh) ([raw file](https://github.com/google/mobly/blob/11d90ed004a5edaacd90243aa7502ca0167001bc/setup.py#L40)):*
> ```Python
> 
> if platform.system() == 'Windows':
>     install_requires.append('pywin32')
> ```

I hope there's no py2/py3 issue for 'pywin32' module....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by xpconanfan** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[setup.py, line 40 at r3](https://reviewable.io:443/reviews/google/mobly/152#-KfSbLj36erW0qj3n0zE:-KfSciHP8VDdx0cl4VnT:b9ajjmw) ([raw file](https://github.com/google/mobly/blob/11d90ed004a5edaacd90243aa7502ca0167001bc/setup.py#L40)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I hope there's no py2/py3 issue for 'pywin32' module....
</blockquote></details>

Seems to be compatible with both like most modules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[setup.py, line 40 at r3](https://reviewable.io:443/reviews/google/mobly/152#-KfSbLj36erW0qj3n0zE:-KfSdCjqXBhcvYqkJo8U:b-896fix) ([raw file](https://github.com/google/mobly/blob/11d90ed004a5edaacd90243aa7502ca0167001bc/setup.py#L40)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Seems to be compatible with both like most modules.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/152)*

**Comment by xpconanfan** [comment]
This was merged without LGTM?

**Comment by adorokhine** [comment]
Hm, weird. Reviewable showed me that code review was done and that it was ready for merge (it gave me the full green circle and the 'squash and delete' button.

Sorry about that; not intended. If you have any more comments I'm happy to start a new PR for them or roll this one back.

**Comment by xpconanfan** [comment]
Np. Just curious what happened.
Yeah, reviewable is confusing.
It'll send out an email like that even if there's no LGTM.

**Pull request merged**
