### PR TITLE
Fix unicode encoding issues with records module.

### PR DESCRIPTION
**Pull request by winterfroststrom**
Part of #459

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/460)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom and @xpconanfan)

---

*[mobly/records.py, line 121 at r1](https://reviewable.io/reviews/google/mobly/460#-LEkPGVvCFZfOHiDerqZ:-LEkPGVvCFZfOHiDerq_:bldbbrk) ([raw file](https://github.com/google/mobly/blob/682a2ffccbd86ff445e4e7d1c08cf32a7626b5c0/mobly/records.py#L121)):*
> ```Python
>         with self._lock:
>             # Use safe_dump here to avoid language-specific tags in final output.
>             with open(self._path, 'a', encoding='utf-8') as f:
> ```

is this the only place we need to use this `open`?
and does this work in py2?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/460)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom and @xpconanfan)

---

*[mobly/records.py, line 121 at r1](https://reviewable.io/reviews/google/mobly/460#-LEkPGVvCFZfOHiDerqZ:-LEkU7ekE3WzXw5NvG6Y:b3aba9u) ([raw file](https://github.com/google/mobly/blob/682a2ffccbd86ff445e4e7d1c08cf32a7626b5c0/mobly/records.py#L121)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

is this the only place we need to use this `open`?
and does this work in py2?
</blockquote></details>

Actually, I think this should probably be used everywhere, hence the bug I filed.
It's just that this should fix the issue that was actually encountered.

Yes, it works with python2, io.open is for compat reasons since encoding isn't a valid keyword normally.

Note, python2 doesn't have this issue because PyYaml sets utf-8 encoding by default and python2 io streams don't set an encoding.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/460)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom and @xpconanfan)

---

*[mobly/records.py, line 122 at r1](https://reviewable.io/reviews/google/mobly/460#-LEkVJwA-Kvdl5T1usIn:-LEkVJwB6zUuYz7oc-_d:b-d83665) ([raw file](https://github.com/google/mobly/blob/682a2ffccbd86ff445e4e7d1c08cf32a7626b5c0/mobly/records.py#L122)):*
> ```Python
>             # Use safe_dump here to avoid language-specific tags in final output.
>             with open(self._path, 'a', encoding='utf-8') as f:
>                 # Setting encoding on safe_dump doesn't do anything
> ```

can we clarify the comment here?
i don't quite understand why this comment is here as it is...

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/460)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom and @xpconanfan)

---

*[mobly/records.py, line 122 at r1](https://reviewable.io/reviews/google/mobly/460#-LEkVJwA-Kvdl5T1usIn:-LEkXUWD7FT3UNIrv9pD:b499q7j) ([raw file](https://github.com/google/mobly/blob/682a2ffccbd86ff445e4e7d1c08cf32a7626b5c0/mobly/records.py#L122)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

can we clarify the comment here?
i don't quite understand why this comment is here as it is...
</blockquote></details>

Changed

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/460)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @xpconanfan)

---

*[mobly/records.py, line 122 at r1](https://reviewable.io/reviews/google/mobly/460#-LEkVJwA-Kvdl5T1usIn:-LEkYSYV-8lhFw1ZnexV:b-sngt1k) ([raw file](https://github.com/google/mobly/blob/682a2ffccbd86ff445e4e7d1c08cf32a7626b5c0/mobly/records.py#L122)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Changed
</blockquote></details>

"setting the encoding on yaml.safe_dump"
but we never did that?

So it is a bit odd to mention this option here...

Also should we move this comment block to before the `with open`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/460)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @winterfroststrom and @xpconanfan)

---

*[mobly/records.py, line 122 at r1](https://reviewable.io/reviews/google/mobly/460#-LEkVJwA-Kvdl5T1usIn:-LEkYle06xwlctD2VDVq:b1wb5rs) ([raw file](https://github.com/google/mobly/blob/682a2ffccbd86ff445e4e7d1c08cf32a7626b5c0/mobly/records.py#L122)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"setting the encoding on yaml.safe_dump"
but we never did that?

So it is a bit odd to mention this option here...

Also should we move this comment block to before the `with open`?
</blockquote></details>

We never did that, but the PyYAML api provides that parameter, which may or may not be preferable, so it's explaining why that doesn't work.

If you think it's unnecessary, I can remove it.


Also moved.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/460)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @xpconanfan)

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/460#-:-LEk_C-r8kMgdxA0-wVN:bnfp4nl)*

**Pull request merged**
