### PR TITLE
Implemented streamed instrumentation tests

### LINKED ISSUE #391: Add timing information for instrumentation tests

### PR DESCRIPTION
**Pull request by winterfroststrom**
Fixes #391

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/392)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[mobly/controllers/android_device_lib/adb.py, line 180 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBjvbMANdfbOTNM2-U:-LCBjvbMANdfbOTNM2-V:b7l1db) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L180)):*
> ```Python
>             raise AdbError(cmd=args, stdout=out, stderr=err, ret_code=ret)
> 
>     def _stream_cmd(self, args, shell, level, handler):
> ```

`_execute_and_process_stdout`

---

*[mobly/controllers/android_device_lib/adb.py, line 203 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBfPD94fYurH-HZEyD:-LCBfPD94fYurH-HZEyE:bpp6stj) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L203)):*
> ```Python
>             shell=shell,
>             bufsize=1)
>         out_buffer = []
> ```

not needed

---

*[mobly/controllers/android_device_lib/adb.py, line 209 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBiHuR8rnHRDx-bEdS:-LCBiHuR8rnHRDx-bEdT:b-l6mwxj) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L209)):*
> ```Python
>             if line:
>                 line = line.decode('utf-8')
>                 logging.log(level, line.rstrip())
> ```

remove

---

*[mobly/controllers/android_device_lib/adb.py, line 211 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBiJcUEBtCnoGwoaZG:-LCBiJcUEBtCnoGwoaZH:b3jasbe) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L211)):*
> ```Python
>                 logging.log(level, line.rstrip())
>                 out_buffer.append(line)
>                 if handler:
> ```

handler is required

---

*[mobly/controllers/android_device_lib/adb.py, line 212 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBiOS_24Z1patPnBHE:-LCBiOSa35mms-i-UJpX:b-oend6p) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L212)):*
> ```Python
>                 out_buffer.append(line)
>                 if handler:
>                     handler(line)
> ```

what if the handler throw an error?

---

*[mobly/controllers/android_device_lib/adb.py, line 215 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBjs9dDT6Wm_UZyWS9:-LCBjs9eAmZg3ACbCv61:bpp6stj) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L215)):*
> ```Python
>             else:
>                 (eof_out, eof_err) = proc.communicate()
>                 out_buffer.append(eof_out)
> ```

not needed

---

*[mobly/controllers/android_device_lib/adb.py, line 220 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBj6MG7ZrCpiqLI7Tl:-LCBj6MG7ZrCpiqLI7Tm:b-uchag3) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L220)):*
> ```Python
>         ret = proc.returncode
>         if ret == 0:
>             return out
> ```

return stderr if there is any?

---

*[mobly/controllers/android_device_lib/adb.py, line 222 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBj8bhDhNpC3DuUuHC:-LCBj8bhDhNpC3DuUuHD:bl10liu) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L222)):*
> ```Python
>             return out
>         else:
>             raise AdbError(cmd=args, stdout=out, stderr=err, ret_code=ret)
> ```

stdout doesn't need to be in this error right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by winterfroststrom** [comment]
Need to add unit tests/test some process failure scenarios.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 180 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBjvbMANdfbOTNM2-U:-LCG8a7C60ls5L4qKTud:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L180)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`_execute_and_process_stdout`
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 203 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBfPD94fYurH-HZEyD:-LCG8bMF--aVh_9tUFq_:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L203)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 209 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBiHuR8rnHRDx-bEdS:-LCG8dDm9nm_1gm5GdqO:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L209)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 211 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBiJcUEBtCnoGwoaZG:-LCG8eD9Eyqaj__UoZFU:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L211)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

handler is required
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 212 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBiOS_24Z1patPnBHE:-LCG8jHS41rApna13Htx:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L212)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what if the handler throw an error?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 215 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBjs9dDT6Wm_UZyWS9:-LCG8kKD2Hmn-IbJqBvA:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L215)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 220 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBj6MG7ZrCpiqLI7Tl:-LCG8lc_61VKdtc3WOBK:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L220)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

return stderr if there is any?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 222 at r2](https://reviewable.io/reviews/google/mobly/392#-LCBj8bhDhNpC3DuUuHC:-LCG8nL5-zQtHHr02Nr6:b-896fix) ([raw file](https://github.com/google/mobly/blob/0497c3b77272c047ac5aee2bef53ef4ccca3586c/mobly/controllers/android_device_lib/adb.py#L222)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

stdout doesn't need to be in this error right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392#-:-LCG8q6B36XlhYrmpxnm:b-g4nxph)*

**Comment by winterfroststrom** [comment]
Added unit tests and tested when process dies randomly.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392#-:-LCH-RNkCtcFH8B1X0Ot:b-umsxqg)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[mobly/controllers/android_device_lib/adb.py, line 206 at r3](https://reviewable.io/reviews/google/mobly/392#-LC_oUj11zZI2SW6BFxY:-LC_oUj11zZI2SW6BFxZ:bfcm7qw) ([raw file](https://github.com/google/mobly/blob/f4f42130704c02f0cb40b35670586bca7d6abd87/mobly/controllers/android_device_lib/adb.py#L206)):*
> ```Python
>             shell=shell,
>             bufsize=1)
>         err = ''
> ```

not needed?

---

*[mobly/controllers/android_device_lib/adb.py, line 221 at r3](https://reviewable.io/reviews/google/mobly/392#-LC_khCQERM8OBURZEIG:-LC_khCQERM8OBURZEIH:b-bj5aq6) ([raw file](https://github.com/google/mobly/blob/f4f42130704c02f0cb40b35670586bca7d6abd87/mobly/controllers/android_device_lib/adb.py#L221)):*
> ```
> [elided]
> ```

What is elided?...

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 206 at r3](https://reviewable.io/reviews/google/mobly/392#-LC_oUj11zZI2SW6BFxY:-LCa2y-22qhSnK9V6gwj:b-896fix) ([raw file](https://github.com/google/mobly/blob/f4f42130704c02f0cb40b35670586bca7d6abd87/mobly/controllers/android_device_lib/adb.py#L206)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 221 at r3](https://reviewable.io/reviews/google/mobly/392#-LC_khCQERM8OBURZEIG:-LCa2HHCD0FDbh1fefYe:bta5lbs) ([raw file](https://github.com/google/mobly/blob/f4f42130704c02f0cb40b35670586bca7d6abd87/mobly/controllers/android_device_lib/adb.py#L221)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

> ```
> [elided]
> ```

What is elided?...
</blockquote></details>

it's just to indicate that stdout is missing, would you prefer empty string or None instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 221 at r3](https://reviewable.io/reviews/google/mobly/392#-LC_khCQERM8OBURZEIG:-LCaOWPv9OG92CD17Pzd:bs8gkfc) ([raw file](https://github.com/google/mobly/blob/f4f42130704c02f0cb40b35670586bca7d6abd87/mobly/controllers/android_device_lib/adb.py#L221)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

it's just to indicate that stdout is missing, would you prefer empty string or None instead?
</blockquote></details>

Should we add a more specific msg explaining that stdout has already been piped through the handler?

---

*[mobly/controllers/android_device_lib/adb.py, line 331 at r4](https://reviewable.io/reviews/google/mobly/392#-LCaOs5ZBoq-5AmkNi-D:-LCaOs5ZBoq-5AmkNi-E:bx7a4dg) ([raw file](https://github.com/google/mobly/blob/a39e767452e1ba5220345ebec5f521d945d20eea/mobly/controllers/android_device_lib/adb.py#L331)):*
> ```Python
>             runner: string, the test runner name, which defaults to
>                 DEFAULT_INSTRUMENTATION_RUNNER.
>             handler: func, a function to parse the instrumentation output line
> ```

"optional. When specified, does xxx"

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 221 at r3](https://reviewable.io/reviews/google/mobly/392#-LC_khCQERM8OBURZEIG:-LCaUIpY3umLkm0YdjzJ:b-896fix) ([raw file](https://github.com/google/mobly/blob/f4f42130704c02f0cb40b35670586bca7d6abd87/mobly/controllers/android_device_lib/adb.py#L221)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Should we add a more specific msg explaining that stdout has already been piped through the handler?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 331 at r4](https://reviewable.io/reviews/google/mobly/392#-LCaOs5ZBoq-5AmkNi-D:-LCaUKbUA152l5z1U3Ky:b-896fix) ([raw file](https://github.com/google/mobly/blob/a39e767452e1ba5220345ebec5f521d945d20eea/mobly/controllers/android_device_lib/adb.py#L331)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"optional. When specified, does xxx"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[mobly/controllers/android_device_lib/adb.py, line 336 at r5](https://reviewable.io/reviews/google/mobly/392#-LCac0mS4I0glk8XzpA8:-LCabwlT-XOBIGhkg8H0:b-bxk46c) ([raw file](https://github.com/google/mobly/blob/c37138c24f1393dc30dffa9bdbf41db6fd5f7181/mobly/controllers/android_device_lib/adb.py#L336)):*
> ```
>                 generated; otherwise if not specified, the stdout is simply
>                 returned once the instrumentation is finished.
> ```
"otherwise" is sufficient. remove "if not specified".

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_instrumentation_test.py, line 284 at r5](https://reviewable.io/reviews/google/mobly/392#-LCacEVA7shTjMVPehlV:-LCacEVA7shTjMVPehlW:b9c5inx) ([raw file](https://github.com/google/mobly/blob/c37138c24f1393dc30dffa9bdbf41db6fd5f7181/mobly/base_instrumentation_test.py#L284)):*
> ```Python
> 
>     Attributes:
>         begin_time: string or None, optional timestamp for when the test
> ```

"or None" is not needed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_instrumentation_test.py, line 284 at r5](https://reviewable.io/reviews/google/mobly/392#-LCacEVA7shTjMVPehlV:-LCaeAvNAb_3fda-yQG8:b-896fix) ([raw file](https://github.com/google/mobly/blob/c37138c24f1393dc30dffa9bdbf41db6fd5f7181/mobly/base_instrumentation_test.py#L284)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"or None" is not needed?
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/adb.py, line 336 at r5](https://reviewable.io/reviews/google/mobly/392#-LCac0mS4I0glk8XzpA8:-LCaeBet0-UgDN6bB7v_:b-896fix) ([raw file](https://github.com/google/mobly/blob/c37138c24f1393dc30dffa9bdbf41db6fd5f7181/mobly/controllers/android_device_lib/adb.py#L336)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

> ```
>                 generated; otherwise if not specified, the stdout is simply
>                 returned once the instrumentation is finished.
> ```
"otherwise" is sufficient. remove "if not specified".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r3, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/392#-:-LCaef1KC3KP9xeRQjRJ:bnfp4nl)*

**Pull request merged**
