### PR TITLE
Properly handle Exceptions containing unicode.

### LINKED ISSUE #358: [Py2] Unicode is not properly handled in string conversions
In Py2, we sometimes get:
```
...
mobly/records.py", line 102, in _test_end
I 16:41:23:508 UTC     self.details = str(e)
I 16:41:23:508 UTC UnicodeEncodeError: 'ascii' codec can't encode character u'\u2022' in position 32280: ordinal not in range(128)
```
This is caused by `str` not able to handle unicode properly in py2.

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #358

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/374)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/records.py, line 170 at r1](https://reviewable.io:443/reviews/google/mobly/374#-L0ICsP-sg8jydvp4kQe:-L0ICsP-sg8jydvp4kQf:b-3tpfsu) ([raw file](https://github.com/google/mobly/blob/b1e28527d0374f26035fddcf20a04b20875c1db8/mobly/records.py#L170)):*
> ```Python
>                 self.details = str(e.details)
>             except UnicodeEncodeError:
>                 self.details = unicode(e.details)
> ```

'unicode' not supported in py3? Granted you wouldn't get into this here except clause in py3...

---

*[mobly/records.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/374#-L0IDIg1vZuk87ABjExv:-L0IDIg1vZuk87ABjExw:btib8k8) ([raw file](https://github.com/google/mobly/blob/b1e28527d0374f26035fddcf20a04b20875c1db8/mobly/records.py#L510)):*
> ```Python
>             logging.warning('Controller info for %s is not YAML serializable!'
>                             ' Coercing it to string.' % name)
>             self.controller_info[name] = str(info, 'utf-8')
> ```

I think in py2 str only takes 1 arg.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/374)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/records.py, line 170 at r1](https://reviewable.io:443/reviews/google/mobly/374#-L0ICsP-sg8jydvp4kQe:-L0M3PrXGeZrrjkyIj65:b-896fix) ([raw file](https://github.com/google/mobly/blob/b1e28527d0374f26035fddcf20a04b20875c1db8/mobly/records.py#L170)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

'unicode' not supported in py3? Granted you wouldn't get into this here except clause in py3...
</blockquote></details>

Done.

---

*[mobly/records.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/374#-L0IDIg1vZuk87ABjExv:-L0M5Avl-frHm2JNoSRK:b-896fix) ([raw file](https://github.com/google/mobly/blob/b1e28527d0374f26035fddcf20a04b20875c1db8/mobly/records.py#L510)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I think in py2 str only takes 1 arg.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/374)*

**Comment by k2fong** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/records.py, line 172 at r2](https://reviewable.io:443/reviews/google/mobly/374#-L0Mwb4jEV5uXRQ9pjGA:-L0Mwb4kxg1Y8GT2rAIm:b-hf03yu) ([raw file](https://github.com/google/mobly/blob/6580ab33e26e04dbec1338721d64980e1b08c13a/mobly/records.py#L172)):*
> ```Python
>             self._set_details(e)
> 
>     def _set_details(self, content):
> ```

this seems like might be a good util function in case we have more unicode to generically handle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/374)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/records.py, line 172 at r2](https://reviewable.io:443/reviews/google/mobly/374#-L0Mwb4jEV5uXRQ9pjGA:-L0R-8VyxDFF3-6itgHX:bcdh7at) ([raw file](https://github.com/google/mobly/blob/6580ab33e26e04dbec1338721d64980e1b08c13a/mobly/records.py#L172)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

this seems like might be a good util function in case we have more unicode to generically handle
</blockquote></details>

This is pretty specific to how we want to handle details at the moment. It simply gives up if Py3 threw the error.
Not ready to be a public `utils` api which we have to support.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/374)*

**Comment by k2fong** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/374#-:-L0VonHzM2evuHtVDvEc:bnfp4nl)*

**Pull request merged**
