### PR TITLE
Travis CI: Add Python 3.6 and 3.7 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/549)

### CODE REVIEW

**Comment by cclauss** [comment]
Did you read the comment??

**Comment by xpconanfan** [comment]
Sorry, I see the issue is closed.
Does that mean there is no plan to fix travisCI and this workaround will always have to exist going forward?

**Comment by cclauss** [comment]
You have to keep up with the Travis blog https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration  They have already deprecating the keyword 'sudo' and they seem to be progressing fast.

**Comment by cclauss** [comment]
What change is requested here?

**Comment by xpconanfan** [comment]
Sorry, it's not clear how removing `sudo` and that post is related to adding py3.7 here.
And we are not sure why there's such urgency to add py3.7 CI using a hack.

Can you clarify these?

**Comment by xpconanfan** [comment]
Thanks!

**Pull request merged**
