### PR TITLE
Add support for listing tests in a test module.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/304)

### CODE REVIEW

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/304#-KrZ79kVPM7ut3uoCoEi:-KrZ79kVPM7ut3uoCoEj:b-fwtzv2) ([raw file](https://github.com/google/mobly/blob/09a5a6b0a3ce944b408174a44a3a1c36f3b7c812/mobly/base_test.py#L438)):*
> ```Python
>                               func.__name__, self.TAG)
> 
>     def get_all_test_names(self):
> ```

with get_all_test_names() being public, is there any worry that this might give different answer depending upon if setup_generated_tests() is called prior or not?

---

*[mobly/test_runner.py, line 138 at r1](https://reviewable.io:443/reviews/google/mobly/304#-KrZ3wxj8xsDQbZYqBqf:-KrZ3wxj8xsDQbZYqBqg:b-6gn6nx) ([raw file](https://github.com/google/mobly/blob/09a5a6b0a3ce944b408174a44a3a1c36f3b7c812/mobly/test_runner.py#L138)):*
> ```Python
>                 test_classes.append(module_member)
>     if len(test_classes) != 1:
>         logging.error('Expected 1 test class per file, found %s.',
> ```

I know this isn't apart of this review, but I'm trying to review more to get familiarity.  The error message isn't accurate if in case 0 test class is found.

---

*[mobly/test_runner.py, line 151 at r1](https://reviewable.io:443/reviews/google/mobly/304#-KrZ4Cz2tL7FXNcUOe5e:-KrZ4Cz2tL7FXNcUOe5f:btn62gs) ([raw file](https://github.com/google/mobly/blob/09a5a6b0a3ce944b408174a44a3a1c36f3b7c812/mobly/test_runner.py#L151)):*
> ```Python
>         logging.exception('Failed to retrieve generated tests.')
>     for name in cls.get_all_test_names():
>         print(name)
> ```

nit, this is probably the only place that will use this but consider returning a list of tests and print from the caller instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/304)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/304#-KrZ79kVPM7ut3uoCoEi:-KrZYYTKWV58Q8QNYgRd:b-jj77fh) ([raw file](https://github.com/google/mobly/blob/09a5a6b0a3ce944b408174a44a3a1c36f3b7c812/mobly/base_test.py#L438)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

with get_all_test_names() being public, is there any worry that this might give different answer depending upon if setup_generated_tests() is called prior or not?
</blockquote></details>

Changed the function name and clarified this in docstring.

---

*[mobly/test_runner.py, line 138 at r1](https://reviewable.io:443/reviews/google/mobly/304#-KrZ3wxj8xsDQbZYqBqf:-KrZRhTEbcQbf96Q_0Sg:bu175gf) ([raw file](https://github.com/google/mobly/blob/09a5a6b0a3ce944b408174a44a3a1c36f3b7c812/mobly/test_runner.py#L138)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

I know this isn't apart of this review, but I'm trying to review more to get familiarity.  The error message isn't accurate if in case 0 test class is found.
</blockquote></details>

In that case, it would be "Expected 1 test class per file, found []." with an empty list, which seems ok?

---

*[mobly/test_runner.py, line 151 at r1](https://reviewable.io:443/reviews/google/mobly/304#-KrZ4Cz2tL7FXNcUOe5e:-KrZUwqDIR9PWgH1EET0:b-j8awy9) ([raw file](https://github.com/google/mobly/blob/09a5a6b0a3ce944b408174a44a3a1c36f3b7c812/mobly/test_runner.py#L151)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

nit, this is probably the only place that will use this but consider returning a list of tests and print from the caller instead.
</blockquote></details>

Meant to keep this logic contained in this one function for better encapsulation.
Changed the name and added docstring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/304)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/test_runner.py, line 151 at r1](https://reviewable.io:443/reviews/google/mobly/304#-KrZ4Cz2tL7FXNcUOe5e:-KrZYlrCJG0wRN46Jltq:bkg3106) ([raw file](https://github.com/google/mobly/blob/09a5a6b0a3ce944b408174a44a3a1c36f3b7c812/mobly/test_runner.py#L151)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Meant to keep this logic contained in this one function for better encapsulation.
Changed the name and added docstring.
</blockquote></details>

Changed the print format a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/304)*

**Comment by k2fong** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/304#-:-Krb2aPzp0uOJdFCGO5Z:bnfp4nl)*

**Pull request merged**
