### PR TITLE
Remove redundant adb calls for serials.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/137)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 59 at r1](https://reviewable.io:443/reviews/google/mobly/137#-KegUGms0kBkhcFxpOFJ:-KegUGmtepcueCfMDYk4:b-fr3lcm) ([raw file](https://github.com/google/mobly/blob/21465f82c8aff45169a7c3824550b9f7e81cc2d4/mobly/controllers/android_device_lib/snippet_client.py#L59)):*
> ```Python
>             adb_proxy=adb_proxy)
>         self.package = package
>         self._serial = self._adb.serial
> ```

Does 'adb' have a 'serial' field? I thought it was ad that had that field?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/137)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 59 at r1](https://reviewable.io:443/reviews/google/mobly/137#-KegUGms0kBkhcFxpOFJ:-KegUil80WYMQNyihoTZ:bgz0djm) ([raw file](https://github.com/google/mobly/blob/21465f82c8aff45169a7c3824550b9f7e81cc2d4/mobly/controllers/android_device_lib/snippet_client.py#L59)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Does 'adb' have a 'serial' field? I thought it was ad that had that field?
</blockquote></details>

yes it does.
that's where the param for `-s` in each adb call come from...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/137)*

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/137)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/137#-:-Kf9PdSE4LJMeX9njNs7:bnfp4nl)*

**Pull request merged**
