### PR TITLE
Stop using utils.exe_cmd().

### LINKED ISSUE #97: Flake in unit tests
Reported in #87 
https://travis-ci.org/google/mobly/jobs/197104959

=================================== FAILURES ===================================
____________________ UtilsTest.test_start_standing_subproc _____________________
self = <tests.mobly.utils_test.UtilsTest testMethod=test_start_standing_subproc>
    def test_start_standing_subproc(self):
        with self.assertRaisesRegexp(utils.Error,
                                     "Process .* has terminated"):
\>           utils.start_standing_subprocess("sleep 0", check_health_delay=0.1)
E           AssertionError: Error not raised
tests/mobly/utils_test.py:32: AssertionErro

### LINKED ISSUE #118: utils.exe_cmd dies if command printed anything at all to stderr, even if command succeeded
Caught someone trying to use this...

### PR DESCRIPTION
**Pull request by adorokhine**
It dies if the process prints ANYTHING to stderr, even if it exited successfully.

Issue #163
Fixes #97
Fixes #118

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/164)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 33 at r1](https://reviewable.io:443/reviews/google/mobly/164#-Kft4IlohqXOZQbkgvwN:-Kft4IlpLhgfHHd6AJ8z:b-a1kill) ([raw file](https://github.com/google/mobly/blob/7b01a61aa1a22614e0e70eae04eb10370a4c8f4f/tests/mobly/utils_test.py#L33)):*
> ```Python
>                                      "Process .* has terminated"):
>             utils.start_standing_subprocess(
>                 ['sleep','0'], check_health_delay=0.5)
> ```

why the change from 0.1 to 0.5 and str to list?
this does not seem to be related to `exe_cmd`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/164)*

**Comment by adorokhine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 33 at r1](https://reviewable.io:443/reviews/google/mobly/164#-Kft4IlohqXOZQbkgvwN:-Kft95spFobm0QYGR4uD:b-896fix) ([raw file](https://github.com/google/mobly/blob/454b556b53133176e6e1f02ae6e0b3f41739bcb1/tests/mobly/utils_test.py#L33)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why the change from 0.1 to 0.5 and str to list?
this does not seem to be related to `exe_cmd`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/164)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/164#-:-KftHytyvUUIumc_97NM:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 33 at r1](https://reviewable.io:443/reviews/google/mobly/164#-Kft4IlohqXOZQbkgvwN:-Kg0s0bj_r8a4fdh3Uew:b-yz7gkv) ([raw file](https://github.com/google/mobly/blob/454b556b53133176e6e1f02ae6e0b3f41739bcb1/tests/mobly/utils_test.py#L33)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see this being changed to a list.
Is this a leak from the start standing subprocess change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/164)*

**Comment by adorokhine** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 33 at r1](https://reviewable.io:443/reviews/google/mobly/164#-Kft4IlohqXOZQbkgvwN:-Kg1Ig0bDteHmFq-Yszy:brssb8g) ([raw file](https://github.com/google/mobly/blob/454b556b53133176e6e1f02ae6e0b3f41739bcb1/tests/mobly/utils_test.py#L33)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I still see this being changed to a list.
Is this a leak from the start standing subprocess change?
</blockquote></details>

Thanks, good catch. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/164)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/164#-:-KgFrMky1iYJR0yzvtbz:bnfp4nl)*

**Comment by adorokhine** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/164)*

**Pull request merged**
