### PR TITLE
Add a test case to cover kill subprocess and descendants behavior.

### PR DESCRIPTION
**Pull request by eric100lin**
Add this test case before doing the psutil dependency removal
for utils.stop_standing_subprocess.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/786)

### CODE REVIEW

**Review by booneng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/786)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[tests/mobly/utils_test.py, line 264 at r2](https://reviewable.io/reviews/google/mobly/786#-MreFmZgBpkt0LfJn6oH:-MreFmZgBpkt0LfJn6oI:bo5d0u1) ([raw file](https://github.com/google/mobly/blob/14473d5817fd4553b3d5563ca809d1cf29fbaec9/tests/mobly/utils_test.py#L264)):*
> ```Python
>     time.sleep(0.01)
> 
>     utils.stop_standing_subprocess(mock_subprocess_a_popen)
> ```

why do you need to create a mock here? Can't you use subprocess_a?



_Code quote:_
```Python
mock_subprocess_a_popen
```

**Review by eric100lin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/786)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @booneng and @xpconanfan)

___
*[tests/mobly/utils_test.py, line 264 at r2](https://reviewable.io/reviews/google/mobly/786#-MreFmZgBpkt0LfJn6oH:-MreOkai3U6F-RzBmEGS:b-lh8tlt) ([raw file](https://github.com/google/mobly/blob/14473d5817fd4553b3d5563ca809d1cf29fbaec9/tests/mobly/utils_test.py#L264)):*
<details><summary><i>Previously, booneng (boon) wrote…</i></summary><blockquote>

why do you need to create a mock here? Can't you use subprocess_a?
</blockquote></details>

Because `utils.stop_standing_subprocess` accepts `subprocess.Popen` object but
we are creating processes with `multiprocessing.Process`.
These two are different and not compatible.

Here, we use mock to pass the PID into it and verify the `wait` is called.
This means `utils.stop_standing_subprocess` only kill the children of`subprocess_a`.

The `subprocess_a` keep running until all its children processes exit.
Therefore we can use `subprocess_a.join(timeout=1)` to verify all the children processes of `subprocess_a` already been killed.

**Review by booneng — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/786)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @xpconanfan)

**Review by booneng — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xpconanfan)

**Pull request merged**
