### PR TITLE
Don't try to use setpgrp.

### PR DESCRIPTION
**Pull request by adorokhine**
This functionality does not work on Windows, so use psutil instead.

Issue #151

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/153)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Should we create a project and track all the PRs that go in for win support?

**Comment by adorokhine** [comment]
What's the difference between a project and a tracking bug?

**Comment by xpconanfan** [comment]
A project can have multiple bugs and also serves as a progress tracker where you can see what's planned, what's ongoing, and what's done.

**Comment by xpconanfan** [comment]
Do we need to 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/utils.py, line 343 at r1](https://reviewable.io:443/reviews/google/mobly/153#-KfOpJizpyziX06Gfz9e:-KfOpJizpyziX06Gfz9f:bfdjz9s) ([raw file](https://github.com/google/mobly/blob/56a4a803e840483c1bbf0c2e7e8be0fc8e51f2cb/mobly/utils.py#L343)):*
> ```Python
>     process = psutil.Process(pid)
>     for child in process.children(recursive=True):
>         child.kill()
> ```

should there be a try...except...log here so we don't skip some child processes in the event of an exception?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153#-:-KfOpr5vZvUp1UzHF6rZ:bw9g5b1)*

**Comment by xpconanfan** [comment]
figure out a way to run unit tests on windows? travis doesn't support windows...

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153#-:-KfOqdFumigBJtP0aIpk:by0mssg)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[mobly/utils.py, line 343 at r1](https://reviewable.io:443/reviews/google/mobly/153#-KfOpJizpyziX06Gfz9e:-KfSfphLaXrDZlRfcY-w:b-896fix) ([raw file](https://github.com/google/mobly/blob/56a4a803e840483c1bbf0c2e7e8be0fc8e51f2cb/mobly/utils.py#L343)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should there be a try...except...log here so we don't skip some child processes in the event of an exception?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/utils.py, line 379 at r3](https://reviewable.io:443/reviews/google/mobly/153#-KfSxn6gC8YT4J8_JVmQ:-KfSxn6hK_pzAl9tFpJ6:b5t8dfd) ([raw file](https://github.com/google/mobly/blob/d07d4be9152d0357de8993d6f9838086b4c36f74/mobly/utils.py#L379)):*
> ```Python
>         success = False
>         logging.exception('Failed to kill standing subprocess %d', pid)
>     if not success:
> ```

This did not used to throw, now it does.
Pls check its caller to make sure it is properly handled. E.g. if this is used in teardown, we don't want to skip the rest of the teardown steps because of this.
Also need to update docstring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153)*

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/utils.py, line 379 at r3](https://reviewable.io:443/reviews/google/mobly/153#-KfSxn6gC8YT4J8_JVmQ:-KfT0c6SVwoOF2FKqEvp:bpnp4cm) ([raw file](https://github.com/google/mobly/blob/d07d4be9152d0357de8993d6f9838086b4c36f74/mobly/utils.py#L379)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This did not used to throw, now it does.
Pls check its caller to make sure it is properly handled. E.g. if this is used in teardown, we don't want to skip the rest of the teardown steps because of this.
Also need to update docstring.
</blockquote></details>

1. The only thing that used to be wrapped is PermissionError (which actually doesn't even exist on py2 so nothing was wrapped before on py2)
2. We don't have any wrapping in teardown currently as far as I can see. eg if tearing down sl4a fails, it will also bail out of the teardown process there too. Not sure why this is different?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153)*

**Comment by xpconanfan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/utils.py, line 379 at r3](https://reviewable.io:443/reviews/google/mobly/153#-KfSxn6gC8YT4J8_JVmQ:-KfT1QUAsxfD0va9cEmr:bl9l705) ([raw file](https://github.com/google/mobly/blob/d07d4be9152d0357de8993d6f9838086b4c36f74/mobly/utils.py#L379)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

1. The only thing that used to be wrapped is PermissionError (which actually doesn't even exist on py2 so nothing was wrapped before on py2)
2. We don't have any wrapping in teardown currently as far as I can see. eg if tearing down sl4a fails, it will also bail out of the teardown process there too. Not sure why this is different?
</blockquote></details>

Huh, I did not realize that. Maybe that's why tests die and leave adb ports behind....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153)*

**Comment by xpconanfan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/utils.py, line 379 at r3](https://reviewable.io:443/reviews/google/mobly/153#-KfSxn6gC8YT4J8_JVmQ:-KfT7UKJbTRwaLlTtC0q:bw9bjr6) ([raw file](https://github.com/google/mobly/blob/d07d4be9152d0357de8993d6f9838086b4c36f74/mobly/utils.py#L379)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Huh, I did not realize that. Maybe that's why tests die and leave adb ports behind....
</blockquote></details>

I uploaded a fix for that...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153#-:-KfT7ZB7rCR2TX6HSfAg:bnfp4nl)*

**Comment by adorokhine** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/153)*

**Pull request merged**
