### PR TITLE
Do not raise Error for already connected devices.

### PR DESCRIPTION
**Pull request by xpconanfan**
Also a few minor style fixes in `adb.py`.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/747)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/747)* status: all files reviewed, 2 unresolved discussions (waiting on @booneng and @xpconanfan)

___
*[tests/mobly/controllers/android_device_lib/adb_test.py, line 497 at r1](https://reviewable.io/reviews/google/mobly/747#-M_x1R1FCEGLe_xfNm8F:-M_x1R1FCEGLe_xfNm8G:b-1blyva) ([raw file](https://github.com/google/mobly/blob/c8eac45abbfb27f748cd4cc1e775f83dd6de007b/tests/mobly/controllers/android_device_lib/adb_test.py#L497)):*
> ```Python
>     out = adb.AdbProxy().connect(mock_address)
>     self.assertEqual('already connected to localhost:1234', out.decode('utf-8'))
> ```

Better to add some negative cases.
Like "failed to authenticate to XXX", "failed to connect to XXX", "reconnect failed: XXX":
https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/client/transport_local.cpp;drc=a5baef9adf403d11cefad18c034a4a143fa22b3d;l=127

**Review by xpconanfan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/747)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @booneng and @eric100lin)

___
*[mobly/controllers/android_device_lib/adb.py, line 364 at r1](https://reviewable.io/reviews/google/mobly/747#-M_x01cs-0QUZ_WL5JSZ:-M_xdAeW799x8siBlLm4:b-896fix) ([raw file](https://github.com/google/mobly/blob/c8eac45abbfb27f748cd4cc1e775f83dd6de007b/mobly/controllers/android_device_lib/adb.py#L364)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> not PATTERN_ADB_CONNECT_SUCCESS.match(stdout.decode('utf-8'))
> ```
I think it's better to use `is None` because `re.match` return None if the string does not match the pattern.
https://docs.python.org/3/library/re.html#re.match
</blockquote></details>

Done.
___
*[tests/mobly/controllers/android_device_lib/adb_test.py, line 497 at r1](https://reviewable.io/reviews/google/mobly/747#-M_x1R1FCEGLe_xfNm8F:-M_xdTVe79q-vl74oe9z:b53xnm0) ([raw file](https://github.com/google/mobly/blob/c8eac45abbfb27f748cd4cc1e775f83dd6de007b/tests/mobly/controllers/android_device_lib/adb_test.py#L497)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

Better to add some negative cases.
Like "failed to authenticate to XXX", "failed to connect to XXX", "reconnect failed: XXX":
https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/client/transport_local.cpp;drc=a5baef9adf403d11cefad18c034a4a143fa22b3d;l=127
</blockquote></details>

Already have a failed case. I don't think we need to iterate through all these messages.

**Review by booneng — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/747)* status: all files reviewed, 2 unresolved discussions (waiting on @eric100lin)

**Review by eric100lin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/mobly/747#-:-M_yiASD2U4bu0G_xPeT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xpconanfan)

**Pull request merged**
