### PR TITLE
Add continue_with_test_info to logcat service.

### PR DESCRIPTION
**Pull request by winterfroststrom**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/655)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Can this be closed now? :)

**Comment by winterfroststrom** [comment]
I mean there are 3 issues and https://github.com/google/mobly/pull/658 only fixes one of them...

**Comment by xianyuanjia** [comment]
Could you elaborate on what issues are yet to be addressed? As of #658, bugreports are fixed because logcat buffer is no longer being cleared. Logcats are written to a single file for the duration of the service, which fixes the issue of dangling files and reboots generating new files.

**Comment by winterfroststrom** [comment]
To be more clear, there are four issues:
1. logcat clears buffer causing on_fail bugreports to lose logcat (fixed by #658)
2. logcat restarting generates a new file (fixed by #658)
3. logcat and other services generate unnecessary files for tests that don't implement teardown_class  (difficult to fix)
4. logcat copies files unnecessarily (unfixable with #658)

1, 3, and 4 were the issues I was referring to, but considering that #658 makes them difficult to fix...
Fine I'll close this

**Pull request closed without merging**
