### PR TITLE
Fix error argument formatting which was leading to not callable TypeE…

### PR DESCRIPTION
**Pull request by dthkao**
…rror.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/455)

### CODE REVIEW

**Comment by winterfroststrom** [comment]
Wait, was this always wrong?

**Comment by winterfroststrom** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 155 at r1](https://reviewable.io/reviews/google/mobly/455#-LDrVn6aAguGx4ez8aEI:-LDrVn6aAguGx4ez8aEJ:b-shmzuy) ([raw file](https://github.com/google/mobly/blob/3612825dae0b73966a7529a33a33e343313cc6a2/mobly/controllers/android_device_lib/snippet_client.py#L155)):*
> ```Python
>             # Failed to connect to app, something went wrong.
>             raise jsonrpc_client_base.AppRestoreConnectionError(
>                 self._ad,
> ```

Add unit test for this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455)*

**Comment by dthkao** [comment]
For a LONG time.... since https://github.com/google/mobly/pull/336

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 155 at r1](https://reviewable.io/reviews/google/mobly/455#-LDrVn6aAguGx4ez8aEI:-LDrYaGA8mFjA-ib6qa_:b-y6kwn6) ([raw file](https://github.com/google/mobly/blob/3612825dae0b73966a7529a33a33e343313cc6a2/mobly/controllers/android_device_lib/snippet_client.py#L155)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Add unit test for this?
</blockquote></details>

We should, but now looking closer at this code TBH I don't even think this is a good approach -- we're swallowing whatever error came from connect which isn't at all get described in the docstring...

I'd prefer to let whatever exception occurred through. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455#-:-LDrWzix7gJ_MUJEuHRp:b-t9a9yu)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 155 at r1](https://reviewable.io/reviews/google/mobly/455#-LDrVn6aAguGx4ez8aEI:-LDtK2G88hbO8zCByvvM:b-s9dor7) ([raw file](https://github.com/google/mobly/blob/3612825dae0b73966a7529a33a33e343313cc6a2/mobly/controllers/android_device_lib/snippet_client.py#L155)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

We should, but now looking closer at this code TBH I don't even think this is a good approach -- we're swallowing whatever error came from connect which isn't at all get described in the docstring...

I'd prefer to let whatever exception occurred through. Thoughts?
</blockquote></details>

Yeah, hiding errors is bad, but that's potentially API breaking
because people might have logic that expects that exact exception type.
So, I'm against just raising it.
Instead, can we just extend the error message with something like "because of exception ..." ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 155 at r1](https://reviewable.io/reviews/google/mobly/455#-LDrVn6aAguGx4ez8aEI:-LDtKlab2dPYbcpzHSo8:b-ybtc4q) ([raw file](https://github.com/google/mobly/blob/3612825dae0b73966a7529a33a33e343313cc6a2/mobly/controllers/android_device_lib/snippet_client.py#L155)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Yeah, hiding errors is bad, but that's potentially API breaking
because people might have logic that expects that exact exception type.
So, I'm against just raising it.
Instead, can we just extend the error message with something like "because of exception ..." ?


</blockquote></details>

Wait, I'm dumb.
This has been broken for everyone, so the API doesn't matter.

In that case, it's a question of whether or not package, host_port, device_port are valuable info.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455)*

**Comment by xpconanfan** [comment]
Can we add a test for the broken code path?

**Comment by dthkao** [comment]
Ang, please see previous comments. We're waiting on a decision w.r.t. swallowing the underlying error (or not). Mind sharing the rationale behind catching everything?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455#-:-LEAdLAS72x2C_dMyGZ0:bwha08)*

**Comment by dthkao** [comment]
BTW, I guess it's worth noting that py3 implicitly handles exception chaining so we're only losing info in py2.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455#-:-LEAeqt7En3qyFOyjaSC:b-67lt3k)*

**Comment by dthkao** [comment]
Tests added.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455#-:-LEAxprA43e6WgNWyWz4:b-wj4ea6)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455#-:-LEBw63DDysl8aJhiD24:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 154 at r2](https://reviewable.io/reviews/google/mobly/455#-LEBwIcG7soZTd2-A9Y9:-LEBwIcH894R-LeZwVWv:bms5bo5) ([raw file](https://github.com/google/mobly/blob/bcd2b5ec8266ceb6c0768e3d79450a0e3c9698e2/mobly/controllers/android_device_lib/snippet_client.py#L154)):*
> ```Python
>         except:
>             # Log the original error and raise AppRestoreConnectionError.
>             self.log.exception('Failed to connect to app!')
> ```

"Failed to reconnect"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455)*

**Comment by winterfroststrom** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/455#-:-LECAwDh9-CVd3Iq-PEE:bnfp4nl)*

**Pull request merged**
