### PR TITLE
Handle v1 snippets on phones that print junk to instrumentation.

### LINKED ISSUE #224: `snippet_shell` is broken for python3
```
$ snippet_shell.py --mbs
s.logINFO:root:[AndroidDevice|HT67K0300103] Launching snippet apk com.google.android.mobly.snippet.bundled with protocol v1
VTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/snippet_shell.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 84, in <module>
    SnippetShell(package).main(args.serial)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 88, in main
    self.start_console()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 73, in start_console
    self._start_services(console_env)
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 43, in _start_services
    self._ad.load_snippet(name='snippet', package=self._package)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 646, in load_snippet
    client.start_app_and_connect()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/snippet_client.py", line 112, in start_app_and_connect
    line)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
```

### LINKED ISSUE #226: Snippet crashes on phones that print extra instrumentation output.
Some phones print extra information prior to instrumentation output. On such phones, the snippet crashes.

### PR DESCRIPTION
**Pull request by adorokhine**
Comes with lots of new unit tests and py3 fixes.

Fixes #226.
Fixes #224.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/227)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 189 at r1](https://reviewable.io:443/reviews/google/mobly/227#-KlblfMBHGUVsYsb35BX:-KlblfMC2k4pyw9i44TT:b879d2f) ([raw file](https://github.com/google/mobly/blob/3606e54d198968fa807da58991817244a73b1fb5/mobly/controllers/android_device_lib/snippet_client.py#L189)):*
> ```Python
>         self._adb.forward(
>             ['tcp:%d' % self.host_port,
>              'tcp:%d' % self.device_port])
> ```

this was the autoformatter?

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 221 at r1](https://reviewable.io:443/reviews/google/mobly/227#-KlblqEfvw26Ok0DC1qe:-KlblqEfvw26Ok0DC1qf:botn7lo) ([raw file](https://github.com/google/mobly/blob/3606e54d198968fa807da58991817244a73b1fb5/mobly/controllers/android_device_lib/snippet_client.py#L221)):*
> ```Python
> 
>     def _read_line(self):
>         while True:
> ```

what if we never get an acceptable line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/227)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 189 at r1](https://reviewable.io:443/reviews/google/mobly/227#-KlblfMBHGUVsYsb35BX:-Klbm9igg1oyi650B6wP:b2nhtan) ([raw file](https://github.com/google/mobly/blob/3606e54d198968fa807da58991817244a73b1fb5/mobly/controllers/android_device_lib/snippet_client.py#L189)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

this was the autoformatter?
</blockquote></details>

Yup

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 221 at r1](https://reviewable.io:443/reviews/google/mobly/227#-KlblqEfvw26Ok0DC1qe:-KlboFdOyj5NPihjPUAj:b-896fix) ([raw file](https://github.com/google/mobly/blob/3606e54d198968fa807da58991817244a73b1fb5/mobly/controllers/android_device_lib/snippet_client.py#L221)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

what if we never get an acceptable line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/227)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/227#-:-Klbp4-Zgil5GlAXMhnK:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 227 at r2](https://reviewable.io:443/reviews/google/mobly/227#-KldwJjmq90v1vEAzqiZ:-KldwJjnZt2xIGaxbdo0:bn32ide) ([raw file](https://github.com/google/mobly/blob/f618e1ff6ce4ee08d35e28c5b5dfb9192d347e5c/mobly/controllers/android_device_lib/snippet_client.py#L227)):*
> ```Python
>                     'Unexpected EOF waiting for app to start')
>             line = line.strip()
>             if (line.startswith('INSTRUMENTATION_RESULT:') or
> ```

So this readline function is really only looking for a couple of particular lines?
Could we rename the function to reflect this and add docstring?
`_read_line` sounds like a generic function that reads any line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/227)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 226 at r2](https://reviewable.io:443/reviews/google/mobly/227#-KldxLWGMgBkeXLklRXg:-KldxLWGMgBkeXLklRXh:b-3b3kof) ([raw file](https://github.com/google/mobly/blob/f618e1ff6ce4ee08d35e28c5b5dfb9192d347e5c/mobly/controllers/android_device_lib/snippet_client.py#L226)):*
> ```Python
>                 raise jsonrpc_client_base.AppStartError(
>                     'Unexpected EOF waiting for app to start')
>             line = line.strip()
> ```

Shouldn't we strip before we do `not line` check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/227)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 226 at r2](https://reviewable.io:443/reviews/google/mobly/227#-KldxLWGMgBkeXLklRXg:-Kle85GDasmQERQlc-4K:bwju1v5) ([raw file](https://github.com/google/mobly/blob/f618e1ff6ce4ee08d35e28c5b5dfb9192d347e5c/mobly/controllers/android_device_lib/snippet_client.py#L226)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Shouldn't we strip before we do `not line` check?
</blockquote></details>

Actually we can't, because readline() returns '' for EOF and '\n' for regular empty lines. So if we strip before the 'not line' check, we would consider any empty line in the output to be the same as EOF. Added a comment to this effect.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 227 at r2](https://reviewable.io:443/reviews/google/mobly/227#-KldwJjmq90v1vEAzqiZ:-Kle84qz-_723Td_9_EB:b-896fix) ([raw file](https://github.com/google/mobly/blob/f618e1ff6ce4ee08d35e28c5b5dfb9192d347e5c/mobly/controllers/android_device_lib/snippet_client.py#L227)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

So this readline function is really only looking for a couple of particular lines?
Could we rename the function to reflect this and add docstring?
`_read_line` sounds like a generic function that reads any line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/227)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/227#-:-KleGSHQZjebDqg7QOzd:bnfp4nl)*

**Pull request merged**
