### PR TITLE
Mobly Release 1.5.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/250)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r2](https://reviewable.io:443/reviews/google/mobly/250#-KonHBD3h4UdyyD6iQnK:-KonHBD3h4UdyyD6iQnL:b4l2y87) ([raw file](https://github.com/google/mobly/blob/87d275e1e6549cc1ad2bba32172efb71893f2021/CHANGELOG.md#L4)):*
> ```Markdown
> 
> ### 1.5: New Snippet Startup Protocol
>   * Fixes critical bugs in 1.4.1
> ```

This is what I have in draft for 1.5:

```
New
* Support the new launch and connection mechanism in Snippet Lib 1.2.
* Support temporarily disconnecting (without rebooting) Android devices from USB in a test, useful for power measurement.

Fix
* A bug in generate_tests that prevents it to be called when wrapped in other functions.
* A bug that exposed Mobly internal controller registry to tests.

Deprecate
* Old generated tests (run_generated_tests)
* Old snippet launch protocol (V0)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/250)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r2](https://reviewable.io:443/reviews/google/mobly/250#-KonHMmpc0mIxICjeBg4:-KonHMmpc0mIxICjeBg5:bt2977u) ([raw file](https://github.com/google/mobly/blob/87d275e1e6549cc1ad2bba32172efb71893f2021/CHANGELOG.md#L3)):*
> ```Markdown
> # Mobly release history
> 
> ### 1.5: New Snippet Startup Protocol
> ```

Should these be `##` instead of `###`, or is `##` reserved for something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/250)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r2](https://reviewable.io:443/reviews/google/mobly/250#-KonHMmpc0mIxICjeBg4:-KonJaM423k-FP5FHSxk:b-896fix) ([raw file](https://github.com/google/mobly/blob/87d275e1e6549cc1ad2bba32172efb71893f2021/CHANGELOG.md#L3)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Should these be `##` instead of `###`, or is `##` reserved for something else?
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 4 at r2](https://reviewable.io:443/reviews/google/mobly/250#-KonHBD3h4UdyyD6iQnK:-KonJO2uFaRpX41sLEX7:b-896fix) ([raw file](https://github.com/google/mobly/blob/87d275e1e6549cc1ad2bba32172efb71893f2021/CHANGELOG.md#L4)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This is what I have in draft for 1.5:

```
New
* Support the new launch and connection mechanism in Snippet Lib 1.2.
* Support temporarily disconnecting (without rebooting) Android devices from USB in a test, useful for power measurement.

Fix
* A bug in generate_tests that prevents it to be called when wrapped in other functions.
* A bug that exposed Mobly internal controller registry to tests.

Deprecate
* Old generated tests (run_generated_tests)
* Old snippet launch protocol (V0)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/250)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r3](https://reviewable.io:443/reviews/google/mobly/250#-KonO-y7uGOwmdKEXl45:-KonO-y7uGOwmdKEXl46:b-1iu66q) ([raw file](https://github.com/google/mobly/blob/638d4193aa1a08b2de914856fd268b67bb175e0c/CHANGELOG.md#L4)):*
> ```Markdown
> 
> ## 1.5: New Snippet Startup Protocol
>   * Fixes critical bugs from 1.4.1
> ```

Still seeing the old description in patch 3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/250)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r3](https://reviewable.io:443/reviews/google/mobly/250#-KonO-y7uGOwmdKEXl45:-KonV9jIMNBOzM7LDUpl:b-smn2pw) ([raw file](https://github.com/google/mobly/blob/638d4193aa1a08b2de914856fd268b67bb175e0c/CHANGELOG.md#L4)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Still seeing the old description in patch 3.
</blockquote></details>

I've taken all your points and moved them into the releases where they actually appear so that the changelog is accurate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/250)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 4 at r3](https://reviewable.io:443/reviews/google/mobly/250#-KonO-y7uGOwmdKEXl45:-KonYsyYlp9U46qQB_Sj:b-fvbyf5) ([raw file](https://github.com/google/mobly/blob/638d4193aa1a08b2de914856fd268b67bb175e0c/CHANGELOG.md#L4)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I've taken all your points and moved them into the releases where they actually appear so that the changelog is accurate.
</blockquote></details>

K, how about moving "critical bug fix" line to the end?

---

*[CHANGELOG.md, line 22 at r3](https://reviewable.io:443/reviews/google/mobly/250#-KonYnPJ7o4L3iU_5y2L:-KonYnPJ7o4L3iU_5y2M:bgltu54) ([raw file](https://github.com/google/mobly/blob/638d4193aa1a08b2de914856fd268b67bb175e0c/CHANGELOG.md#L22)):*
> ```Markdown
>   * Old snippet launch protocol (V0)
> 
>   Warning: This release has multiple issues; please use 1.5.
> ```

Let's move this to the first line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/250)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 4 at r3](https://reviewable.io:443/reviews/google/mobly/250#-KonO-y7uGOwmdKEXl45:-Koo60f8uyjuU0QoYawg:b-896fix) ([raw file](https://github.com/google/mobly/blob/638d4193aa1a08b2de914856fd268b67bb175e0c/CHANGELOG.md#L4)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

K, how about moving "critical bug fix" line to the end?
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 22 at r3](https://reviewable.io:443/reviews/google/mobly/250#-KonYnPJ7o4L3iU_5y2L:-Koo61ilmwoIg-P76CoK:b-896fix) ([raw file](https://github.com/google/mobly/blob/638d4193aa1a08b2de914856fd268b67bb175e0c/CHANGELOG.md#L22)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Let's move this to the first line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/250)*

**Pull request merged**
