### PR TITLE
Disable the blacklist on hidden apis for sl4a/snippets

### PR DESCRIPTION
**Pull request by mswest46**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/427)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[mobly/controllers/android_device.py, line 1202 at r1](https://beta.reviewable.io/reviews/google/mobly/427#-L9SHpiC6AG_XBiZbI-8:-L9SHpiC6AG_XBiZbI-9:b-7q7363) ([raw file](https://github.com/google/mobly/blob/c8dd270f3de97366641a36e657a767d056b9013f/mobly/controllers/android_device.py#L1202)):*
> ```Python
>             self.adb.reboot()
> 
>     def _is_at_least_P(self):
> ```

i'm hesitant in making a method at `AndroidDevice` level to specifically check for builds newer than P.
Can you inline this logic in `_disable_hidden_api_blacklist` to minimize the impact since nothing else needs this right now?

---

*[mobly/controllers/android_device.py, line 1210 at r1](https://beta.reviewable.io/reviews/google/mobly/427#-L9SIIWkDdZYNtg-ro_p:-L9SIIWkDdZYNtg-ro_q:b-x1gzya) ([raw file](https://github.com/google/mobly/blob/c8dd270f3de97366641a36e657a767d056b9013f/mobly/controllers/android_device.py#L1210)):*
> ```Python
>         return False
> 
>     def _disable_hidden_api_blacklist(self):
> ```

can this be moved down to `base_snippet_client`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/427)*

**Comment by mswest46** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 122 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9STNr26EB5JcfLPGq0:-L9SXtWn330EBQVLRK6U:b-896fix) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L122)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

don't create extra attr when you can directly  call self._ad.adb
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 325 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9STwyE-oJki1dHHpKR:-L9SXwmk8haojxmfXpAk:b-mjibm5) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L325)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`>=`?
</blockquote></details>

A device running an O release build will report 'REL', not 'O', which would break >= logic. So == makes more sense.

---

*[tests/lib/mock_android_device.py, line 91 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9STpw75WGFos-ONfj1:-L9SYFdB1gRoWtu6QY4x:bw552xk) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/tests/lib/mock_android_device.py#L91)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

is this still needed?
</blockquote></details>

Whoops, thanks.

---

*[tests/mobly/controllers/android_device_lib/sl4a_client_test.py, line 38 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9STawl4BcexKdn1Nia:-L9SYnZM1TDxqz6Tm2eV:b-896fix) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/tests/mobly/controllers/android_device_lib/sl4a_client_test.py#L38)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

use single quote
</blockquote></details>

Done.

---

*[tests/mobly/controllers/android_device_lib/sl4a_client_test.py, line 40 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9ST_eQ2hH4QSjcZ8Te:-L9SYojR14u8wL962okV:b-896fix) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/tests/mobly/controllers/android_device_lib/sl4a_client_test.py#L40)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

can you have this return > P so we can hit the new code path in tests? Same for other places
</blockquote></details>

Done.

---

*[tests/mobly/controllers/android_device_lib/snippet_client_test.py, line 59 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9STgif28EO45rYuC3y:-L9SYpt4APqK-wMxEr-m:b-896fix) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/tests/mobly/controllers/android_device_lib/snippet_client_test.py#L59)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

single quotes
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/427)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 325 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9STwyE-oJki1dHHpKR:-L9fnp6i3ec4gj0RTe2Z:b-ndxbl7) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L325)):*
<details><summary><i>Previously, mswest46 (Michael West) wrote…</i></summary><blockquote>

A device running an O release build will report 'REL', not 'O', which would break >= logic. So == makes more sense.
</blockquote></details>

Sounds like we should handle the version_codename and sdk version number in separate `if` blocks.

Also the current logic is not scalable as it requires us to manually add letters for every future android release.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/427)*

**Comment by mswest46** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 325 at r3](https://beta.reviewable.io/reviews/google/mobly/427#-L9STwyE-oJki1dHHpKR:-L9gEYRnEUPSqm0Sh3Vr:b-ixtcix) ([raw file](https://github.com/google/mobly/blob/ec971304480297f89bfc728c83d2343e90757e77/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L325)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Sounds like we should handle the version_codename and sdk version number in separate `if` blocks.

Also the current logic is not scalable as it requires us to manually add letters for every future android release.
</blockquote></details>

Correct me if I'm wrong, but any build running release version P or greater will have sdk version at least 28, so no need to check for any potential letters >P. The check for version_codename is only for devices running a P build that is still in development, and so reports sdk version as 27. But I could well be wrong, I don't have a great source for that claim :) 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/427)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/427#-:-LAEPwF11uskFvqJNyvN:bnfp4nl)*

**Pull request merged**
