### PR TITLE
Minor fixes in base_test.

### PR DESCRIPTION
**Pull request by xpconanfan**
* Remove unused import
* Correct an inconsistency between docstring and code behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/331)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/base_test_test.py, line 24 at r1](https://reviewable.io:443/reviews/google/mobly/331#-Kv19rrMPTF0XXuEYC3Z:-Kv19rrMPTF0XXuEYC3_:bimtxml) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/tests/mobly/base_test_test.py#L24)):*
> ```Python
> from mobly import utils as mobly_utils
> 
> from tests.lib import utils
> ```

A part of me wants to switch around which module is aliased.... Since actual code uses "from mobly import utils", can we do "from tests.lib import utils as test_utils"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/base_test_test.py, line 24 at r1](https://reviewable.io:443/reviews/google/mobly/331#-Kv19rrMPTF0XXuEYC3Z:-Kv1Adf5qC4I8kR_O829:bye0v9x) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/tests/mobly/base_test_test.py#L24)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

A part of me wants to switch around which module is aliased.... Since actual code uses "from mobly import utils", can we do "from tests.lib import utils as test_utils"?
</blockquote></details>

`from tests.lib import utils` is in a lot of test modules, `mobly.utils` is not.
So this is the consistent way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by kdart** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvEVDVjRxYkUPlgLB04:badsqe1) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
> ```Python
>         self._assert_function_name_in_stack('setup_generated_tests')
>         for args in arg_sets:
>             test_name = name_func(*args)[:utils.MAX_FILENAME_LEN]
> ```

Perhaps a function to chop the left side? Or the middle? The right side is usually the most specific and useful identifier. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvEWR87qI1Gi-OP0dIB:bbnehgp) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

Perhaps a function to chop the left side? Or the middle? The right side is usually the most specific and useful identifier. 
</blockquote></details>

true. but we can't chop left side as it's the prefix "test_".
perhaps we should just raise an exception if it's too long.

or is it worth checking the name length at all?
the check was mostly for systems that have restriction on file name length.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by kdart** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvV7Pv0Je6lEPRaHdzl:b-z5kafz) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

true. but we can't chop left side as it's the prefix "test_".
perhaps we should just raise an exception if it's too long.

or is it worth checking the name length at all?
the check was mostly for systems that have restriction on file name length.
</blockquote></details>

I think any modern system has a pretty long file name length. Maybe skip it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvV7ye_FFrIpu0nDv8l:b-hvo3h9) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

I think any modern system has a pretty long file name length. Maybe skip it?
</blockquote></details>

It seems to be 255 on linux.
I did encounter some tests going too long causing the file names to be truncated in some cases.
is there a way to check a system's max supported filename len?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by kdart** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvVA06utifDEhmWcZG0:bi49l1y) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It seems to be 255 on linux.
I did encounter some tests going too long causing the file names to be truncated in some cases.
is there a way to check a system's max supported filename len?
</blockquote></details>

It depends on the file system, but yes it's 255 file name, and 4096 max path length. But why would a test name be that long? 

But it's not too hard to write a "middle chopper". I'd prefer that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvW03IpP1Eu7DZ0-FBJ:b1s3sov) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

It depends on the file system, but yes it's 255 file name, and 4096 max path length. But why would a test name be that long? 

But it's not too hard to write a "middle chopper". I'd prefer that. 

</blockquote></details>

randomly cut off parts of the name from middle doesn't make sense either

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by kdart** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvW8Tt3xBcrCMsKugiH:b-bvy2n3) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

randomly cut off parts of the name from middle doesn't make sense either
</blockquote></details>

But if the name is already 255 chars we won't miss a few. ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 438 at r1](https://reviewable.io:443/reviews/google/mobly/331#-KvEVDVjRxYkUPlgLB03:-KvZpeKR84-N8VxztZTv:b-yp93dz) ([raw file](https://github.com/google/mobly/blob/cd22b63134f039fbd9088822d36df2634eacb47a/mobly/base_test.py#L438)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

But if the name is already 255 chars we won't miss a few. ;-)
</blockquote></details>

Removed the comment instead.
Seems more appropriate to guard against file name when actually creating the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331)*

**Comment by kdart** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/331#-:-KviP1w_RGreLBnNnXCX:bnfp4nl)*

**Pull request merged**
