### PR TITLE
Fix start_app timeout mechanism which assumes _is_app_running() retur…

### PR DESCRIPTION
**Pull request by dthkao**
…ns immediately.

Previously, this was looping for 
wait_time x (1+_SOCKET_CONNECTION_TIMEOUT+_SOCKET_READ_TIMEOUT) seconds
instead of
wait_time x (1) seconds

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/186)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 178 at r1](https://reviewable.io:443/reviews/google/mobly/186#-KhyTTS_ar0GORcGV-tx:-KhyTTSaVxXS7ihUFviE:blnlwgw) ([raw file](https://github.com/google/mobly/blob/84afd1b58179a368482efb3541e90aba7c4ab0f1/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L178)):*
> ```Python
> 
>         Args:
>             wait_time: float, The time to wait for the app to come up before
> ```

perhaps we should change the comment here to say the unit is "second", since the sleep is 1s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/186)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 178 at r1](https://reviewable.io:443/reviews/google/mobly/186#-KhyTTS_ar0GORcGV-tx:-KhyTbKgb8cypQLlsTRi:bff9ezi) ([raw file](https://github.com/google/mobly/blob/84afd1b58179a368482efb3541e90aba7c4ab0f1/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L178)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

perhaps we should change the comment here to say the unit is "second", since the sleep is 1s.
</blockquote></details>

And say this is an int instead of float

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/186)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 178 at r1](https://reviewable.io:443/reviews/google/mobly/186#-KhyTTS_ar0GORcGV-tx:-Khye6PC398UFb_QMHS9:b-896fix) ([raw file](https://github.com/google/mobly/blob/84afd1b58179a368482efb3541e90aba7c4ab0f1/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L178)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

And say this is an int instead of float
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/186)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 178 at r1](https://reviewable.io:443/reviews/google/mobly/186#-KhyTTS_ar0GORcGV-tx:-KhyeUIJFxnfWX5S29s3:b-h06bl) ([raw file](https://github.com/google/mobly/blob/84afd1b58179a368482efb3541e90aba7c4ab0f1/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L178)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why the `*`?
I think we are ok without the "minimum".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/186)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 178 at r1](https://reviewable.io:443/reviews/google/mobly/186#-KhyTTS_ar0GORcGV-tx:-Khyi_Apj50SmC_Ep1xq:b-896fix) ([raw file](https://github.com/google/mobly/blob/84afd1b58179a368482efb3541e90aba7c4ab0f1/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L178)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why the `*`?
I think we are ok without the "minimum".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/186)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/186#-:-KhyjnfinkliHsxZLBIK:bnfp4nl)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/186#-:-KhzXCNOniXtta6pO7Yo:bnfp4nl)*

**Pull request merged**
