### PR TITLE
Generated tests 2.0.

### PR DESCRIPTION
**Pull request by xpconanfan**
* Simplified and more concise usage.
* Generated test cases can now be selected via --test_case cli arg.

Related #83 

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/197)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 152 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQUzwzgYHO8cCFPVE:-KjHQUzwzgYHO8cCFPVF:b-u837g4) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L152)):*
> ```Python
>                                 'configuration, continue.', name)
> 
>     def pre_setup(self):
> ```

why not be specific and call this "setup_generated_tests"?

On more of a design level, are we not going with a decorator approach?

---

*[mobly/base_test.py, line 425 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQeNGz_jdw0tw0y3K:-KjHQeNGz_jdw0tw0y3L:bie500r) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L425)):*
> ```Python
>         for args in arg_sets:
>             test_name = name_func(*args)
>             if not test_name.startswith('test_'):
> ```

did you want to add the verifier for test case name format here? or are spaces ok?

---

*[mobly/base_test.py, line 445 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHR4v4KmKd2Z8NrFCk:-KjHR4v4KmKd2Z8NrFCl:b-lg3v88) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L445)):*
> ```Python
>         """Runs generated test cases.
> 
>         !DEPRECATED! Use self.generate_tests instead.
> ```

can we add a log.warning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 152 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQUzwzgYHO8cCFPVE:-KjHT6uZlg-QYG3tDE9B:b-4eax0j) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L152)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

why not be specific and call this "setup_generated_tests"?

On more of a design level, are we not going with a decorator approach?
</blockquote></details>

Because we could potentially use this for other things in the future.
I don't want to name an entire new phase after generated tests.

I don't see how could decorator help here. Can you elaborate?

---

*[mobly/base_test.py, line 425 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQeNGz_jdw0tw0y3K:-KjHTMMxyswK4F3TqyzL:b7sgd88) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L425)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

did you want to add the verifier for test case name format here? or are spaces ok?
</blockquote></details>

That is an issue I want to address in a separate PR with a more generic solution that also applies to other places that need test name validation like `config_parser`.

---

*[mobly/base_test.py, line 445 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHR4v4KmKd2Z8NrFCk:-KjHTdx5y_0iodT_Uc80:b-y598pt) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L445)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

can we add a log.warning?
</blockquote></details>

I checked the usage, seems like we could remove old code paths for good?
I want to do the removal in a follow up PR to keep this one small though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 152 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQUzwzgYHO8cCFPVE:-KjHUYU1sRm8JROgco3e:bku6fno) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L152)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Because we could potentially use this for other things in the future.
I don't want to name an entire new phase after generated tests.

I don't see how could decorator help here. Can you elaborate?
</blockquote></details>

My concern is ambiguity between pre_setup and setup_class. In order to get args for some generated tests we'd need to move a lot of the logic from setup_class to pre_setup anyway. Is there any reason the try loops for setup_class can't just be pushed ahead of fetching the tests list?

For a decorator for test functions, there are some nice points in usage. In stead of an explicit call generate tests, you could use the decorator to mark which test methods generate tests (as is done already), and if setup_class occurs before calling fetching test names, then in the reflection in _get_all_test_names we can have the logic to generate test_names (basically what's inside generate_tests at the moment).

Usage could be
@generated_test(name_function, arg_sets)
def test_do_stuff(self):
    # test logic

---

*[mobly/base_test.py, line 425 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQeNGz_jdw0tw0y3K:-KjHvCZNzd4DIIZjhLbU:bb7ohn6) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L425)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

That is an issue I want to address in a separate PR with a more generic solution that also applies to other places that need test name validation like `config_parser`.
</blockquote></details>

sgtm

---

*[mobly/base_test.py, line 445 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHR4v4KmKd2Z8NrFCk:-KjHvG-LLGTtfPmLYVoH:b-do2ynt) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L445)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I checked the usage, seems like we could remove old code paths for good?
I want to do the removal in a follow up PR to keep this one small though.
</blockquote></details>

What about external users? How about adding the log.warning and keeping it there for at least one full release before removal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 152 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQUzwzgYHO8cCFPVE:-KjJM1fkegwin5jY0dc5:b-g0rq1j) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L152)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

My concern is ambiguity between pre_setup and setup_class. In order to get args for some generated tests we'd need to move a lot of the logic from setup_class to pre_setup anyway. Is there any reason the try loops for setup_class can't just be pushed ahead of fetching the tests list?

For a decorator for test functions, there are some nice points in usage. In stead of an explicit call generate tests, you could use the decorator to mark which test methods generate tests (as is done already), and if setup_class occurs before calling fetching test names, then in the reflection in _get_all_test_names we can have the logic to generate test_names (basically what's inside generate_tests at the moment).

Usage could be
@generated_test(name_function, arg_sets)
def test_do_stuff(self):
    # test logic


</blockquote></details>

Decorator does not work well for this.

People may need to write some code to create the arg_sets, e.g. a list comprehension with string formatting.
This code needs to be executed somewhere, before setup kicks off, to generate new tests.
Decorator does not provide such a venue.

The order of setup_class affects how the record is tallied, changing its order requires a lot of changes.
setup_class is also the place users register controllers today, whereas all we want is to have a pre-process that decides what tests there are.

This is actually a precursor to be able to list all the tests in a test class, which is required for CTS/GTS integration. If generate_tests is mixed into setup_class, it would be impossible to do list tests without also initializing all the controllers.

Overall, I chose this approach because it is less invasive to the current test execution flow, and leaves room for future expansion.

---

*[mobly/base_test.py, line 445 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHR4v4KmKd2Z8NrFCk:-KjJO7tltyjaK-wHYrMa:bcuzqtu) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L445)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

What about external users? How about adding the log.warning and keeping it there for at least one full release before removal?
</blockquote></details>

Added a warning line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 152 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQUzwzgYHO8cCFPVE:-KjK57MLUqk1ZTwGKp1b:b-6n3u8z) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L152)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Decorator does not work well for this.

People may need to write some code to create the arg_sets, e.g. a list comprehension with string formatting.
This code needs to be executed somewhere, before setup kicks off, to generate new tests.
Decorator does not provide such a venue.

The order of setup_class affects how the record is tallied, changing its order requires a lot of changes.
setup_class is also the place users register controllers today, whereas all we want is to have a pre-process that decides what tests there are.

This is actually a precursor to be able to list all the tests in a test class, which is required for CTS/GTS integration. If generate_tests is mixed into setup_class, it would be impossible to do list tests without also initializing all the controllers.

Overall, I chose this approach because it is less invasive to the current test execution flow, and leaves room for future expansion.
</blockquote></details>

-- You can do that with a decorator still, although if you need to access instance attributes it's a little more work. I think it's worth considering the API from how a user would use it both in writing the test and is specifying it from a command/test suite. 

"This is actually a precursor to be able to list all the tests in a test class, which is required for CTS/GTS integration. If generate_tests is mixed into setup_class, it would be impossible to do list tests without also initializing all the controllers."

-- Then let's be explicit and give it a non-ambiguous name. "pre_setup" means pre-what? 

'Overall, I chose this approach because it is less invasive to the current test execution flow, and leaves room for future expansion."

-- sounds like yagni to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 152 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQUzwzgYHO8cCFPVE:-KjK6MV5wBoUWOlszPpl:ba6tgo8) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L152)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

-- You can do that with a decorator still, although if you need to access instance attributes it's a little more work. I think it's worth considering the API from how a user would use it both in writing the test and is specifying it from a command/test suite. 

"This is actually a precursor to be able to list all the tests in a test class, which is required for CTS/GTS integration. If generate_tests is mixed into setup_class, it would be impossible to do list tests without also initializing all the controllers."

-- Then let's be explicit and give it a non-ambiguous name. "pre_setup" means pre-what? 

'Overall, I chose this approach because it is less invasive to the current test execution flow, and leaves room for future expansion."

-- sounds like yagni to me.
</blockquote></details>

It seems more cumbersome for users to try to fit the logic that reads user param and output the arg sets into a decorator arg. Could you give an example on what you have in mind for decorator?

If the problem is with the name, then we can name it better.

Why is choosing a less invasive approach yagni? We are talking to CTS/GTS right now for integration, so we definitely need it. I'm not sure what you mean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 152 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQUzwzgYHO8cCFPVE:-KjiUdMuL1nxw8ofk-ab:b-jn5s6n) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L152)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It seems more cumbersome for users to try to fit the logic that reads user param and output the arg sets into a decorator arg. Could you give an example on what you have in mind for decorator?

If the problem is with the name, then we can name it better.

Why is choosing a less invasive approach yagni? We are talking to CTS/GTS right now for integration, so we definitely need it. I'm not sure what you mean.
</blockquote></details>

Discussed offline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 425 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQeNGz_jdw0tw0y3K:-Kjla_k6vHMONNLnV2-z:b-26vcu2) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L425)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

We have tests named 'Call TMobile to Sprint (5s call/5s hold)`. This check would make that name invalid. Would it be possible to avoid doing partial validation in this CL until we can fully discuss this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/base_test.py, line 425 at r1](https://reviewable.io:443/reviews/google/mobly/197#-KjHQeNGz_jdw0tw0y3K:-KjnO6Ps69J_Txg2aFpy:b-896fix) ([raw file](https://github.com/google/mobly/blob/0a179964b1992b6583e8fc3fcce673e6511339b7/mobly/base_test.py#L425)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

We have tests named 'Call TMobile to Sprint (5s call/5s hold)`. This check would make that name invalid. Would it be possible to avoid doing partial validation in this CL until we can fully discuss this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197)*

**Comment by adorokhine** [comment]
:lgtm: Looks good! Mind waiting for David's approval too?

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197#-:-KjoX66gRfQ2AWt8-RQk:b-y8akqh)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/197#-:-KjtAn-fx5Y1GbtZub2K:bnfp4nl)*

**Pull request merged**
