### PR TITLE
Mobly Release 1.6.1

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/319)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r1](https://reviewable.io:443/reviews/google/mobly/319#-KsA2B4TnoqP29Qp7mrn:-KsA2B4TnoqP29Qp7mro:b-ejjxyp) ([raw file](https://github.com/google/mobly/blob/3df5ba5c2a343b33461b83818e7408d241c6f884/CHANGELOG.md#L4)):*
> ```Markdown
> 
> 
> ## 1.6.1: New Output
> ```

Can we have an entry for 1.6 still? This seems confusing (missing major release version)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/319)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r1](https://reviewable.io:443/reviews/google/mobly/319#-KsA2B4TnoqP29Qp7mrn:-KsA2TRHvnXb90lfgk9k:b-ws04v7) ([raw file](https://github.com/google/mobly/blob/3df5ba5c2a343b33461b83818e7408d241c6f884/CHANGELOG.md#L4)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Can we have an entry for 1.6 still? This seems confusing (missing major release version)
</blockquote></details>

No we can't because PyPI doesn't let us.
And PyPI number should match changelog and github number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/319)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r1](https://reviewable.io:443/reviews/google/mobly/319#-KsA2B4TnoqP29Qp7mrn:-KsA3xPAiY0vFNkg4PI5:byu5dmt) ([raw file](https://github.com/google/mobly/blob/3df5ba5c2a343b33461b83818e7408d241c6f884/CHANGELOG.md#L4)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

No we can't because PyPI doesn't let us.
And PyPI number should match changelog and github number.
</blockquote></details>

Sad phantom release. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/319#-:-KsA40hG_p-27iiJdKD9:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r1](https://reviewable.io:443/reviews/google/mobly/319#-KsA2B4TnoqP29Qp7mrn:-KsA4u5E-VQIiS1n4qpA:b32vhv) ([raw file](https://github.com/google/mobly/blob/3df5ba5c2a343b33461b83818e7408d241c6f884/CHANGELOG.md#L4)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Sad phantom release. :(
</blockquote></details>

:(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/319)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/319)*

**Pull request merged**
