### PR TITLE
Adding sphinx documentation system.

### PR DESCRIPTION
**Pull request by yusufm**
Used the following command to auto generate api documentation for mobly package:

sphinx-apidoc mobly --full -o docs -H 'Mobly'

Also, setup MD support for sphinx in conf.py.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/122)

### CODE REVIEW

**Comment by adorokhine** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/conf.py, line 21 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVjoykez41npXCAJp:-KdbVjoykez41npXCAJq:bx50r) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L21)):*
> ```Python
> # import os
> # import sys
> # sys.path.insert(0, u'/usr/local/google/home/mohsinally/Development/mobly/mobly')
> ```

Do we want to have this particular path as an example?

---

*[docs/conf.py, line 59 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVpngdA0H8_V9Zvuy:-KdbVpngdA0H8_V9Zvuz:bj4cox0) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L59)):*
> ```Python
> # General information about the project.
> project = u'Mobly'
> copyright = u'2017, Author'
> ```

Should we set these?

---

*[docs/conf.py, line 67 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVriZRTiE1k6JijJ0:-KdbVri_2Wdo2nSa0GHA:b-b6s6ut) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L67)):*
> ```Python
> #
> # The short X.Y version.
> version = u''
> ```

Could this be pulled out of the setup.py configs?

---

*[docs/conf.py, line 81 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVwbp1yjf-6vyudkR:-KdbVwbp1yjf-6vyudkS:b-mbeknb) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L81)):*
> ```Python
> # directories to ignore when looking for source files.
> # This patterns also effect to html_static_path and html_extra_path
> exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
> ```

Could/should this be pulled out of .gitignore?

---

*[docs/conf.py, line 161 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbW0spclXr90ps545_:-KdbW0spclXr90ps545a:b3l4c8t) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L161)):*
> ```Python
> texinfo_documents = [
>     (master_doc, 'Mobly', u'Mobly Documentation',
>      author, 'Mobly', 'One line description of project.',
> ```

No description?

---

*[docs/make.bat, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbW5yL5RB1zAE5tpxz:-KdbW5yMLM_XNHOIBnqM:bgbsum8) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/make.bat#L1)):*
> ```Batchfile
> @ECHO OFF
> ```

We don't really support windows... do we need this?

---

*[docs/Makefile, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbWCB__Atoims4TSRe:-KdbWCB__Atoims4TSRf:b-tvugu0) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/Makefile#L1)):*
> ```Makefile
> # Makefile for Sphinx documentation
> ```

Can we add a comment here for what the 'usual' way to run this is? eg how did you generate this set of docs?

---

*[docs/mobly.controllers.attenuator_lib.rst, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbWKlpBmMzNteu5pc0:-KdbWKlpBmMzNteu5pc1:bmi30fi) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/mobly.controllers.attenuator_lib.rst#L1)):*
> ```reStructuredText
> mobly.controllers.attenuator_lib package
> ```

Should we .gitignore these rst files? They don't  seem to be useful for manual use and they seem automatically generated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by yusufm** [comment]
Review status: 9 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/conf.py, line 21 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVjoykez41npXCAJp:-KdbeglltjN_hAr26PJc:b-b61q7n) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L21)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Do we want to have this particular path as an example?
</blockquote></details>

removing that.

---

*[docs/conf.py, line 59 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVpngdA0H8_V9Zvuy:-KdbelEvbyPkVv2EoFKq:bpsxeaa) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L59)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Should we set these?
</blockquote></details>

changed copyright line. Who should be Author?

---

*[docs/conf.py, line 67 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVriZRTiE1k6JijJ0:-KdbfJYNEuf0D_Lki4W-:b-p746xt) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L67)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Could this be pulled out of the setup.py configs?
</blockquote></details>

readthedocs should use versions from git tags.

---

*[docs/conf.py, line 81 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVwbp1yjf-6vyudkR:-KdbfRM1v64UH2LB7lBC:bmn6946) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L81)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Could/should this be pulled out of .gitignore?
</blockquote></details>

This is a sphinx setting. So not appropriate to get from .gitignore I beleive.

---

*[docs/conf.py, line 161 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbW0spclXr90ps545_:-Kdbfb4iTNo0sep_2Stg:b-896fix) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L161)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

No description?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by adorokhine** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/conf.py, line 67 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVriZRTiE1k6JijJ0:-Kdbi3m7yCpjJ-TUgp52:b-np1qbo) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L67)):*
<details><summary><i>Previously, yusufm wrote…</i></summary><blockquote>

readthedocs should use versions from git tags.
</blockquote></details>

sg, mind adding a comment to that effect?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by yusufm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/conf.py, line 67 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVriZRTiE1k6JijJ0:-Kdbkqmv8autal1SEtl4:bsusoci) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L67)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

sg, mind adding a comment to that effect?
</blockquote></details>

I would like to see how readthedocs actually reacts to this before adding a note. This is the default comment, so changing it could break reality.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by yusufm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/make.bat, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbW5yL5RB1zAE5tpxz:-KdbqetIC8VLr7K8A8dU:b-m0zw7u) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/make.bat#L1)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

We don't really support windows... do we need this?
</blockquote></details>

its the autogen code by sphinx. I don't think we should remove it, for simplicity.

---

*[docs/Makefile, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbWCB__Atoims4TSRe:-Kdbr2_lDqFqACSlz97_:byef85z) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/Makefile#L1)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can we add a comment here for what the 'usual' way to run this is? eg how did you generate this set of docs?
</blockquote></details>

I wouldn't change this file. Its auto generated and should be kept clean. We can have a README or some other mechanism for providing info on how to generate documentation.

---

*[docs/mobly.controllers.attenuator_lib.rst, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbWKlpBmMzNteu5pc0:-KdbqwAxQgpsvRjOZFQm:bf0gvps) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/mobly.controllers.attenuator_lib.rst#L1)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Should we .gitignore these rst files? They don't  seem to be useful for manual use and they seem automatically generated?
</blockquote></details>

These files are used by sphinx to generate the api documentation. They need to be checked in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/conf.py, line 67 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVriZRTiE1k6JijJ0:-KdbtF6KjgauvBNfiQEZ:b-uae6vh) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L67)):*
<details><summary><i>Previously, yusufm wrote…</i></summary><blockquote>

I would like to see how readthedocs actually reacts to this before adding a note. This is the default comment, so changing it could break reality.
</blockquote></details>

Sorry, are you saying that adding a new comment to this python file could break something? Does this system look at comments inside its config?

---

*[docs/Makefile, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbWCB__Atoims4TSRe:-KdbtOWsP5hhrEvFENlz:bys24hw) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/Makefile#L1)):*
<details><summary><i>Previously, yusufm wrote…</i></summary><blockquote>

I wouldn't change this file. Its auto generated and should be kept clean. We can have a README or some other mechanism for providing info on how to generate documentation.
</blockquote></details>

sg, could you add a small readme with this info and the gen command that's currently in the description of this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by yusufm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/conf.py, line 67 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbVriZRTiE1k6JijJ0:-Kdbvt-0t1Ylm5TEXvuv:bovzi9u) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/conf.py#L67)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Sorry, are you saying that adding a new comment to this python file could break something? Does this system look at comments inside its config?
</blockquote></details>

It wouldn't break anything if we add a comment, but it might not be entirely accurate a comment. So I would prefer to add it once we have some experience with readthedocs and other integrations.

---

*[docs/Makefile, line 1 at r1](https://reviewable.io:443/reviews/google/mobly/122#-KdbWCB__Atoims4TSRe:-Kdbw6u8Wcv52axj96E-:bhy9ot6) ([raw file](https://github.com/google/mobly/blob/b195aaf3215a075e1407ca808ef1205bfbcdbfac/docs/Makefile#L1)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

sg, could you add a small readme with this info and the gen command that's currently in the description of this PR?
</blockquote></details>

Will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122#-:-Kdc3mIOaBSBNSK0RdkW:bnfp4nl)*

**Comment by adorokhine** [comment]
Looks good. Thanks! Ang, are you good with this PR too?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122#-:-Kdc3uGkmwKJFsDlXf7o:b-ia4obz)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[docs/mobly.controllers.android_device_lib.rst, line 34 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcCUrKTVhaDGUQTZvI:-KdcCUrKTVhaDGUQTZvJ:b-ij1ql9) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/mobly.controllers.android_device_lib.rst#L34)):*
> ```reStructuredText
> ---------------------------------------------------------------
> 
> .. automodule:: mobly.controllers.android_device_lib.jsonrpc_client_base
> ```

Alex: should client base be listed?

---

*[docs/mobly.controllers.android_device_lib.rst, line 42 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcCOaIGlXLRfv9Iv9i:-KdcCOaIGlXLRfv9Iv9j:b-3lmwz3) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/mobly.controllers.android_device_lib.rst#L42)):*
> ```reStructuredText
> --------------------------------------------------------------
> 
> .. automodule:: mobly.controllers.android_device_lib.jsonrpc_shell_base
> ```

Alex: should the shell base be listed?

---

*[docs/mobly.rst, line 41 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcC3hvXmoGoz0RocS4:-KdcC3hvXmoGoz0RocS5:bpjuafq) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/mobly.rst#L41)):*
> ```reStructuredText
> -----------------
> 
> .. automodule:: mobly.keys
> ```

keys should not be exposed

---

*[docs/README.sphinx, line 14 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcD-KdEb47sLvx1f6W:-KdcD-KdEb47sLvx1f6X:b6m1o2j) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/README.sphinx#L14)):*
> ```
> =========================================
> 
> The initial sphinx autogeneration of mobly APIs were performed by running:
> ```

can you specify in which directory this should be run.
Also can you mention that this is only needed once unless there are module-level changes, and that this does not generate the actual doc?

---

*[docs/README.sphinx, line 24 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcCnF1phKkdXDkq9Cp:-KdcCnF1phKkdXDkq9Cq:b-8ateyy) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/README.sphinx#L24)):*
> ```
> ======================
> 
> readthedocs.org hosts Sphinx documentation for a number of open source projects. If the appropriate github hook is set, it will autogenerate documentation with each submission.
> ```

Do we need to specify this in readme?
Should we just set it up on readthedocs.org and link here instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by xpconanfan** [comment]
Posted comments, some are for Alex

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122#-:-KdcDU78JzpGY6VIzw2U:bqc3ayx)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/mobly.controllers.android_device_lib.rst, line 34 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcCUrKTVhaDGUQTZvI:-KdcG4GBcXSPPTXkT9kJ:bwpdd21) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/mobly.controllers.android_device_lib.rst#L34)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Alex: should client base be listed?
</blockquote></details>

Sure, why not? This is the full API documentation right? Like Javadoc. I don't think we can/should filter it. It's  as much a developer as a client tool.

---

*[docs/mobly.rst, line 41 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcC3hvXmoGoz0RocS4:-KdcGKGktFp-UsDW6JWs:bus8uu8) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/mobly.rst#L41)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

keys should not be exposed
</blockquote></details>

Why not? They're documented right? I'd find it convenient when developing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by yusufm** [comment]
Review status: 10 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/README.sphinx, line 14 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcD-KdEb47sLvx1f6W:-KdcHQlIt1qMHVEyg3kB:b-1w023l) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/README.sphinx#L14)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

can you specify in which directory this should be run.
Also can you mention that this is only needed once unless there are module-level changes, and that this does not generate the actual doc?
</blockquote></details>

The other sections in the doc elaborate on it. Added some more clarifications.

---

*[docs/README.sphinx, line 24 at r3](https://reviewable.io:443/reviews/google/mobly/122#-KdcCnF1phKkdXDkq9Cp:-KdcHXirkM6dYzO0v-uv:b-7rl0jd) ([raw file](https://github.com/google/mobly/blob/1ab8f80765c9825a6e2fa51face83de2726949eb/docs/README.sphinx#L24)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Do we need to specify this in readme?
Should we just set it up on readthedocs.org and link here instead?
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/122#-:-KdcKsDOrf9MOOMasifs:bnfp4nl)*

**Pull request merged**
