### PR TITLE
Properly report test results when a class is skipped.

### LINKED ISSUE #237: Properly report skipped test classes
Now that we have a way to reliably get all the tests in a class, including the generated tests, the test report for an aborted class should include entries for all the tests requested, instead of only one entry for the class.

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #237

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/238)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 598 at r1](https://reviewable.io:443/reviews/google/mobly/238#-Knubf1cLSPD58iF-quR:-Knubf1dAyi-v2lyZAv_:b-lxayl5) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/base_test.py#L598)):*
> ```Python
>             # Skip all tests peacefully.
>             e.details = 'Test class aborted due to: %s' % e.details
>             for test_name in self._get_all_test_names():
> ```

This loop reappears below. Factor out? Also would the third version of it (which checks for execution) be enough for all three usages?

---

*[mobly/records.py, line 297 at r1](https://reviewable.io:443/reviews/google/mobly/238#-KnucBh9qyNSnandAWAA:-KnucBh9qyNSnandAWAB:b-looy6t) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/records.py#L297)):*
> ```Python
>             test_record: A TestResultRecord object for the test class.
>         """
>         self.error.append(test_record)
> ```

How does this change the behavior? Can the eventual squashed message of the issue tracking explain what is changing better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 598 at r1](https://reviewable.io:443/reviews/google/mobly/238#-Knubf1cLSPD58iF-quR:-KnueMf5oRp9gFSuuo4E:b-896fix) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/base_test.py#L598)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

This loop reappears below. Factor out? Also would the third version of it (which checks for execution) be enough for all three usages?
</blockquote></details>

Done.

---

*[mobly/records.py, line 297 at r1](https://reviewable.io:443/reviews/google/mobly/238#-KnucBh9qyNSnandAWAA:-Knucpn9CcYDquEHggaj:b3x9rtu) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/records.py#L297)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

How does this change the behavior? Can the eventual squashed message of the issue tracking explain what is changing better?
</blockquote></details>

`fail` is defined as explicit failure by throwing signals.TestFailure, other things like setup_failure should be considered error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238)*

**Comment by dthkao** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/records.py, line 297 at r1](https://reviewable.io:443/reviews/google/mobly/238#-KnucBh9qyNSnandAWAA:-KoO-QzC7UZAppGueV4P:b-2egkbq) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/records.py#L297)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`fail` is defined as explicit failure by throwing signals.TestFailure, other things like setup_failure should be considered error.
</blockquote></details>

I meant how does this (appending to error instead of executed) change the summary json?

---

*[mobly/records.py, line 309 at r2](https://reviewable.io:443/reviews/google/mobly/238#-KoO-fmMHOvIdDsPppMO:-KoO-fmMHOvIdDsPppMP:b-xo747k) ([raw file](https://github.com/google/mobly/blob/20f609c9ae1d0f34b1feed91a461f09d820db6f4/mobly/records.py#L309)):*
> ```Python
>             False otherwise.
>         """
>         for record in self.executed:
> ```

minor: could be a list comprehension, right?
something like:

matches = [x for x in self.executed if x.test_name == test_name]
return len(matches)>0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/records.py, line 309 at r2](https://reviewable.io:443/reviews/google/mobly/238#-KoO-fmMHOvIdDsPppMO:-KoO0_KphsyjCeZgOlLY:b-jgdz5e) ([raw file](https://github.com/google/mobly/blob/20f609c9ae1d0f34b1feed91a461f09d820db6f4/mobly/records.py#L309)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

minor: could be a list comprehension, right?
something like:

matches = [x for x in self.executed if x.test_name == test_name]
return len(matches)>0
</blockquote></details>

what's the benefit of that?
we'd loop through the whole list every time instead of returning as long as we find a match.
seems less efficient?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/records.py, line 297 at r1](https://reviewable.io:443/reviews/google/mobly/238#-KnucBh9qyNSnandAWAA:-KoO2R8FZIzsiQfZgxCs:b-bk5w0m) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/records.py#L297)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I meant how does this (appending to error instead of executed) change the summary json?
</blockquote></details>

Oh, I'm thinking, if `setup_class` failed, no test was executed.
Hence it does not seem appropriate to append to `executed` tally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238)*

**Comment by dthkao** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/records.py, line 297 at r1](https://reviewable.io:443/reviews/google/mobly/238#-KnucBh9qyNSnandAWAA:-KoTsW6_rwxbW6e52LRw:b-6vfxlt) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/records.py#L297)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Oh, I'm thinking, if `setup_class` failed, no test was executed.
Hence it does not seem appropriate to append to `executed` tally.
</blockquote></details>

Gotcha. So this otherwise doesn't affect the actual json result entry? if so sgtm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238#-:-KoTsgnORphigSsQWRm9:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/records.py, line 297 at r1](https://reviewable.io:443/reviews/google/mobly/238#-KnucBh9qyNSnandAWAA:-KoTt_s_F8J0YEkDemYB:b-szcic4) ([raw file](https://github.com/google/mobly/blob/6d55796147bc2f537531ca28a8c475fbfd501487/mobly/records.py#L297)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Gotcha. So this otherwise doesn't affect the actual json result entry? if so sgtm.
</blockquote></details>

Yes, this only affects how setup is tallied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/238)*

**Pull request merged**
