### PR TITLE
Improve timeout error message from event callback.

### LINKED ISSUE #130: Better timeout message in CallbackHandler
Right now the `CallbackHandler`'s timeout msg only includes the `callback_id`, which is an implementation detail that doesn't make too much sense for the user. We should add the name of the call where the event was supposed to originate from.

### PR DESCRIPTION
**Pull request by xpconanfan**
fixes #130

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/135)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 74 at r1](https://reviewable.io:443/reviews/google/mobly/135#-Ke4ob0DXHPzYW-rBks6:-Ke4ob0DXHPzYW-rBks7:b6v54a8) ([raw file](https://github.com/google/mobly/blob/17f126533ea9c8c2e19c8379964a14ea02b6a3a6/mobly/controllers/android_device_lib/callback_handler.py#L74)):*
> ```Python
>                 raise TimeoutError(
>                     'Timeout waiting for event "%s" triggered by %s'
>                     % (event_name, self._method_name))
> ```

Why not keep the callback id in there as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/135)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 74 at r1](https://reviewable.io:443/reviews/google/mobly/135#-Ke4ob0DXHPzYW-rBks6:-Ke4qNtizUsPekAcMHvk:bq9wddn) ([raw file](https://github.com/google/mobly/blob/17f126533ea9c8c2e19c8379964a14ea02b6a3a6/mobly/controllers/android_device_lib/callback_handler.py#L74)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Why not keep the callback id in there as well?
</blockquote></details>

It is not really useful for regular users, and may cause confusion...
Since it is an implementation detail, I don't want people to start relying on it for analysis and other things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/135)*

**Comment by dthkao** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 74 at r1](https://reviewable.io:443/reviews/google/mobly/135#-Ke4ob0DXHPzYW-rBks6:-KeAHY-f5qWGNANKxdHW:b-m3b6kg) ([raw file](https://github.com/google/mobly/blob/17f126533ea9c8c2e19c8379964a14ea02b6a3a6/mobly/controllers/android_device_lib/callback_handler.py#L74)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It is not really useful for regular users, and may cause confusion...
Since it is an implementation detail, I don't want people to start relying on it for analysis and other things.
</blockquote></details>

What about logging the id (debug level?) for our sake but not including it in the raise?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/135)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 74 at r1](https://reviewable.io:443/reviews/google/mobly/135#-Ke4ob0DXHPzYW-rBks6:-KeAHoaJIUzPtXmcQGAb:baa157g) ([raw file](https://github.com/google/mobly/blob/17f126533ea9c8c2e19c8379964a14ea02b6a3a6/mobly/controllers/android_device_lib/callback_handler.py#L74)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

What about logging the id (debug level?) for our sake but not including it in the raise?
</blockquote></details>

Debug level goes to test run details directly, which is already too verbose...
We probably need a separate way to log stuff from mobly system. Right now there's no log that's just 'for our sake' since the user gets everything in one big file.

We need to figure out a way for better internal logging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/135)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/callback_handler.py, line 74 at r1](https://reviewable.io:443/reviews/google/mobly/135#-Ke4ob0DXHPzYW-rBks6:-KeAJ5PL7rMMeQ9Kw8lL:b-896fix) ([raw file](https://github.com/google/mobly/blob/17f126533ea9c8c2e19c8379964a14ea02b6a3a6/mobly/controllers/android_device_lib/callback_handler.py#L74)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Debug level goes to test run details directly, which is already too verbose...
We probably need a separate way to log stuff from mobly system. Right now there's no log that's just 'for our sake' since the user gets everything in one big file.

We need to figure out a way for better internal logging.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/135)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/135#-:-KeATp_LT-Te3dpMMijI:bnfp4nl)*

**Pull request merged**
