### PR TITLE
Remove deprecated code.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/693)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/693)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 226 at r1](https://reviewable.io/reviews/google/mobly/693#-MQWKmn31UMAMptUTYLk:-MQWKmn31UMAMptUTYLl:bm7f2g5) ([raw file](https://github.com/google/mobly/blob/c91cb0fd7433f27f30443384e21a0a0ae0343833/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L226)):*
> ```
>         # socket.create_connection throws different exceptions in Python 2/3
>         # TODO: Use ConnectionRefusedError directly once PY2 is deprecated.
> ```
The deprecated comments can be removed.

**Review by xpconanfan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/693)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 226 at r1](https://reviewable.io/reviews/google/mobly/693#-MQWKmn31UMAMptUTYLk:-MQWP_TSCLNAwkPwwzgq:b-896fix) ([raw file](https://github.com/google/mobly/blob/c91cb0fd7433f27f30443384e21a0a0ae0343833/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L226)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
>         # socket.create_connection throws different exceptions in Python 2/3
>         # TODO: Use ConnectionRefusedError directly once PY2 is deprecated.
> ```
The deprecated comments can be removed.
</blockquote></details>

Done.

**Review by eric100lin — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/693#-:-MQWQJEu8G60eEXaccWk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eric100lin)

**Review by eric100lin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/693)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
