### PR TITLE
Fix unit tests on Windows.

### PR DESCRIPTION
**Pull request by winterfroststrom**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/425)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[tests/mobly/output_test.py, line 91 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mNL0CBnZqALdEAwGx:-L9mNL0D2b-5sZnXWqXY:b-75xpz6) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L91)):*
> ```Python
>                 self.assertNotIn(item, content)
> 
>     @unittest.skipIf(platform.system() == 'Windows',
> ```

how would we make sure the `latest` path work in windows?
can we add unit test for win to verify the `latest` path?

---

*[tests/mobly/output_test.py, line 104 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mN4KbDSSGJAuQ6WrI:-L9mN4Kc6IB9Wa_yshUH:b-cyhuu) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L104)):*
> ```Python
>     @unittest.skipUnless(platform.system() == 'Windows',
>                          'Shortcuts are specific to Windows operating systems')
>     def test_symlink(self):
> ```

two tests of the same name?

---

*[tests/mobly/output_test.py, line 106 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mN8Ad0sjinvFM9gQb:-L9mN8Ad0sjinvFM9gQc:b-6k6dl3) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L106)):*
> ```Python
>     def test_symlink(self):
>         """Verifies the shortcut is created and links properly."""
>         from win32com import client
> ```

do conditional import at the beginning of the file?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/mobly/output_test.py, line 91 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mNL0CBnZqALdEAwGx:-L9mNVpv5ZiZziMHyEso:bxa6kar) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L91)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

how would we make sure the `latest` path work in windows?
can we add unit test for win to verify the `latest` path?
</blockquote></details>

Oh nvm

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/output_test.py, line 102 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mOCv_730kaL2fcELC:-L9mOCv_730kaL2fcELD:b-dhaxqz) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L102)):*
> ```Python
>         self.assertTrue(os.readlink(symlink), logging.log_path)
> 
>     @unittest.skipUnless(platform.system() == 'Windows',
> ```

can we use `skipIf` here? less likely to be misread.

---

*[tests/mobly/output_test.py, line 104 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mN4KbDSSGJAuQ6WrI:-L9mNc4c0iavx7dvS9bf:b9a12r0) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L104)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

two tests of the same name?
</blockquote></details>

Wouldn't the second override the first regardless of the decorators?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/mobly/output_test.py, line 102 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mOCv_730kaL2fcELC:-L9mPGOeA6YzTkq8yDm3:b-896fix) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L102)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

can we use `skipIf` here? less likely to be misread.
</blockquote></details>

Done.

---

*[tests/mobly/output_test.py, line 104 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mN4KbDSSGJAuQ6WrI:-L9mOJ9DERka48VY3ZQ5:b-skzxav) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L104)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Wouldn't the second override the first regardless of the decorators?
</blockquote></details>

Yes, this is a mistake from copying-pasting stuff from my windows workspace because I don't have a real dev process on Windows right now

---

*[tests/mobly/output_test.py, line 106 at r1](https://beta.reviewable.io/reviews/google/mobly/425#-L9mN8Ad0sjinvFM9gQb:-L9mPH1T4HNDbxW1mRex:b-896fix) ([raw file](https://github.com/google/mobly/blob/6dbe9e6572666a6236268fa1aa8aae1d53f36cd1/tests/mobly/output_test.py#L106)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

do conditional import at the beginning of the file?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[tests/mobly/output_test.py, line 116 at r2](https://beta.reviewable.io/reviews/google/mobly/425#-L9mPZPX5_kdmA-qvhSz:-L9mPZPX5_kdmA-qvhT-:b354p86) ([raw file](https://github.com/google/mobly/blob/ab5eb7b95c498ca45ad207d8d6d666b15af361cc/tests/mobly/output_test.py#L116)):*
> ```Python
>         shortcut_path = os.path.join(self.log_dir, self.test_bed_name,
>                                      'latest.lnk')
>         self.assertTrue
> ```

what's this?

---

*[tests/mobly/output_test.py, line 118 at r2](https://beta.reviewable.io/reviews/google/mobly/425#-L9mPhEf0xbJcxNnRSYx:-L9mPhEf0xbJcxNnRSYy:b-4vv679) ([raw file](https://github.com/google/mobly/blob/ab5eb7b95c498ca45ad207d8d6d666b15af361cc/tests/mobly/output_test.py#L118)):*
> ```Python
>         self.assertTrue
>         shell = client.Dispatch("WScript.Shell")
>         shortcut = shell.CreateShortCut(shortcut_path)
> ```

we are creating this shortcut inside the test then verifying it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/output_test.py, line 116 at r2](https://beta.reviewable.io/reviews/google/mobly/425#-L9mPZPX5_kdmA-qvhSz:-L9mQd3K3_duss8mzsWU:bwdf3ew) ([raw file](https://github.com/google/mobly/blob/ab5eb7b95c498ca45ad207d8d6d666b15af361cc/tests/mobly/output_test.py#L116)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

That's another copy-paste error

---

*[tests/mobly/output_test.py, line 118 at r2](https://beta.reviewable.io/reviews/google/mobly/425#-L9mPhEf0xbJcxNnRSYx:-L9mQfpt5gCteuTq5c-p:b-bld52l) ([raw file](https://github.com/google/mobly/blob/ab5eb7b95c498ca45ad207d8d6d666b15af361cc/tests/mobly/output_test.py#L118)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

we are creating this shortcut inside the test then verifying it?
</blockquote></details>

Based on https://stackoverflow.com/questions/397125/reading-the-target-of-a-lnk-file-in-python,
the shortcut should be created by the test runner, but I believe this command is just making a reference to the actual shortcut to read it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/output_test.py, line 118 at r2](https://beta.reviewable.io/reviews/google/mobly/425#-L9mPhEf0xbJcxNnRSYx:-L9mR_eoAYmwfbjcmJ4s:b-b8ody0) ([raw file](https://github.com/google/mobly/blob/ab5eb7b95c498ca45ad207d8d6d666b15af361cc/tests/mobly/output_test.py#L118)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Based on https://stackoverflow.com/questions/397125/reading-the-target-of-a-lnk-file-in-python,
the shortcut should be created by the test runner, but I believe this command is just making a reference to the actual shortcut to read it.
</blockquote></details>

Sounds like we should assert this is None before test run?

---

*[tests/mobly/output_test.py, line 118 at r3](https://beta.reviewable.io/reviews/google/mobly/425#-L9mRXmFEl37iO9g4WT0:-L9mRXmFEl37iO9g4WT1:bd614on) ([raw file](https://github.com/google/mobly/blob/a728b0edcc49e972bdafb0202b8638569faacdac/tests/mobly/output_test.py#L118)):*
> ```Python
>         shell = client.Dispatch("WScript.Shell")
>         shortcut = shell.CreateShortCut(shortcut_path)
>         self.assertTrue(shortcut.Targetpath, logging.log_path)
> ```

do you mean `assertEqual`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/output_test.py, line 118 at r2](https://beta.reviewable.io/reviews/google/mobly/425#-L9mPhEf0xbJcxNnRSYx:-L9mRcFM0S-ef7oP8Dta:bzajsq8) ([raw file](https://github.com/google/mobly/blob/ab5eb7b95c498ca45ad207d8d6d666b15af361cc/tests/mobly/output_test.py#L118)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Sounds like we should assert this is None before test run?
</blockquote></details>

Right from testing on windows, if the actual shortcut doesn't exist, it'll just returns empty string, otherwise it returns the actual path

okay, will do

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/output_test.py, line 118 at r2](https://beta.reviewable.io/reviews/google/mobly/425#-L9mPhEf0xbJcxNnRSYx:-L9memw586u03Df9SWD2:b-896fix) ([raw file](https://github.com/google/mobly/blob/ab5eb7b95c498ca45ad207d8d6d666b15af361cc/tests/mobly/output_test.py#L118)):*
<details><summary><i>Previously, winterfroststrom wrote…</i></summary><blockquote>

Right from testing on windows, if the actual shortcut doesn't exist, it'll just returns empty string, otherwise it returns the actual path

okay, will do
</blockquote></details>

Done.

---

*[tests/mobly/output_test.py, line 118 at r3](https://beta.reviewable.io/reviews/google/mobly/425#-L9mRXmFEl37iO9g4WT0:-L9melb0CTU6XRU8Mqqh:b-896fix) ([raw file](https://github.com/google/mobly/blob/a728b0edcc49e972bdafb0202b8638569faacdac/tests/mobly/output_test.py#L118)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

do you mean `assertEqual`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[tests/mobly/output_test.py, line 114 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pq1dl9alqAHtyojzf:-L9pq1dl9alqAHtyojzg:b-7rifpa) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/output_test.py#L114)):*
> ```Python
>         shell = client.Dispatch("WScript.Shell")
>         shortcut = shell.CreateShortCut(shortcut_path)
>         self.assertFalse(shortcut.Targetpath)
> ```

`assertIsNone`?

---

*[tests/mobly/output_test.py, line 121 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pq7RB5IANDdmWnzIq:-L9pq7RB5IANDdmWnzIr:bkzzj0j) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/output_test.py#L121)):*
> ```Python
>         tr._teardown_logger()
>         shortcut = shell.CreateShortCut(shortcut_path)
>         # Normalize paths for case and truncation
> ```

why do we need to normalize path here?
if we need it here, should we not check the normalized path is none in the beginning?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/controllers/monsoon_test.py, line 21 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pqagWBfQBjrBVNBxh:-L9pqagWBfQBjrBVNBxi:bxfnm5g) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/controllers/monsoon_test.py#L21)):*
> ```Python
> 
> class MonsoonTest(unittest.TestCase):
>     @unittest.skipIf(platform.system() == 'Windows',
> ```

do we need a todo to fix monsoon importing on Windows?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/mobly/controllers/android_device_test.py, line 598 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pqh8YAwpbfirja0uw:-L9pqh8YAwpbfirja0ux:b-bvoiky) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/controllers/android_device_test.py#L598)):*
> ```Python
> 
>     @unittest.skipIf(platform.system() == 'Windows',
>                      'The character ":" is not valid in Windows file names')
> ```

we should fix the behavior of this API on windows instead of skipping the test here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/mobly/output_test.py, line 114 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pq1dl9alqAHtyojzf:-L9q5iRZ37GKuxzk9s3-:b-mw25il) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/output_test.py#L114)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`assertIsNone`?
</blockquote></details>


That doesn't quite work because it returns u'' instead of None

---

*[tests/mobly/output_test.py, line 121 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pq7RB5IANDdmWnzIq:-L9q5mVZ9VOYIfh1i1gb:b4xcd84) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/output_test.py#L121)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why do we need to normalize path here?
if we need it here, should we not check the normalized path is none in the beginning?
</blockquote></details>

The path needs to be normalized because windows will sometimes truncate names for example winter~ vs winterfrosts
Additionally, windows is case-insensitive but string comparison isn't

---

*[tests/mobly/controllers/android_device_test.py, line 598 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pqh8YAwpbfirja0uw:-L9q634_0KNIp28jALvQ:b-cihauv) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/controllers/android_device_test.py#L598)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

we should fix the behavior of this API on windows instead of skipping the test here.
</blockquote></details>

Yes, but that's tracked in another issue:
https://github.com/google/mobly/issues/423

Added a TODO though

---

*[tests/mobly/controllers/monsoon_test.py, line 21 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pqagWBfQBjrBVNBxh:-L9q6CMK5oZ9DqJ_vM0n:b-896fix) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/controllers/monsoon_test.py#L21)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

do we need a todo to fix monsoon importing on Windows?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_test.py, line 598 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pqh8YAwpbfirja0uw:-L9qNFFK2XROhMZSYyuD:bh26boe) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/controllers/android_device_test.py#L598)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

if this is tracked by another issue, can we leave this test failing instead of skipping it?
I'd rather not skip tests just so the build is green.
</blockquote></details>

the monsoon one is ok to skip since it's not as critical
this is in AndroidDevice, we should not leave it broken for win.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by winterfroststrom** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/controllers/android_device_test.py, line 598 at r4](https://beta.reviewable.io/reviews/google/mobly/425#-L9pqh8YAwpbfirja0uw:-L9r7pGkDDThOEaDMBOA:beaoz4k) ([raw file](https://github.com/google/mobly/blob/16c0dcd8e36aeb9684519fcf158127420dc92184/tests/mobly/controllers/android_device_test.py#L598)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

the monsoon one is ok to skip since it's not as critical
this is in AndroidDevice, we should not leave it broken for win.
</blockquote></details>

Okay, I've forced pushed with those changes gone, since it'll be handled with https://github.com/google/mobly/pull/433 instead

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/425#-:-LA4ZjQXCGVg9sd6YdAT:bnfp4nl)*

**Pull request merged**
