### PR TITLE
Remove usage of distutil for dir operations.

### PR DESCRIPTION
**Pull request by xpconanfan**
So we don't have to deal with `distutil` in lib code

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/365)

### CODE REVIEW

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6H4NsfuiKgynhiEs0:-Kz6H4NsfuiKgynhiEs1:b-nu55y1) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L510)):*
> shutil.rmtree(new_path, ignore_errors=True)
need to ensure new_path doesn't equal old_path, otherwise there will be data loss

---

*[mobly/controllers/android_device.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6HOloak_lsUWVZY7C:-Kz6HOloak_lsUWVZY7D:bzdik2o) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L510)):*
> ```Python
>         utils.create_dir(new_path)
>         if os.path.exists(old_path):
>             shutil.rmtree(new_path, ignore_errors=True)
> ```

Since path can be change now, do we have to worry about user doing some wrong like 2 different test setting to the same path?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6H4NsfuiKgynhiEs0:-Kz6JJCWBlnvepRcMPiy:b-896fix) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L510)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

> shutil.rmtree(new_path, ignore_errors=True)
need to ensure new_path doesn't equal old_path, otherwise there will be data loss
</blockquote></details>

Done.

---

*[mobly/controllers/android_device.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6HOloak_lsUWVZY7C:-Kz6JJVE48C7xV9_POBB:b5hnq6h) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L510)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

Since path can be change now, do we have to worry about user doing some wrong like 2 different test setting to the same path?
</blockquote></details>

Added a check, check it out..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6H4NsfuiKgynhiEs0:-Kz6LA88f1KWhF9P2IrB:b-rilex5) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L510)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the log path equality check needs to be above the directory existence check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 510 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6H4NsfuiKgynhiEs0:-Kz6MiojJuGRG4AQL_rQ:b-896fix) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L510)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

the log path equality check needs to be above the directory existence check.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6R6DdyW6gQkNsleVl:bur9qrm) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
> utils.create_dir(new_path)
looks like this got loss, don't we still need this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6Rbb9lHCKLlx263Aq:bgvaau9) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

> utils.create_dir(new_path)
looks like this got loss, don't we still need this?
</blockquote></details>

No we don't. `copytree` does it already

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6GkLWJlP7usCytleq:b-2qhr58) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

No we don't. `copytree` does it already
</blockquote></details>

but old_path might not exist thus skipping the copytree.  though I don't know when that might happen

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6SJM46sZruHXWkPfs:b4j439i) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

but old_path might not exist thus skipping the copytree.  though I don't know when that might happen
</blockquote></details>

not sure what you mean. if old path doesn't exist then there's nothing to copy?
code that write to `log_path` don't assume its existence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6T6P8LUYq4oO82x1T:bnpd3iw) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

not sure what you mean. if old path doesn't exist then there's nothing to copy?
code that write to `log_path` don't assume its existence.
</blockquote></details>

new_path won't be created if old_path doesn't exist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6TgDnjQEf3EEKai-e:b-5b5syd) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

new_path won't be created if old_path doesn't exist
</blockquote></details>

Correct and that's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6VAUXCghYRNVah8Zs:b31xurs) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Correct and that's fine.
</blockquote></details>

when log actually gets written to this new location later, it might fail since the log_path doesn't exist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz6WZ8GB4ArTIpAwpTh:b-zgspjh) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

when log actually gets written to this new location later, it might fail since the log_path doesn't exist
</blockquote></details>

No it won't.
if you look at the old code before the attribute change, `log_path` did not exist until write.
bc all APIs that write to it can take care of the creation themselves.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 508 at r1](https://reviewable.io:443/reviews/google/mobly/365#-Kz6R6DdyW6gQkNsleVk:-Kz9x3EeptC88EdD6dJp:byzlzy3) ([raw file](https://github.com/google/mobly/blob/a8d08f7ab4dfaf7af097902155533a94365fc5e9/mobly/controllers/android_device.py#L508)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

No it won't.
if you look at the old code before the attribute change, `log_path` did not exist until write.
bc all APIs that write to it can take care of the creation themselves.
</blockquote></details>

ah, the other place creates the directory recursively (at less that's what I saw at  RuntimeTestInfo).  But it still seems like this base log path should be created here so that its not depending on other places to do so.  I guess my main issue with this is that by the end of this function, it isn't deterministic if log_path exist or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365)*

**Comment by xpconanfan** [comment]
This is consistent with the previous static log_path and is by design. So
we are not changing it here.

If nothing wrote to it, it doesn't exist.

**Comment by k2fong** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/365#-:-KzAWREI1GoRWJt_A23H:bnfp4nl)*

**Pull request merged**
