### PR TITLE
Fixed missing stacktrace for py2 for setup_test failure

### LINKED ISSUE #409: Exceptions thrown from `setup_test` lose stacktrace in test logs.
The full stack trace logged looks like:

```
Traceback (most recent call last):
  File "mobly/base_test.py", line 363, in exec_one_test
    raise new_e
```

### PR DESCRIPTION
**Pull request by matty3**
Same as https://github.com/google/mobly/pull/412 but with the commit author corrected.

Fixes #409

Ran with python version 2.7.13 and got the sample error response back:

[SampleTestBed] 02-27 16:10:30.221 INFO [Test] test_hello
[SampleTestBed] 02-27 16:10:30.221 ERROR Exception occurred in test_hello.
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/mobly-1.7.1-py2.7.egg/mobly/base_test.py", line 359, in exec_one_test
self._setup_test(test_name)
File "/usr/local/lib/python2.7/dist-packages/mobly-1.7.1-py2.7.egg/mobly/base_test.py", line 211, in _setup_test
self.setup_test()
File "hello_world_test.py", line 18, in setup_test
asserts.fail('sample failure')
File "/usr/local/lib/python2.7/dist-packages/mobly-1.7.1-py2.7.egg/mobly/asserts.py", line 239, in fail
raise signals.TestFailure(msg, extras)
TestError: Details=Details=sample failure, Extras=None, Extras=None
[SampleTestBed] 02-27 16:10:30.223 INFO [Test] test_hello ERROR

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/413)

### CODE REVIEW

**Comment by matty3** [comment]
Hey Ang - for your previous comments:

> is it possible to add some unit test to verify the log output?

I'll see what I can do

> I like this, can you check if we are doing anything similar in other places and replace with this?

Sure I'll see if this is happening elsewhere

**Comment by matty3** [comment]
Ang - comments below

> is it possible to add some unit test to verify the log output?
Added stack trace check to tests

> I like this, can you check if we are doing anything similar in other places and replace with this?
Did a search for '__traceback__' and it looks like this was the only place it was used like this. No other changes needed.

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 363 at r3](https://reviewable.io:443/reviews/google/mobly/413#-L8JITOCSAwJNq2BeRBz:-L8JITODZujZUhGej6TK:b-zcus2h) ([raw file](https://github.com/google/mobly/blob/3013a5d8be3e4b03e2da4478ea5f99e8987cf229/mobly/base_test.py#L363)):*
> ```Python
>                     self._setup_test(test_name)
>                 except signals.TestFailure as e:
>                     raise_with_traceback(signals.TestError(e.details, e.extras))
> ```

Does this function also add the `__traceback__` attr to the exception obj in py2?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/413)*

**Comment by matty3** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 363 at r3](https://beta.reviewable.io/reviews/google/mobly/413#-L8JITOCSAwJNq2BeRBz:-L8cc19T0W6xuTM_DMn9:b-r2dpqe) ([raw file](https://github.com/google/mobly/blob/3013a5d8be3e4b03e2da4478ea5f99e8987cf229/mobly/base_test.py#L363)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Does this function also add the `__traceback__` attr to the exception obj in py2?
</blockquote></details>

Yes it does. The test checks for the traceback in both py2 and py3.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/413)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 363 at r3](https://beta.reviewable.io/reviews/google/mobly/413#-L8JITOCSAwJNq2BeRBz:-L8dQTGMDF7BmfFzP12X:bhx1sxv) ([raw file](https://github.com/google/mobly/blob/3013a5d8be3e4b03e2da4478ea5f99e8987cf229/mobly/base_test.py#L363)):*
<details><summary><i>Previously, matty3 (Matthew) wrote…</i></summary><blockquote>

Yes it does. The test checks for the traceback in both py2 and py3.
</blockquote></details>

I mean specifically the existence of attribute `__traceback__`...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/413)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 363 at r3](https://beta.reviewable.io/reviews/google/mobly/413#-L8JITOCSAwJNq2BeRBz:-L97UKP36vk1d6TWXMpj:b5aojyt) ([raw file](https://github.com/google/mobly/blob/3013a5d8be3e4b03e2da4478ea5f99e8987cf229/mobly/base_test.py#L363)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I mean specifically the existence of attribute `__traceback__`...
</blockquote></details>

I think this is good enough..

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/413#-:-L97UmM0BwrmRmE-f7ry:bnfp4nl)*

**Comment by matty3** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[mobly/base_test.py, line 363 at r3](https://beta.reviewable.io/reviews/google/mobly/413#-L8JITOCSAwJNq2BeRBz:-L961bau-EmU55e4k5Fh:b933xqq) ([raw file](https://github.com/google/mobly/blob/3013a5d8be3e4b03e2da4478ea5f99e8987cf229/mobly/base_test.py#L363)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I mean specifically the existence of attribute `__traceback__`...
</blockquote></details>

I believe so. The test that was modified does checks on the record returned from a run. This is the same record that checks for the existence of __traceback__. Since the test passes for py2 and py3, I think it is safe to say that it works as intended.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/413)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/413)*

**Pull request merged**
