### PR TITLE
Lock adb port management.

### PR DESCRIPTION
**Pull request by adorokhine**
adb gets very confused if you try to manage port forwarding concurrently on
the same server, leading to crashes like "Socket error: no error".

Adding a lock around it seems to make the errors go away.

Issue #102.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/173)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 150 at r1](https://reviewable.io:443/reviews/google/mobly/173#-KgXqS7ww1obpXts8UnZ:-KgXqS7ww1obpXts8Un_:b1z1by) ([raw file](https://github.com/google/mobly/blob/1a433aa94720cab9a1efcec438b530ffb870c104/mobly/controllers/android_device_lib/adb.py#L150)):*
> ```Python
> 
>     def forward(self, args=None, shell=False):
>         with ADB_PORT_LOCK:
> ```

You mean running two `adb forward` cmds concurrently is causing problems?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 150 at r1](https://reviewable.io:443/reviews/google/mobly/173#-KgXqS7ww1obpXts8UnZ:-KgXvFS7eFVSEyq_rOzp:by1a28c) ([raw file](https://github.com/google/mobly/blob/1a433aa94720cab9a1efcec438b530ffb870c104/mobly/controllers/android_device_lib/adb.py#L150)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

You mean running two `adb forward` cmds concurrently is causing problems?
</blockquote></details>

Yep, that's right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 25 at r1](https://reviewable.io:443/reviews/google/mobly/173#-KgXxx_lf43s3jxzhysz:-KgXxx_lf43s3jxzhyt-:bgzo7ul) ([raw file](https://github.com/google/mobly/blob/1a433aa94720cab9a1efcec438b530ffb870c104/mobly/controllers/android_device_lib/adb.py#L25)):*
> ```Python
> 
> # adb gets confused if we try to manage bound ports in parallel, so anything to
> # do with port forwarding must happen under this lock.
> ```

what about the cmd to remove the forwarded port in `AndroidDevice._terminate_jsonrpc_client`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 25 at r1](https://reviewable.io:443/reviews/google/mobly/173#-KgXxx_lf43s3jxzhysz:-KgXyMPVfYB4GzQUkjrH:bm7gsuk) ([raw file](https://github.com/google/mobly/blob/1a433aa94720cab9a1efcec438b530ffb870c104/mobly/controllers/android_device_lib/adb.py#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what about the cmd to remove the forwarded port in `AndroidDevice._terminate_jsonrpc_client`?
</blockquote></details>

Yep, that one would conflict as well, so it is subject to the same lock by virtue of going through adb.forward().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 25 at r1](https://reviewable.io:443/reviews/google/mobly/173#-KgXxx_lf43s3jxzhysz:-KgXym7k-UC3dGJ2Srbp:be01ptg) ([raw file](https://github.com/google/mobly/blob/1a433aa94720cab9a1efcec438b530ffb870c104/mobly/controllers/android_device_lib/adb.py#L25)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Yep, that one would conflict as well, so it is subject to the same lock by virtue of going through adb.forward().
</blockquote></details>

Hmm, taking a second look at this, in what case would two `adb forward` cmds be executed in parallel?
Also this guard does not work when multiple test runs are running at the same time anyway...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 25 at r1](https://reviewable.io:443/reviews/google/mobly/173#-KgXxx_lf43s3jxzhysz:-KgXzKcU_iDib9joFYMd:bvxhjuv) ([raw file](https://github.com/google/mobly/blob/1a433aa94720cab9a1efcec438b530ffb870c104/mobly/controllers/android_device_lib/adb.py#L25)):*
> in what case would two adb forward cmds be executed in parallel?
Our case was that we wanted to load all our snippets in parallel, since we have quite a few. This was breaking adb.

> Also this guard does not work when multiple test runs are running at the same time anyway...
That's true, it doesn't handle conflicts from other processes. Any suggestions for how you'd like that handled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 25 at r1](https://reviewable.io:443/reviews/google/mobly/173#-KgXxx_lf43s3jxzhysz:-KgXzjQT245GafK3EpSz:b-sahqqc) ([raw file](https://github.com/google/mobly/blob/1a433aa94720cab9a1efcec438b530ffb870c104/mobly/controllers/android_device_lib/adb.py#L25)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

> in what case would two adb forward cmds be executed in parallel?
Our case was that we wanted to load all our snippets in parallel, since we have quite a few. This was breaking adb.

> Also this guard does not work when multiple test runs are running at the same time anyway...
That's true, it doesn't handle conflicts from other processes. Any suggestions for how you'd like that handled?
</blockquote></details>

Perhaps fixing this in adb itself might be something we should consider as well...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/173#-:-KgXzt0-xjEzRUb2u69y:bnfp4nl)*

**Pull request merged**
