### PR TITLE
Add stacktrace to test record.

### LINKED ISSUE #148: Test result entry should include stacktrace
Test result entry in test summary should include the stacktrace if an exception happened during test.
Right now we only see the message of the exception, not the whole stacktrace.

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #148

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/149)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/records_test.py, line 53 at r1](https://reviewable.io:443/reviews/google/mobly/149#-KfhYCRo7N1Mb-GMibbB:-KfhYCRpk1ULCwWzPm0v:buhzymz) ([raw file](https://github.com/google/mobly/blob/c550454acdb3f0c9a30f69688defd2077748798d/tests/mobly/records_test.py#L53)):*
> ```Python
>         d[records.TestResultEnums.RECORD_UID] = None
>         d[records.TestResultEnums.RECORD_CLASS] = None
>         d[records.TestResultEnums.RECORD_EXTRA_ERRORS] = {}
> ```

should this default to None?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/149)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/records_test.py, line 53 at r1](https://reviewable.io:443/reviews/google/mobly/149#-KfhYCRo7N1Mb-GMibbB:-KfhYeBdpfa-xsEmzTt8:b-2464s0) ([raw file](https://github.com/google/mobly/blob/c550454acdb3f0c9a30f69688defd2077748798d/tests/mobly/records_test.py#L53)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

should this default to None?
</blockquote></details>

No, this is expected to be `{}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/149)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/records.py, line 75 at r1](https://reviewable.io:443/reviews/google/mobly/149#-KfhdCfKwLhwL3aIe5DO:-KfhdCfLSxeaYL9F_XWw:b-m2orxp) ([raw file](https://github.com/google/mobly/blob/c550454acdb3f0c9a30f69688defd2077748798d/mobly/records.py#L75)):*
> ```Python
>         self.details = None
>         self.stacktrace = None
>         self.extra_errors = {}
> ```

Sorry I meant to comment here, not in the test. What's the reason to treat this differently from other record entries? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/149)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/records.py, line 75 at r1](https://reviewable.io:443/reviews/google/mobly/149#-KfhdCfKwLhwL3aIe5DO:-KfhgVIsjtBio_gnVx4R:b-4qpzrg) ([raw file](https://github.com/google/mobly/blob/c550454acdb3f0c9a30f69688defd2077748798d/mobly/records.py#L75)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Sorry I meant to comment here, not in the test. What's the reason to treat this differently from other record entries? 
</blockquote></details>

bc this is the only one that is expected to be an iterable by design.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/149)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/149#-:-KfhiqMdAbQ_9unbAwje:bnfp4nl)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/149#-:-KfhjnivIEpL5UlFLHwR:bnfp4nl)*

**Pull request merged**
