### PR TITLE
Fix adb test

### PR DESCRIPTION
**Pull request by l-meng**
Use mock instead of python -c command to test adb module

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/310)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/mobly/controllers/android_device_lib/adb_test.py, line 43 at r1](https://reviewable.io:443/reviews/google/mobly/310#-KrbyANwkAqqB4RWgt0C:-KrbyANxw_50Vs_isScM:b-5csrn) ([raw file](https://github.com/google/mobly/blob/e95a0ae92268570639a6582fd865e79983e51493/tests/mobly/controllers/android_device_lib/adb_test.py#L43)):*
> ```Python
>     def test_exec_cmd_no_timeout_success(self, mock_psutil_process,
>                                          mock_Popen):
>         self._mock_process(mock_psutil_process, mock_Popen)
> ```

if this is called before every test, you can have a `self.setUp` method for it.

---

*[tests/mobly/controllers/android_device_lib/adb_test.py, line 67 at r1](https://reviewable.io:443/reviews/google/mobly/310#-KrbyUOfD-vfgSP8Jbcc:-KrbyUOfD-vfgSP8Jbcd:b-s69fjy) ([raw file](https://github.com/google/mobly/blob/e95a0ae92268570639a6582fd865e79983e51493/tests/mobly/controllers/android_device_lib/adb_test.py#L67)):*
> ```Python
>         # mock process.wait(timeout=timeout) to not
>         # throw psutil.TimeoutExpired exception
>         mock_psutil_process.return_value.wait.return_value = None
> ```

is this line needed? wouldn't mock return None by default?

---

*[tests/mobly/controllers/android_device_lib/adb_test.py, line 87 at r1](https://reviewable.io:443/reviews/google/mobly/310#-Krbydj89YJgsiTf4ugl:-Krbydj89YJgsiTf4ugm:b-n23k2p) ([raw file](https://github.com/google/mobly/blob/e95a0ae92268570639a6582fd865e79983e51493/tests/mobly/controllers/android_device_lib/adb_test.py#L87)):*
> ```Python
>     @mock.patch('mobly.controllers.android_device_lib.adb.subprocess.Popen')
>     @mock.patch('mobly.controllers.android_device_lib.adb.psutil.Process')
>     def test_exec_cmd_timeout_negative_error(self, mock_psutil_process,
> ```

`test_exec_cmd_with_negative_timeout_value`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/310)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 130 at r2](https://reviewable.io:443/reviews/google/mobly/310#-Krc1Gha5u-BjZNVzkA4:-Krc1Gha5u-BjZNVzkA5:b-g04cfb) ([raw file](https://github.com/google/mobly/blob/2d07f4f8355ebea62bf2a76af08d2e0eac392003/mobly/controllers/android_device_lib/adb.py#L130)):*
> ```Python
>                 process.terminate()
>                 raise AdbTimeoutError('Timed out Adb cmd "%s". timeout: %s' %
>                                       (args, timeout))
> ```

why was this changed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/310)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/310)*

**Comment by l-meng** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 130 at r2](https://reviewable.io:443/reviews/google/mobly/310#-Krc1Gha5u-BjZNVzkA4:-Krc9ZumVwjGTynX2BuR:bwis6ij) ([raw file](https://github.com/google/mobly/blob/2d07f4f8355ebea62bf2a76af08d2e0eac392003/mobly/controllers/android_device_lib/adb.py#L130)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why was this changed?
</blockquote></details>

yapf updated the format, should we include it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/310)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/310)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/310#-:-KrcCS20XxRTaTPTYhnD:bnfp4nl)*

**Pull request merged**
