### PR TITLE
Change 'test case' to 'test method' for clarity.

### PR DESCRIPTION
**Pull request by adorokhine**
Pyunit and JUnit both use 'test case' to mean 'test class', but Mobly used
it to mean 'test method', so trying to avoid misunderstanding.

Note: Unused parts of config_parser.py are being deleted instead of
updated.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/210)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 232 at r1](https://reviewable.io:443/reviews/google/mobly/210#-KkK2NIuqE6MjZA25_MI:-KkK2NIuqE6MjZA25_MJ:b-1bmdpx) ([raw file](https://github.com/google/mobly/blob/b8ecf7a4a22f9ae5aebb7493d72dcdcdfccf9851/mobly/base_test.py#L232)):*
> ```Python
>         Args:
>             record: The records.TestResultRecord object for the failed test
>                     method.
> ```

When we refer to the test's results, it means the result of the "test", not the result of executing the "test method".
The method is just the "test_xxx" function, whereas the "test" is more than just that, e.g. the setup of a test method can also fail the test.

The equivalent for "test case"/"test" in base class is "test", not "test method".
We should only use "test_method" to refer to the actual "test_xxx" function.

---

*[mobly/base_test.py, line 324 at r1](https://reviewable.io:443/reviews/google/mobly/210#-KkK3tM7DmMHOGVouALv:-KkK3tM7DmMHOGVouALw:b-ujg4hj) ([raw file](https://github.com/google/mobly/blob/b8ecf7a4a22f9ae5aebb7493d72dcdcdfccf9851/mobly/base_test.py#L324)):*
> ```Python
>             tr_record.add_error(func.__name__, e)
> 
>     def exec_one_test_method(self, test_name, test_method, args=(), **kwargs):
> ```

This is executing a "test", not just a "test method" as it executes the setup and teardown as well, which are separate methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/210)*

**Comment by adorokhine** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/base_test.py, line 232 at r1](https://reviewable.io:443/reviews/google/mobly/210#-KkK2NIuqE6MjZA25_MI:-KkKAvVgoamNJdxHc2pK:b-896fix) ([raw file](https://github.com/google/mobly/blob/b8ecf7a4a22f9ae5aebb7493d72dcdcdfccf9851/mobly/base_test.py#L232)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

When we refer to the test's results, it means the result of the "test", not the result of executing the "test method".
The method is just the "test_xxx" function, whereas the "test" is more than just that, e.g. the setup of a test method can also fail the test.

The equivalent for "test case"/"test" in base class is "test", not "test method".
We should only use "test_method" to refer to the actual "test_xxx" function.
</blockquote></details>

Done.

---

*[mobly/base_test.py, line 324 at r1](https://reviewable.io:443/reviews/google/mobly/210#-KkK3tM7DmMHOGVouALv:-KkKAxqHhTO5ZQWxithz:b-896fix) ([raw file](https://github.com/google/mobly/blob/b8ecf7a4a22f9ae5aebb7493d72dcdcdfccf9851/mobly/base_test.py#L324)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This is executing a "test", not just a "test method" as it executes the setup and teardown as well, which are separate methods.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/210)*

**Comment by xpconanfan** [comment]
Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[mobly/base_test.py, line 167 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNW1wRnmFlBMlHWCjo:-KkNW1wRnmFlBMlHWCjp:bc6z9df) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/base_test.py#L167)):*
> ```Python
> 
>     def setup_class(self):
>         """Setup function that will be called before executing any test method
> ```

"test"

---

*[mobly/base_test.py, line 402 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNWCos2_RJJhw5NW8C:-KkNWCos2_RJJhw5NW8D:bljv73b) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/base_test.py#L402)):*
> ```Python
> 
>         Generated tests are not written down as methods, but as a list of
>         parameter sets. This way we reduce code repetition and improve test
> ```

"improve scalability"?

---

*[mobly/config_parser.py, line 88 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNWNE6ZfxRVD_S3iwj:-KkNWNE6ZfxRVD_S3iwk:b-w2e949) ([raw file](https://github.com/google/mobly/blob/092d02c17b60c5e7e6d0594687ffa9d9c1711ed8/mobly/config_parser.py#L88)):*
> ```Python
> 
> 
> def _verify_test_class_name(test_cls_name):
> ```

why are these being removed here? seems completely unrelated to the context of this PR.

---

*[mobly/suite_runner.py, line 58 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfYqUgTQCvqJGCpY1:-KkNfYqUgTQCvqJGCpY2:b1qszz3) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/suite_runner.py#L58)):*
> ```Python
>         help='Path to the test configuration file.')
>     parser.add_argument(
>         '--test',
> ```

should this be "tests" since it's a list?

---

*[mobly/suite_runner.py, line 63 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfepTGne0pfr93qLZ:-KkNfepTGne0pfr93qL_:b-a1c5nt) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/suite_runner.py#L63)):*
> ```Python
>         type=str,
>         metavar='[ClassA[.test_a] ClassB[.test_b] ...]',
>         help='A list of test classes and optional test methods to execute.')
> ```

It should be "test class names", and test names" instead of "test methods" here right?

---

*[mobly/test_runner.py, line 67 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfx1-pvvksIyUglz9:-KkNfx1-pvvksIyUglzA:brbzwu0) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L67)):*
> ```Python
>         help='Path to the test configuration file.')
>     parser.add_argument(
>         '--test',
> ```

should this be plural?

---

*[mobly/test_runner.py, line 72 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfqVBzhP2YnpQydA2:-KkNfqVC27nq3RWmuHkq:b-t3wf8s) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L72)):*
> ```Python
>         type=str,
>         metavar='[test_a test_b...]',
>         help='A list of test methods in the test script.')
> ```

This is a list of "test names" here?

---

*[mobly/test_runner.py, line 89 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNg4kG2bw7D3-05FKY:-KkNg4kG2bw7D3-05FKZ:bqef2qm) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L89)):*
> ```Python
>     test_class = _find_test_class()
>     test_class_name = test_class.__name__
>     # Parse test method specifiers if exist.
> ```

Like in `base_test`, "test case" -> "test" in this file too unless it's referring to the actual function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/210)*

**Comment by adorokhine** [comment]
Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[mobly/base_test.py, line 167 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNW1wRnmFlBMlHWCjo:-KkNhuyNxSRyQ14PZHtp:b-896fix) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/base_test.py#L167)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"test"
</blockquote></details>

Done.

---

*[mobly/base_test.py, line 402 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNWCos2_RJJhw5NW8C:-KkNhy6B11VL3JwOZ-g9:b-896fix) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/base_test.py#L402)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"improve scalability"?
</blockquote></details>

Done.

---

*[mobly/config_parser.py, line 88 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNWNE6ZfxRVD_S3iwj:-KkNlYKIqY-i3Eg5XrP9:b-896fix) ([raw file](https://github.com/google/mobly/blob/092d02c17b60c5e7e6d0594687ffa9d9c1711ed8/mobly/config_parser.py#L88)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why are these being removed here? seems completely unrelated to the context of this PR.
</blockquote></details>

Done.

---

*[mobly/suite_runner.py, line 58 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfYqUgTQCvqJGCpY1:-KkNiJSL0KwdnMU2CTH4:b-896fix) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/suite_runner.py#L58)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should this be "tests" since it's a list?
</blockquote></details>

Done.

---

*[mobly/suite_runner.py, line 63 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfepTGne0pfr93qLZ:-KkNiYkxFtrZtblPsg7q:b-62aipl) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/suite_runner.py#L63)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It should be "test class names", and test names" instead of "test methods" here right?
</blockquote></details>

I don't think so; this is literally a list of method names isn't it?

---

*[mobly/test_runner.py, line 67 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfx1-pvvksIyUglz9:-KkNiZfTEZg-1ddfvDKi:b-896fix) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L67)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should this be plural?
</blockquote></details>

Done.

---

*[mobly/test_runner.py, line 72 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfqVBzhP2YnpQydA2:-KkNigwDktZlsi7ZDlKT:b-u8jtbb) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L72)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This is a list of "test names" here?
</blockquote></details>

This is literally a list of test method names isn't it?

---

*[mobly/test_runner.py, line 89 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNg4kG2bw7D3-05FKY:-KkNinaP1-Sp2DWY4IE4:ben7p3c) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L89)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Like in `base_test`, "test case" -> "test" in this file too unless it's referring to the actual function.
</blockquote></details>

I think I've done that, haven't I? All remaining usages of `test method` refer to the name of an actual test method in the class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/210)*

**Comment by xpconanfan** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[mobly/suite_runner.py, line 63 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfepTGne0pfr93qLZ:-KkNmXnjO-KFyxZUl2Mw:b-y06m1u) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/suite_runner.py#L63)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I don't think so; this is literally a list of method names isn't it?
</blockquote></details>

these used to be referred to as names of the "test cases", so here they'd be "test names"?
They are not "test methods" here. Users are passing names here, not actual functions or classes.

---

*[mobly/test_runner.py, line 72 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfqVBzhP2YnpQydA2:-KkNmvbdTf1oB6eitnO4:b-e63xn9) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L72)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This is literally a list of test method names isn't it?
</blockquote></details>

The old arg is "test case" so these are names of "tests", not "test methods".

---

*[mobly/test_runner.py, line 89 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNg4kG2bw7D3-05FKY:-KkNnYTsPw_cI3zmwTT9:b-z07yt7) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L89)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I think I've done that, haven't I? All remaining usages of `test method` refer to the name of an actual test method in the class.
</blockquote></details>

I think we should use "test name" here.
These are identifiers that tells the runner which "tests" to run, not just which "test methods" to call.
Running a "test" means more than just executing a "test method".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/210)*

**Comment by adorokhine** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[mobly/suite_runner.py, line 63 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfepTGne0pfr93qLZ:-KkS3hs95zXH7FLJ8jKW:b-896fix) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/suite_runner.py#L63)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

these used to be referred to as names of the "test cases", so here they'd be "test names"?
They are not "test methods" here. Users are passing names here, not actual functions or classes.
</blockquote></details>

Done.

---

*[mobly/test_runner.py, line 72 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNfqVBzhP2YnpQydA2:-KkS41H04hCfbLdO0986:b-896fix) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L72)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

The old arg is "test case" so these are names of "tests", not "test methods".
</blockquote></details>

Done.

---

*[mobly/test_runner.py, line 89 at r2](https://reviewable.io:443/reviews/google/mobly/210#-KkNg4kG2bw7D3-05FKY:-KkS43Aqd0fjT9X-s5ZF:b-896fix) ([raw file](https://github.com/google/mobly/blob/f8d0a86c166ead8050449ee3194a384c35609d13/mobly/test_runner.py#L89)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I think we should use "test name" here.
These are identifiers that tells the runner which "tests" to run, not just which "test methods" to call.
Running a "test" means more than just executing a "test method".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/210)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/210#-:-KkSAO9VWCyUjXkF_0Ae:bnfp4nl)*

**Pull request merged**
