### PR TITLE
Remove deprecated code path for generated tests.

### PR DESCRIPTION
**Pull request by xpconanfan**
As planned for release 1.5, we are removing the old code path for
generated tests.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/242)

### CODE REVIEW

**Comment by kdart** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/242#-:-KoURRK06zvD_TgWtLOt:bnfp4nl)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/242#-KoURqupr7IWFkqkirHc:-KoURqupr7IWFkqkirHd:b-k9cmru) ([raw file](https://github.com/google/mobly/blob/310791d8d2faa9f554fddb0a5ce11ae249156bb4/mobly/base_test.py#L429)):*
> ```Python
>             self._generated_test_table[test_name] = test_func
> 
>     def run_generated_testcases(self,
> ```

There's some generated test stuff in signals too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/242)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/base_test.py, line 429 at r1](https://reviewable.io:443/reviews/google/mobly/242#-KoURqupr7IWFkqkirHc:-KoUSSa4L1bqtI6Kg2dC:b-896fix) ([raw file](https://github.com/google/mobly/blob/310791d8d2faa9f554fddb0a5ce11ae249156bb4/mobly/base_test.py#L429)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

There's some generated test stuff in signals too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/242)*

**Comment by adorokhine** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mobly/signals.py, line 80 at r2](https://reviewable.io:443/reviews/google/mobly/242#-KoUStp2sNSXtvVvgEtw:-KoUStp3ejAX00j-YHLL:b-85x5sm) ([raw file](https://github.com/google/mobly/blob/310791d8d2faa9f554fddb0a5ce11ae249156bb4/mobly/signals.py#L80)):*
> ```Python
> 
> 
> class TestSilent(TestSignal):
> ```

There's still a catch block for this deleted exception in base_test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/242)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/signals.py, line 80 at r2](https://reviewable.io:443/reviews/google/mobly/242#-KoUStp2sNSXtvVvgEtw:-KoUU0hc1qyaumZBz2Cf:b-896fix) ([raw file](https://github.com/google/mobly/blob/310791d8d2faa9f554fddb0a5ce11ae249156bb4/mobly/signals.py#L80)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

There's still a catch block for this deleted exception in base_test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/242)*

**Comment by adorokhine** [comment]
:lgtm:

Should this reference/fix #83?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/242#-:-KoUUlDLZRfUziEPrQpc:b-9b759m)*

**Pull request merged**
