### PR TITLE
Add an option to get the stderr of an adb command.

### LINKED ISSUE #435: Propagate stderr from adb commands
The current mobly adb proxy does not propagate stderr if ret code is zero.
We thought this was ok since Android has fixed return code issues in M.

But turns out many China manufacturers did not fix this in China devices.
In order to better support China devices and potentially other devices of the same ret code problem, we need to surface stderr.

### PR DESCRIPTION
**Pull request by xpconanfan**
Minor refactoring of `adb_test`
Fixes #435

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/437)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[mobly/controllers/android_device_lib/adb.py, line 279 at r1](https://beta.reviewable.io/reviews/google/mobly/437#-LAIsFf7-05sU6C6Hx5K:-LAIsFf7-05sU6C6Hx5L:b1zt8o6) ([raw file](https://github.com/google/mobly/blob/93853c8ba9cc06560e500141a68f3fa9039824ab/mobly/controllers/android_device_lib/adb.py#L279)):*
> ```Python
> 
>     def __getattr__(self, name):
>         def adb_call(args=None, shell=False, timeout=None, return_all=False):
> ```

I'm not a huge fan of signatures changing based on a flag. Is there a way we can make this an init-level setting instead of per-call?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/437)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 279 at r1](https://beta.reviewable.io/reviews/google/mobly/437#-LAIsFf7-05sU6C6Hx5K:-LAIv4JN3Pnm3xAhzfbd:bwk8scm) ([raw file](https://github.com/google/mobly/blob/93853c8ba9cc06560e500141a68f3fa9039824ab/mobly/controllers/android_device_lib/adb.py#L279)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I'm not a huge fan of signatures changing based on a flag. Is there a way we can make this an init-level setting instead of per-call?
</blockquote></details>

I thought of the same thing initially.
However that wouldn't work since that'll break any util that makes adb calls and expect a single output, which is quite a lot.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/437)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 279 at r1](https://beta.reviewable.io/reviews/google/mobly/437#-LAIsFf7-05sU6C6Hx5K:-LASRC_P0nIhJA6oSbuz:b-896fix) ([raw file](https://github.com/google/mobly/blob/93853c8ba9cc06560e500141a68f3fa9039824ab/mobly/controllers/android_device_lib/adb.py#L279)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I thought of the same thing initially.
However that wouldn't work since that'll break any util that makes adb calls and expect a single output, which is quite a lot.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/google/mobly/437)*

**Comment by k2fong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device_lib/adb.py, line 180 at r2](https://reviewable.io/reviews/google/mobly/437#-LAxdWSb9-VLwvRvALDx:-LAxdWSb9-VLwvRvALDy:b-emzufr) ([raw file](https://github.com/google/mobly/blob/2b485638ea9ddaa5b605df63534d08737dcbd9b6/mobly/controllers/android_device_lib/adb.py#L180)):*
> ```
> return out, err
> ```
is returning err still needed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/437)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 180 at r2](https://reviewable.io/reviews/google/mobly/437#-LAxdWSb9-VLwvRvALDx:-LAxxMaa7wsMOR8LS4nP:b-66j40e) ([raw file](https://github.com/google/mobly/blob/2b485638ea9ddaa5b605df63534d08737dcbd9b6/mobly/controllers/android_device_lib/adb.py#L180)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

> ```
> return out, err
> ```
is returning err still needed?
</blockquote></details>

My thinking is, if return both here as part of this change, we are set if we ever need stderr...

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/437)*

**Comment by k2fong** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 180 at r2](https://reviewable.io/reviews/google/mobly/437#-LAxdWSb9-VLwvRvALDx:-LAxcRhc2sYqq6Chi8NV:be47n8l) ([raw file](https://github.com/google/mobly/blob/2b485638ea9ddaa5b605df63534d08737dcbd9b6/mobly/controllers/android_device_lib/adb.py#L180)):*
> ```
> return out, err
> ```
probably nit but I would suggest leaving it out till we until we actually need it, as it might lead to confusion why there are two paths to get stderr in the future when someone else looks at it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/437#-:-LAycCym32jYJEk8BiZO:bnfp4nl)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 180 at r2](https://reviewable.io/reviews/google/mobly/437#-LAxdWSb9-VLwvRvALDx:-LAyehS35J6KjCgY-_Q4:bylpo6k) ([raw file](https://github.com/google/mobly/blob/2b485638ea9ddaa5b605df63534d08737dcbd9b6/mobly/controllers/android_device_lib/adb.py#L180)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

> ```
> return out, err
> ```
probably nit but I would suggest leaving it out till we until we actually need it, as it might lead to confusion why there are two paths to get stderr in the future when someone else looks at it.
</blockquote></details>

I agree with Peter.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/437)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/adb.py, line 180 at r2](https://reviewable.io/reviews/google/mobly/437#-LAxdWSb9-VLwvRvALDx:-LAz-8p9EaUEHCmH2aoZ:b-896fix) ([raw file](https://github.com/google/mobly/blob/2b485638ea9ddaa5b605df63534d08737dcbd9b6/mobly/controllers/android_device_lib/adb.py#L180)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I agree with Peter.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly/437)*

**Pull request merged**
