### PR TITLE
Changing Mobly to use portpicker 

### PR DESCRIPTION
**Pull request by malvarezrohena**
Making mobly use portpicker instead of picking random port.

Note: I am not sure if after this change you still need the list_occupied_adb_ports logic in is_port_available.  I am guessing yes, because you dont know if other processes running in the same machine are picking the same portsw that portserver allocates for you. 

We probably need also some documentation about portpicker/portserver

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/185)

### CODE REVIEW

**Comment by malvarezrohena** [comment]
I signed it!

**Comment by xpconanfan** [comment]
Do we know if portpicker works well in py3 and Windows?

**Comment by malvarezrohena** [comment]
They Claim it works with Py3 https://github.com/google/python_portpicker, I
am reading to see if it works on windows.  Havent found anything yet

**Comment by xpconanfan** [comment]
Alex has a windows machine, maybe he could try it there

**Comment by malvarezrohena** [comment]
Sounds like a good idea to try it on a windows machine, the portpicker page doesn't say anything about Windows, and it includes a port server which says that listens on a Unix socket.  Maybe the port server only works on Linux/Unix? 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185#-:-Khy483VkQ9QS7HKETke:b528igl)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/utils.py, line 453 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDBKEe7OhRFq4eZM5:-KhyDBKFNSHgO_9m5MVj:b-l6e96w) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L453)):*
> ```Python
> 
> 
> def get_available_host_port():
> ```

Can you add a unit test for this method? (eg get an available host_port, use is_port_available to check if it's really free).

Then I can easily try it on Windows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/utils.py, line 481 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDWIGqfQBEyr7N6-_:-KhyDWIHO9HT5fzwwEDg:b-fp9853) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L481)):*
> ```Python
>     s = None
>     try:
>         s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
> ```

From reading the portpicker code, both the portserver and non-portserver code paths already check this. Maybe this method can just be reduced to checking against adb.list_occupied_ports (and renamed accordingly?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/utils.py, line 481 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDWIGqfQBEyr7N6-_:-KhyF4P17AaWfJDUtxdq:bvn8ey4) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L481)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

From reading the portpicker code, both the portserver and non-portserver code paths already check this. Maybe this method can just be reduced to checking against adb.list_occupied_ports (and renamed accordingly?)
</blockquote></details>

Sounds like we could simply remove this function or merge the portpicker line into it and rename accordingly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/utils.py, line 481 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDWIGqfQBEyr7N6-_:-Ki1LzW55IAZFjPVqlws:b3id84n) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L481)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Sounds like we could simply remove this function or merge the portpicker line into it and rename accordingly?
</blockquote></details>

So we are removing everything inside this try/finally statement, cause its already done in portpicker.  Doing the change now and adding the unit test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by xpconanfan** [comment]
Unit tests are failing, please fix.
You can check by running `$ python setup.py test`

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185#-:-Ki1V-fRn8KzbyG5fvqF:b-hkoxs0)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tests/mobly/utils_test.py, line 48 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kF7IlUobs-py_FUN:-Ki2kF7J-fCEpbdqpLvB:bmfa264) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/tests/mobly/utils_test.py#L48)):*
> ```Python
>     @mock.patch('mobly.controllers.android_device_lib.adb.list_occupied_adb_ports')
>     def test_get_available_port_positive(self, mock_list_occupied_adb_ports):
>         with mock.patch.object(portpicker, 'PickUnusedPort', return_value=AVAILABLE_PORT):
> ```

You could patch object with a decorator.
Let's do that to be consistent with the regular `mock.patch`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mobly/utils.py, line 456 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kky8ka1KTDmudT5N:-Ki2kky8ka1KTDmudT5O:bc69vjs) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L456)):*
> ```Python
> 
> def get_available_host_port():
>     """Gets a host port number available for adb forward.
> ```

please update the docstring of this function with the new behavior

---

*[mobly/utils.py, line 463 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kcDkQ7QowRqlzIAK:-Ki2kcDkQ7QowRqlzIAL:bv9y1ov) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L463)):*
> ```Python
>     """
>     i = 0
>     while i < MAX_RETRY:
> ```

How about `for _ in range(MAX_RETRY)` instead?

---

*[mobly/utils.py, line 470 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kSO_HCioMEaMhyDq:-Ki2kSO_HCioMEaMhyDr:b-uf17d8) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L470)):*
> ```Python
>             return port
>     raise Error('Failed to find available port after {} retries'.
>                 format(MAX_RETRY))
> ```

Use `%` to format string instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[mobly/utils.py, line 37 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2mNKB535dtxNQjnVQ:-Ki2mNKB535dtxNQjnVR:b-milz6m) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L37)):*
> ```Python
> MAX_FILENAME_LEN = 255
> # Number of times to retry to get available port
> MAX_RETRY = 50
> ```

Since the file is a general util file, the name `MAX_RETRY` seems kind of ambiguous. Do you want to call it something like `MAX_PORT_ALLOCATION_RETRY`?

---

*[mobly/utils.py, line 456 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kky8ka1KTDmudT5N:-Ki2mYwwx21ZQ1Oa5JZQ:bvc2h2l) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L456)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

please update the docstring of this function with the new behavior
</blockquote></details>

@Ang What's incorrect about the old docstring? The new behaviour seems the same as the old behaviour unless a portserver is used so the text still seems valid to me?

---

*[mobly/utils.py, line 464 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2miNzUM-vTTDx2Hk1:-Ki2miNzUM-vTTDx2Hk2:b-kr2j44) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L464)):*
> ```Python
>     i = 0
>     while i < MAX_RETRY:
>         port = portpicker.PickUnusedPort()        
> ```

Trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by xpconanfan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[mobly/utils.py, line 456 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kky8ka1KTDmudT5N:-Ki2ptw9r6J6p81u0BDl:b7i8hoh) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L456)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

@Ang What's incorrect about the old docstring? The new behaviour seems the same as the old behaviour unless a portserver is used so the text still seems valid to me?
</blockquote></details>

I was hoping for more details like it now has a max retry and raises `Error` if no port can be found.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by xpconanfan** [comment]
Also, unit test is still broken, pls fix

---

Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185#-:-Ki3Tfu9c4u34H__KzMM:bwhr1bb)*

**Comment by malvarezrohena** [comment]
@xpconanfan for the raise error in utils.py, you said to use % format, but the rest of the file is using .format to format strings.  Dont we want to maintain uniformity?

**Comment by xpconanfan** [comment]
Huh, I didn't realize utils.py is still on old convention, sorry...
Yeah, let's keep it consistent then.

**Comment by malvarezrohena** [comment]
@xpconanfan python setup.py tests says all 137 tests passed.   I am running "python setup.py tests"  which test do you see failing

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mobly/utils.py, line 453 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDBKEe7OhRFq4eZM5:-Ki6KCJJ9sXKM3outzqK:bmukci1) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L453)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can you add a unit test for this method? (eg get an available host_port, use is_port_available to check if it's really free).

Then I can easily try it on Windows.
</blockquote></details>

Alex: could you run on windows now?

---

*[mobly/utils.py, line 461 at r3](https://reviewable.io:443/reviews/google/mobly/185#-Ki6Ji9TGd_A-IbYJdtK:-Ki6Ji9TGd_A-IbYJdtL:b-lbj0xi) ([raw file](https://github.com/google/mobly/blob/f067527ff5f4a7df1781be879da6ccd4b78d2a83/mobly/utils.py#L461)):*
> ```Python
>         An integer representing a port number on the host available for adb
>         forward.
>     Raises:
> ```

missing an empty line between Returns and Raises sections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
Done

**Comment by xpconanfan** [comment]
Pls rebase :)

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185#-:-Ki6RYuT6l3TejHgFPFY:b-ijn34z)*

**Comment by malvarezrohena** [comment]
Done, let me know if I didn't do it right :) 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185#-:-Ki6YuBrgptT2pbDMMBC:b65pfhy)*

**Comment by malvarezrohena** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[mobly/utils.py, line 453 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDBKEe7OhRFq4eZM5:-Ki6JEn3fjD7Y210XuPK:b-896fix) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L453)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can you add a unit test for this method? (eg get an available host_port, use is_port_available to check if it's really free).

Then I can easily try it on Windows.
</blockquote></details>

Done.

---

*[mobly/utils.py, line 481 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDWIGqfQBEyr7N6-_:-Ki6JEIErWz9DCMDZ9W2:b-896fix) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L481)):*
<details><summary><i>Previously, malvarezrohena wrote…</i></summary><blockquote>

So we are removing everything inside this try/finally statement, cause its already done in portpicker.  Doing the change now and adding the unit test
</blockquote></details>

Done.

---

*[mobly/utils.py, line 37 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2mNKB535dtxNQjnVQ:-Ki6JC_BJdvYWz1ghfQt:b-896fix) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L37)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Since the file is a general util file, the name `MAX_RETRY` seems kind of ambiguous. Do you want to call it something like `MAX_PORT_ALLOCATION_RETRY`?
</blockquote></details>

Done.

---

*[mobly/utils.py, line 456 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kky8ka1KTDmudT5N:-Ki6JD8V67IjenB6ewo3:b-896fix) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L456)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I was hoping for more details like it now has a max retry and raises `Error` if no port can be found.
</blockquote></details>

Done.

---

*[mobly/utils.py, line 463 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kcDkQ7QowRqlzIAK:-Ki6JE-AI3UOSQPyJVlP:b-896fix) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L463)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

How about `for _ in range(MAX_RETRY)` instead?
</blockquote></details>

Done.

---

*[mobly/utils.py, line 464 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2miNzUM-vTTDx2Hk1:-Ki6JDWua2muJtSzYPS8:b-896fix) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L464)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Done.

---

*[mobly/utils.py, line 470 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kSO_HCioMEaMhyDq:-Ki6JHLX3wPpJ9ETWwGp:b9lz6za) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/mobly/utils.py#L470)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Use `%` to format string instead.
</blockquote></details>

keeping this way for consistency

---

*[tests/mobly/utils_test.py, line 48 at r2](https://reviewable.io:443/reviews/google/mobly/185#-Ki2kF7IlUobs-py_FUN:-Ki6JM_6nD9SdM0m_OBd:b-896fix) ([raw file](https://github.com/google/mobly/blob/4870d27c498060905e73d1ae8b02315b79ae3d13/tests/mobly/utils_test.py#L48)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

You could patch object with a decorator.
Let's do that to be consistent with the regular `mock.patch`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by xpconanfan** [comment]
Looks like there are still merge conflicts.

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/utils.py, line 453 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDBKEe7OhRFq4eZM5:-Ki7YPwUxD5g0y6oPyaY:b-2iawpr) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L453)):*
<details><summary><i>Previously, malvarezrohena wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think the current unit test would actually expose any bugs; see concerns below.

---

*[mobly/utils.py, line 414 at r5](https://reviewable.io:443/reviews/google/mobly/185#-Ki7YVGosLctIygGlLFP:-Ki7YVGosLctIygGlLFQ:b-c0uppz) ([raw file](https://github.com/google/mobly/blob/5ec5b3ffd95bb977fb4b00179ea37d9d2e35a749/mobly/utils.py#L414)):*
> ```Python
> 
>     Raises:
>       Error is raised when no port is found after
> ```

Error: when no port is found after...

---

*[tests/mobly/utils_test.py, line 49 at r5](https://reviewable.io:443/reviews/google/mobly/185#-Ki7Yoo2Pcp4c6sCN3Kr:-Ki7Yoo2Pcp4c6sCN3Ks:bktps4c) ([raw file](https://github.com/google/mobly/blob/5ec5b3ffd95bb977fb4b00179ea37d9d2e35a749/tests/mobly/utils_test.py#L49)):*
> ```Python
>     @mock.patch(
>         'mobly.controllers.android_device_lib.adb.list_occupied_adb_ports')
>     @mock.patch('portpicker.PickUnusedPort', return_value=AVAILABLE_PORT)
> ```

If you mock out portpicker in this test, the unit test essentially becomes a check that we call the mock and return its value. Doesn't seem very valuable to me. In particular, whether or not it passes on Windows doesn't give us any information about whether the portpicker approach works on that OS not. Also if something breaks and we start returning bound ports, it won't catch it either.

Seems like we shouldn't be mocking this out, but just getting a real port and then making sure it's really free (can be bound) like we were doing before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
@adorokhine What you are asking for is not an unit test, that is more like an integration test.  And the integration test wouldnt test get_available_host_port, but that portpicker work on windows and does the right thing.  Can you run the portpicker tests on your windows machine?

**Comment by adorokhine** [comment]
Looks good and seems to work! Thanks! Leaving final approval to Ang.

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185#-:-KiXkSYVaT9K8Q5Uxzbe:bu20hhp)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185#-:-KiXkW_09QcJLHkzU3Fc:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/mobly/utils_test.py, line 23 at r6](https://reviewable.io:443/reviews/google/mobly/185#-KiYG_SsSzAFxVGy8pIz:-KiYG_SsSzAFxVGy8pJ-:b-8dgvnl) ([raw file](https://github.com/google/mobly/blob/e66ac37d848439316767e2252eff18497cd9df4e/tests/mobly/utils_test.py#L23)):*
> ```Python
> from mobly import utils
> 
> AVAILABLE_PORT = 5
> ```

This should be named `MOCK_AVAILABLE_PORT`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
*[tests/mobly/utils_test.py, line 49 at r5](https://reviewable.io:443/reviews/google/mobly/185#-Ki7Yoo2Pcp4c6sCN3Kr:-Ki_yk770RGnrvoEy_32:bt6a928) ([raw file](https://github.com/google/mobly/blob/5ec5b3ffd95bb977fb4b00179ea37d9d2e35a749/tests/mobly/utils_test.py#L49)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

If you mock out portpicker in this test, the unit test essentially becomes a check that we call the mock and return its value. Doesn't seem very valuable to me. In particular, whether or not it passes on Windows doesn't give us any information about whether the portpicker approach works on that OS not. Also if something breaks and we start returning bound ports, it won't catch it either.

Seems like we shouldn't be mocking this out, but just getting a real port and then making sure it's really free (can be bound) like we were doing before.
</blockquote></details>

Added extra test to make sure portpicker does the right thing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
*[tests/mobly/utils_test.py, line 49 at r5](https://reviewable.io:443/reviews/google/mobly/185#-Ki7Yoo2Pcp4c6sCN3Kr:-Ki_ypfyPnRMrjRxpqkd:b-896fix) ([raw file](https://github.com/google/mobly/blob/5ec5b3ffd95bb977fb4b00179ea37d9d2e35a749/tests/mobly/utils_test.py#L49)):*
<details><summary><i>Previously, malvarezrohena wrote…</i></summary><blockquote>

Added extra test to make sure portpicker does the right thing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
*[mobly/utils.py, line 461 at r3](https://reviewable.io:443/reviews/google/mobly/185#-Ki6Ji9TGd_A-IbYJdtK:-Ki6xiNFcARMoPjxxcUw:b-896fix) ([raw file](https://github.com/google/mobly/blob/f067527ff5f4a7df1781be879da6ccd4b78d2a83/mobly/utils.py#L461)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

missing an empty line between Returns and Raises sections.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/utils.py, line 414 at r5](https://reviewable.io:443/reviews/google/mobly/185#-Ki7YVGosLctIygGlLFP:-Ki_zUp6tSpwBZ6aKNkL:b-896fix) ([raw file](https://github.com/google/mobly/blob/5ec5b3ffd95bb977fb4b00179ea37d9d2e35a749/mobly/utils.py#L414)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Error: when no port is found after...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
*[tests/mobly/utils_test.py, line 23 at r6](https://reviewable.io:443/reviews/google/mobly/185#-KiYG_SsSzAFxVGy8pIz:-Ki_zeSU1OPIEkwDtuQo:b-896fix) ([raw file](https://github.com/google/mobly/blob/e66ac37d848439316767e2252eff18497cd9df4e/tests/mobly/utils_test.py#L23)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This should be named `MOCK_AVAILABLE_PORT`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Comment by malvarezrohena** [comment]
*[mobly/utils.py, line 453 at r1](https://reviewable.io:443/reviews/google/mobly/185#-KhyDBKEe7OhRFq4eZM5:-Ki_zhCFE9LAa6ypeu5w:bu3cf8s) ([raw file](https://github.com/google/mobly/blob/2fba51fbbed95f3ba735417c8d8ea0999e177372/mobly/utils.py#L453)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I don't think the current unit test would actually expose any bugs; see concerns below.
</blockquote></details>

Thanks for running on windows

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/185)*

**Pull request merged**
