### PR TITLE
Minor fixes for new output format.

### PR DESCRIPTION
**Pull request by xpconanfan**
#41

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/273)

### CODE REVIEW

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 93 at r1](https://reviewable.io:443/reviews/google/mobly/273#-Kq9QEMi6YtLzvopR-XR:-Kq9QEMi6YtLzvopR-XS:bbws2vu) ([raw file](https://github.com/google/mobly/blob/a4258b27ce39b77271222b4c0dbf77bce11d868b/mobly/records.py#L93)):*
>         content_str = yaml.safe_dump(
>             new_content, explicit_start=True, indent=4)
is there some specific reason why not just use dump() or now safe_dump() to stream output to a file directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/273)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 93 at r1](https://reviewable.io:443/reviews/google/mobly/273#-Kq9QEMi6YtLzvopR-XR:-Kq9R4GJv22kGqRHwoSu:bmyh1lb) ([raw file](https://github.com/google/mobly/blob/a4258b27ce39b77271222b4c0dbf77bce11d868b/mobly/records.py#L93)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

>         content_str = yaml.safe_dump(
>             new_content, explicit_start=True, indent=4)
is there some specific reason why not just use dump() or now safe_dump() to stream output to a file directly?
</blockquote></details>

`yaml.dump` dumps language-specific tags, which do not affect parsing but is not human friendly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/273)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 93 at r1](https://reviewable.io:443/reviews/google/mobly/273#-Kq9QEMi6YtLzvopR-XR:-Kq9ReehKDUhSaCVUvDu:b-v6ymqz) ([raw file](https://github.com/google/mobly/blob/a4258b27ce39b77271222b4c0dbf77bce11d868b/mobly/records.py#L93)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`yaml.dump` dumps language-specific tags, which do not affect parsing but is not human friendly.
</blockquote></details>

Done.
Added a comment to explain

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/273)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 93 at r1](https://reviewable.io:443/reviews/google/mobly/273#-Kq9QEMi6YtLzvopR-XR:-Kq9RYUqFkshxjoTnlvV:bkkmh7j) ([raw file](https://github.com/google/mobly/blob/a4258b27ce39b77271222b4c0dbf77bce11d868b/mobly/records.py#L93)):*
> yaml.safe_dump(
>             new_content, explicit_start=True, indent=4)
Sorry, I was probably not clear, I meant this yaml.safe_dump(new_content, <file_handle>, explicit_start=True, indent=4) instead of having to write out the returned content.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/273)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/records.py, line 93 at r1](https://reviewable.io:443/reviews/google/mobly/273#-Kq9QEMi6YtLzvopR-XR:-Kq9T6kwIRhmtQxZfOnA:b-896fix) ([raw file](https://github.com/google/mobly/blob/a4258b27ce39b77271222b4c0dbf77bce11d868b/mobly/records.py#L93)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

> yaml.safe_dump(
>             new_content, explicit_start=True, indent=4)
Sorry, I was probably not clear, I meant this yaml.safe_dump(new_content, <file_handle>, explicit_start=True, indent=4) instead of having to write out the returned content.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/273)*

**Comment by k2fong** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/273#-:-Kq9UI92wVthjZgicQj0:bnfp4nl)*

**Pull request merged**
