### PR TITLE
Add a exception log line.

### PR DESCRIPTION
**Pull request by xpconanfan**
Follow up #325

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/337)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 731 at r1](https://reviewable.io:443/reviews/google/mobly/337#-KvEQsdIuhFM_BhFibZj:-KvEQsdJhIHQUzrxU0UN:b-1c7a1k) ([raw file](https://github.com/google/mobly/blob/bf58b9bfdbf836e7db7b22b0f127c0def5b63c48/mobly/controllers/android_device.py#L731)):*
> ```Python
>             client.start_app_and_connect()
>         except Exception as e:
>             self.log.exception('Failed to start app and connect.')
> ```

Possibly add a comment here that this is to log the original stack?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/337)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 731 at r1](https://reviewable.io:443/reviews/google/mobly/337#-KvEQsdIuhFM_BhFibZj:-KvERAKoFGiI4A9M0sFN:bmmvfyo) ([raw file](https://github.com/google/mobly/blob/bf58b9bfdbf836e7db7b22b0f127c0def5b63c48/mobly/controllers/android_device.py#L731)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Possibly add a comment here that this is to log the original stack?
</blockquote></details>

That seems redundant, this code is pretty self explanatory...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/337)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 731 at r1](https://reviewable.io:443/reviews/google/mobly/337#-KvEQsdIuhFM_BhFibZj:-KvEm2ml25xOgVd49kFh:bssuyzk) ([raw file](https://github.com/google/mobly/blob/bf58b9bfdbf836e7db7b22b0f127c0def5b63c48/mobly/controllers/android_device.py#L731)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

That seems redundant, this code is pretty self explanatory...
</blockquote></details>

Not really, we've removed what seem like duplicate logs in the past. Seeing as this helps with a recurring mystery, it would be nice if it stayed here until we actually find the root cause. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/337)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 731 at r1](https://reviewable.io:443/reviews/google/mobly/337#-KvEQsdIuhFM_BhFibZj:-KvEosps5IVj-xIFi8yE:b-896fix) ([raw file](https://github.com/google/mobly/blob/bf58b9bfdbf836e7db7b22b0f127c0def5b63c48/mobly/controllers/android_device.py#L731)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Not really, we've removed what seem like duplicate logs in the past. Seeing as this helps with a recurring mystery, it would be nice if it stayed here until we actually find the root cause. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/337)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/337#-:-KvEp518zAeTxInWSlP4:bnfp4nl)*

**Pull request merged**
