### PR TITLE
Include a debug hint in snippet client error message.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/731)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/731)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @xpconanfan)

___
*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 97 at r1](https://reviewable.io/reviews/google/mobly/731#-MVZzV8k9pCbJhd0nfch:-MVZzV8k9pCbJhd0nfci:bqdujir) ([raw file](https://github.com/google/mobly/blob/f1c8f58fb51054974c4717ae6d876d20e1832a81/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L97)):*
> ```
>   NO_RESPONSE_FROM_SERVER = 'No response from server. Check the device logcat '
>   'for crashes.'
> ```
How about write it in this way, maybe more easy to read:
```
  NO_RESPONSE_FROM_SERVER = ('No response from server. '
                             'Check the device logcat for crashes.')
```

**Review by xpconanfan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/731)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 97 at r1](https://reviewable.io/reviews/google/mobly/731#-MVZzV8k9pCbJhd0nfch:-MV_-g14-OCu5KIN93aQ:b-896fix) ([raw file](https://github.com/google/mobly/blob/f1c8f58fb51054974c4717ae6d876d20e1832a81/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L97)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
>   NO_RESPONSE_FROM_SERVER = 'No response from server. Check the device logcat '
>   'for crashes.'
> ```
How about write it in this way, maybe more easy to read:
```
  NO_RESPONSE_FROM_SERVER = ('No response from server. '
                             'Check the device logcat for crashes.')
```
</blockquote></details>

Done.

**Review by eric100lin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/731#-:-MV_-l5d66vZ1YR3GtBw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eric100lin)

**Review by eric100lin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/731)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xpconanfan)

**Comment by xpconanfan** [comment]
Force pushing because travis-ci service is broken

**Pull request merged**
