### PR TITLE
Added ability to detect if usb disconnects

### PR DESCRIPTION
**Pull request by k2fong**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/265)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpGtEKQlk9QXVBEzO9W:b-t96j86) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
> ```Python
>         self._wait_for_device(self._is_adb_detectable, timeout)
> 
>     def wait_for_adb_detached(self, timeout=DEFAULT_TIMEOUT_USB_OFF):
> ```

Why do you need to call these two "private" methods?
Is there something you need to do but could not with the current implementation of device disconnect support?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpGuwX17UITjcdnSzKQ:b-t8r7u1) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Why do you need to call these two "private" methods?
Is there something you need to do but could not with the current implementation of device disconnect support?
</blockquote></details>

I needed a wait on adb/usb disconnecting.  I could potentially implement this outside Mobly but I thought this might be a fitting functionality for the android_device.py.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpGwPgTeSXSD-uXfkqF:b-pc0xpy) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

I needed a wait on adb/usb disconnecting.  I could potentially implement this outside Mobly but I thought this might be a fitting functionality for the android_device.py.
</blockquote></details>

Seems like you could simply use `self.wait_for_boot_completion`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpH7eAgu0Y49IrnKOeR:b-x4km3f) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Seems like you could simply use `self.wait_for_boot_completion`?
</blockquote></details>

hmm, I don't think that fits for my need?  I basically needed the reverse of wait_for_adb_detection()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpHuafKPB7fKzEYDG8i:b4ajg4n) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

hmm, I don't think that fits for my need?  I basically needed the reverse of wait_for_adb_detection()
</blockquote></details>

you want to wait for the device to disconnect from adb and time out if it doesn't?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpLTDSzRB0CR3xM-RVV:b-flnrgp) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

you want to wait for the device to disconnect from adb and time out if it doesn't?
</blockquote></details>

Yes, that is correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpLTnonOxUF8KoHDxN1:b-7tsz4j) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

Yes, that is correct
</blockquote></details>

`self._wait_for_device` is really a retry loop with timeout.
Its name is misleading, and its implementation is flawed.
I've filed a bug tracking this #266 

Do you want to wait for that change?

I'm not sure about added more of these incorrectly implemented methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpSuPehHvaUIK0FHYfD:b7qw7df) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`self._wait_for_device` is really a retry loop with timeout.
Its name is misleading, and its implementation is flawed.
I've filed a bug tracking this #266 

Do you want to wait for that change?

I'm not sure about added more of these incorrectly implemented methods.
</blockquote></details>

Do you have an estimate of when this fix might be in?  Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpaBG2oB3WvDNPxGfLu:bhrhrje) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

Do you have an estimate of when this fix might be in?  Thanks
</blockquote></details>

That's up to @l-meng

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by l-meng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpaK63r9O-ZTdSY72or:bvou0x6) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
> it_for_device is really a retry loop with tim

One of the issues #266 tries to fix, which impacts this PR, is that: self._wait_for_device does not exactly follow the user specified timeout parameter, if and only if self.adb.wait_for_device() takes considerable amount of time to complete (or potentially it is blocking forever).

I didn't see it happens in USB re-connect so far, but it might be more likely to happen for reboot case (I don't have a proof how likely or under what conditions that self.adb.wait_for_device()  won't return)

Please let me know how much #266 will be blocking this PR, I think it is not a blocker for this PR.
(if in the real tests we ever see cases that self.adb.wait_for_device() blocking, or breaking the timeout contract, we will have bugs opened by those test owners, but haven't seen any so far)

But I'll fix it anyway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpaVrWJC-FCA5p8zNfR:b-2f8s4i) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

> it_for_device is really a retry loop with tim

One of the issues #266 tries to fix, which impacts this PR, is that: self._wait_for_device does not exactly follow the user specified timeout parameter, if and only if self.adb.wait_for_device() takes considerable amount of time to complete (or potentially it is blocking forever).

I didn't see it happens in USB re-connect so far, but it might be more likely to happen for reboot case (I don't have a proof how likely or under what conditions that self.adb.wait_for_device()  won't return)

Please let me know how much #266 will be blocking this PR, I think it is not a blocker for this PR.
(if in the real tests we ever see cases that self.adb.wait_for_device() blocking, or breaking the timeout contract, we will have bugs opened by those test owners, but haven't seen any so far)

But I'll fix it anyway




</blockquote></details>

Because this PR is adding new public APIs, it'll be difficult to deprecate later...

If we rename and refactor `_wait_for_device` to be a proper retry function, we don't need to add this public API.

The user just need to do something like `wait_until(lambda ad : not ad.is_adb_detectable(), timeout)`.

This way we don't have to add a new public API every time somebody needs the `not` of a signal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpqXPF6q0YVnN12XcKM:b-s5lscd) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Because this PR is adding new public APIs, it'll be difficult to deprecate later...

If we rename and refactor `_wait_for_device` to be a proper retry function, we don't need to add this public API.

The user just need to do something like `wait_until(lambda ad : not ad.is_adb_detectable(), timeout)`.

This way we don't have to add a new public API every time somebody needs the `not` of a signal.

</blockquote></details>

@l-meng, #266 is not technically blocking this PR.  But sounds like it might be better to hold off this PR until #266 gets implemented.  And at which point if we implement something like the wait_until() suggested, this PR probably will be obsolete.  What is blocking for me is this ability to wait and detect for disconnect.  So what I'm wondering now is if I should wait for #266 or have a workaround outside Mobly for now.  Do you have an idea when the fix for #266 will get in?  Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Comment by l-meng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 949 at r1](https://reviewable.io:443/reviews/google/mobly/265#-KpGtEKQlk9QXVBEzO9V:-KpuqKdOwoPxWQP_e3ui:bvh3x9m) ([raw file](https://github.com/google/mobly/blob/88b73ceee1c22c291a7d3a59c3a00b37fd8a9f1d/mobly/controllers/android_device.py#L949)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

@l-meng, #266 is not technically blocking this PR.  But sounds like it might be better to hold off this PR until #266 gets implemented.  And at which point if we implement something like the wait_until() suggested, this PR probably will be obsolete.  What is blocking for me is this ability to wait and detect for disconnect.  So what I'm wondering now is if I should wait for #266 or have a workaround outside Mobly for now.  Do you have an idea when the fix for #266 will get in?  Thanks.
</blockquote></details>

working on this. If the scope does not change, should be ready in a few days.
If you can't wait for that, you could do it in your change and migrate once this is merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/265)*

**Pull request closed without merging**
