### PR TITLE
Add an --mbs flag to snippet_shell to avoid having to remember the package.

### PR DESCRIPTION
**Pull request by adorokhine**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/200)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjLaJkGW9zDRv6RskTL:b-udq94k) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
> ```Python
> from mobly.controllers.android_device_lib import jsonrpc_shell_base
> 
> MBS_PACKAGE = 'com.google.android.mobly.snippet.bundled'
> ```

Is it possible to put this in a place where the snippet client could use as well?
This way ppl can use this instead of hard code the actual string in their tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjLda8KgORpZwgsgwcV:b-whfzfi) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Is it possible to put this in a place where the snippet client could use as well?
This way ppl can use this instead of hard code the actual string in their tests.
</blockquote></details>

Moved to `snippet_client.py`; is that what you meant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 21 at r2](https://reviewable.io:443/reviews/google/mobly/200#-KjLf9MCxacpOAUPymdh:-KjLf9MCxacpOAUPymdi:bpwc7be) ([raw file](https://github.com/google/mobly/blob/fbb9d6042d95fd87d69c3c26c96243c06a48d426/mobly/controllers/android_device_lib/snippet_client.py#L21)):*
> ```Python
> from mobly.controllers.android_device_lib import jsonrpc_client_base
> 
> # Convenience constant for the package of Mobly Bundled Snippets.
> ```

Should we add a link to MBS repo in the comment?
No strong preference

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjLefaJ35bCinawM5dr:b-50o7z4) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Moved to `snippet_client.py`; is that what you meant?
</blockquote></details>

Hmm, do you think we need a `mobly.const` module?
It seems a bit odd having to import snippet_client module just to get this constant.
Or maybe we could add an alias for this constant in android_device?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjLfpw4MVeCW5XerRE-:brc7fjw) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, do you think we need a `mobly.const` module?
It seems a bit odd having to import snippet_client module just to get this constant.
Or maybe we could add an alias for this constant in android_device?
</blockquote></details>

No preference from my side; tell me what you'd like to see and I'll do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjLpJiMbJ45zxJozdp3:br3wsu8) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

No preference from my side; tell me what you'd like to see and I'll do it.
</blockquote></details>

Are you ok with doing this in `load_snippet`?
Like if `ad.load_snippet(xx, package='MBS')`, `ad.load_snippet(xx, mbs=True)`, `ad.load_snippet(xx')` or something along the line, we automatically load mbs package. Any option is fine with me.
This way no caller needs to do extra import.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjLrxJvbJmSFlY75099:bsxgo6s) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Are you ok with doing this in `load_snippet`?
Like if `ad.load_snippet(xx, package='MBS')`, `ad.load_snippet(xx, mbs=True)`, `ad.load_snippet(xx')` or something along the line, we automatically load mbs package. Any option is fine with me.
This way no caller needs to do extra import.

</blockquote></details>

`load_snippet` is a pretty generic method so I don't think it's a good idea to start adding mbs stuff to it, but how about a new `load_mbs()` method similar to the already existing `load_sl4a()`? It can just call `load_snippet` under the hood.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjM1Ex6W3pmSVIk_CBD:b-9ccb35) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

`load_snippet` is a pretty generic method so I don't think it's a good idea to start adding mbs stuff to it, but how about a new `load_mbs()` method similar to the already existing `load_sl4a()`? It can just call `load_snippet` under the hood.
</blockquote></details>

I was actually hoping to get rid of the `load_sl4a` thing. I don't like special functions in AndroidDevice for specific apks, like how we don't have `register_android_device` in addition to `register_controller` in `test_runner`.

How does this look:
```
ad.load_snippet(android_device.PACKAGE_SNIPPET)

# and maybe one day:
ad.load_snippet(android_device.PACKAGE_SL4A)
```

This way at least the tests don't have to import something extra

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjMLdXs3PsG7FKb5VuS:b5v10co) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I was actually hoping to get rid of the `load_sl4a` thing. I don't like special functions in AndroidDevice for specific apks, like how we don't have `register_android_device` in addition to `register_controller` in `test_runner`.

How does this look:
```
ad.load_snippet(android_device.PACKAGE_SNIPPET)

# and maybe one day:
ad.load_snippet(android_device.PACKAGE_SL4A)
```

This way at least the tests don't have to import something extra
</blockquote></details>

Since sl4a and snippet need separate code paths anyway, why even use the package name as the constant? Any string constant would do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/snippet_shell.py, line 35 at r1](https://reviewable.io:443/reviews/google/mobly/200#-KjLaJkGW9zDRv6RskTK:-KjPP2msL9z-uTeu_GXA:b-896fix) ([raw file](https://github.com/google/mobly/blob/b760ecb1772067bebe2383240584e2444d27286c/tools/snippet_shell.py#L35)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Since sl4a and snippet need separate code paths anyway, why even use the package name as the constant? Any string constant would do.
</blockquote></details>

Done.

---

*[mobly/controllers/android_device_lib/snippet_client.py, line 21 at r2](https://reviewable.io:443/reviews/google/mobly/200#-KjLf9MCxacpOAUPymdh:-KjPP4C5nVq9J-VtwRCs:b-896fix) ([raw file](https://github.com/google/mobly/blob/fbb9d6042d95fd87d69c3c26c96243c06a48d426/mobly/controllers/android_device_lib/snippet_client.py#L21)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Should we add a link to MBS repo in the comment?
No strong preference
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/200#-:-KjPR2m1emH1tXfY6khL:bnfp4nl)*

**Pull request merged**
