### PR TITLE
Add a log when a device's debug tag changes.

### PR DESCRIPTION
**Pull request by adorokhine**
This helps correlate the old and new debug tags.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/196)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 411 at r1](https://reviewable.io:443/reviews/google/mobly/196#-KjAe0xccAJ6jmb7VPSW:-KjAe0xccAJ6jmb7VPSX:b-km6z95) ([raw file](https://github.com/google/mobly/blob/b92fdbea02c49289eb2db287deac54c3df9b6ecc/mobly/controllers/android_device.py#L411)):*
> ```Python
>                 'INFO [AndroidDevice|Caller] One pending call ringing.'
>         """
>         self.log.info('Logging debug tag set to \"%s\"', tag)
> ```

why the `\`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/196)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 411 at r1](https://reviewable.io:443/reviews/google/mobly/196#-KjAe0xccAJ6jmb7VPSW:-KjAeLsMjDcOFPVsuQ9g:bx780jl) ([raw file](https://github.com/google/mobly/blob/b92fdbea02c49289eb2db287deac54c3df9b6ecc/mobly/controllers/android_device.py#L411)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why the `\`?
</blockquote></details>

I'm a really big fan of Guns N Roses

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/196)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 353 at r2](https://reviewable.io:443/reviews/google/mobly/196#-KjBFP6WedrKHn7ho6Gm:-KjBFP6WedrKHn7ho6Gn:b5phay2) ([raw file](https://github.com/google/mobly/blob/cf5656f9563fa9959afaba423f04b6312f66dac5/mobly/controllers/android_device.py#L353)):*
> ```Python
>         log: A logger adapted from root logger with an added prefix specific
>              to an AndroidDevice instance. The default prefix is
>              [AndroidDevice|<serial>]. Use self.debug_tag(tag) to use a
> ```

Usage is actually `self.debug_tag = <tag>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/196)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 353 at r2](https://reviewable.io:443/reviews/google/mobly/196#-KjBFP6WedrKHn7ho6Gm:-KjBQGhAGAbDxd1S6pN9:b-896fix) ([raw file](https://github.com/google/mobly/blob/cf5656f9563fa9959afaba423f04b6312f66dac5/mobly/controllers/android_device.py#L353)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Usage is actually `self.debug_tag = <tag>`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/196)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/196#-:-KjBvGnd0vo26HBfOX7T:bnfp4nl)*

**Pull request merged**
