### PR TITLE
Update docs.

### LINKED ISSUE #112: Replace doc site with regular md files
Since doc site is difficult to maintain, we decided to use regular md files instead.

### PR DESCRIPTION
**Pull request by xpconanfan**
* Added [tutorial](https://github.com/google/mobly/wiki/Getting-Started-with-Mobly) via Github GUI.
* Move tutorial to Wiki.
* Update README to be a frontpage instead of tutorial.
* Remove doc sites.

Fixes #112

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/113)

### CODE REVIEW

**Comment by adorokhine** [comment]
Is there a way to review the wiki changes? You said it was its own project right? Can a PR be sent within that project?

---

Reviewed 1 of 29 files at r1.
Review status: 1 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113#-:-KdDiRCTMiS1fwaAembn:b-m9oy3r)*

**Comment by xpconanfan** [comment]
I could only find the git repo. not sure where the reviews to since it seems to be a separate project.
Read github's doc on it and it only uses the GUI

---

Review status: 1 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113#-:-KdDkanM8d5F-c0oIULO:bipwdxb)*

**Comment by xpconanfan** [comment]
Ready for review.

**Comment by adorokhine** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 42 at r2](https://reviewable.io:443/reviews/google/mobly/113#-Kde7vajSL-vr0p_niN3:-Kde7vakO2i8vn2rXwMm:bmmjd59) ([raw file](https://github.com/google/mobly/blob/cf6944f2bb3a04513ecea0a4f49c4146ba584278/README.md#L42)):*
> ```Markdown
> 
> ```
> <<<<<<< HEAD
> ```

This file contains merge artifact markers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by xpconanfan** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 42 at r2](https://reviewable.io:443/reviews/google/mobly/113#-Kde7vajSL-vr0p_niN3:-Kde96cgWshpWR-GQ5gc:b-fdbt9z) ([raw file](https://github.com/google/mobly/blob/4e6872a6b49e1057b4f792f42d3a4dc0a56cfa2b/README.md#L42)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This file contains merge artifact markers
</blockquote></details>

Hmm, sorry not sure why it wasn't pushed properly.
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by adorokhine** [comment]
Reviewed 28 of 29 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 42 at r3](https://reviewable.io:443/reviews/google/mobly/113#-KdgrVz7Py-dDhH3Obj4:-KdgrVz87pLw9NETxhcv:b-d5dq2k) ([raw file](https://github.com/google/mobly/blob/354eaf0829008879e8080b998baf07a746c9671d/README.md#L42)):*
> ```Markdown
> 
> ```
> $ git clone git@github.com:google/mobly.git
> ```

This clone should use https as the public won't have access to clone it through ssh.

---

*[README.md, line 51 at r3](https://reviewable.io:443/reviews/google/mobly/113#-KdgryUau61BLkscezRA:-KdgryUbtKbijGWg_K8b:bv733kf) ([raw file](https://github.com/google/mobly/blob/354eaf0829008879e8080b998baf07a746c9671d/README.md#L51)):*
> ```Markdown
> 
> ## Tutorials
> To get started with some simple tests, see the [Mobly tutorial](https://github.com/google/mobly/wiki/Getting-Started-with-Mobly).
> ```

We've decided against wiki right? Should this be a link to tutorial.md instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 42 at r3](https://reviewable.io:443/reviews/google/mobly/113#-KdgrVz7Py-dDhH3Obj4:-Kdh6fM5SWtvkWrbZ6_F:b-896fix) ([raw file](https://github.com/google/mobly/blob/354eaf0829008879e8080b998baf07a746c9671d/README.md#L42)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This clone should use https as the public won't have access to clone it through ssh.
</blockquote></details>

Done.

---

*[README.md, line 51 at r3](https://reviewable.io:443/reviews/google/mobly/113#-KdgryUau61BLkscezRA:-Kdh6fnqInUJvvHdTS3h:b-896fix) ([raw file](https://github.com/google/mobly/blob/354eaf0829008879e8080b998baf07a746c9671d/README.md#L51)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

We've decided against wiki right? Should this be a link to tutorial.md instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by adorokhine** [comment]
Review status: 29 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 51 at r4](https://reviewable.io:443/reviews/google/mobly/113#-KdhFiWYVNY4MO-6Yjxg:-KdhFiWZQI_-2TpJEh4q:b-49oy0r) ([raw file](https://github.com/google/mobly/blob/652931a8b393655e9b82be145fbc40593e88ff70/README.md#L51)):*
> ```Markdown
> 
> ## Tutorials
> To get started with some simple tests, see the [Mobly tutorial](https://github.com/google/mobly/blob/master/docs/tutorial.md).
> ```

This should probably be a relative link: docs/tutorial.md. Otherwise it's hard to preview these docs in a PR because the internal links don't work. (You can check the mobly snippet lib examples to see examples of relative links).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by dthkao** [comment]
Review status: 29 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 29 at r4](https://reviewable.io:443/reviews/google/mobly/113#-KdlT9fKNHkW59VQDffX:-KdlT9fKNHkW59VQDffY:b-z6q1bv) ([raw file](https://github.com/google/mobly/blob/652931a8b393655e9b82be145fbc40593e88ff70/README.md#L29)):*
> ```Markdown
> **If you use Python3, use `pip3` and `python3` (or python3.x) accordingly.**
> 
> ## Installation
> ```

Can we add a note about installing in virtualenv to avoid adding it to path?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by xpconanfan** [comment]
Users can feel free to use virtualenv if they know what they are doing. If
they don't, I don't want this to become a mini tutorial for virtualenv.
Also don't want to leave the impression that virtualenv is required to run.
Let's keep it simple

**Comment by xpconanfan** [comment]
Review status: 29 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 29 at r4](https://reviewable.io:443/reviews/google/mobly/113#-KdlT9fKNHkW59VQDffX:-KdlmLgCadST2v_rZa7j:b-es5c9n) ([raw file](https://github.com/google/mobly/blob/652931a8b393655e9b82be145fbc40593e88ff70/README.md#L29)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Can we add a note about installing in virtualenv to avoid adding it to path?
</blockquote></details>

Users can feel free to use virtualenv if they know what they are doing. If they don't, I don't want this to become a mini tutorial for virtualenv. Also don't want to leave the impression that virtualenv is required to run. Let's keep it simple

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by xpconanfan** [comment]
Review status: 29 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 51 at r4](https://reviewable.io:443/reviews/google/mobly/113#-KdhFiWYVNY4MO-6Yjxg:-KdllVf5opRMYJMBEquo:buefleg) ([raw file](https://github.com/google/mobly/blob/652931a8b393655e9b82be145fbc40593e88ff70/README.md#L51)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This should probably be a relative link: docs/tutorial.md. Otherwise it's hard to preview these docs in a PR because the internal links don't work. (You can check the mobly snippet lib examples to see examples of relative links).
</blockquote></details>

Changing to relative link did not resolve the preview problem for me... am i previewing it wrong?..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/113#-:-KdmZdgaZZ-yR5bUlQAd:bnfp4nl)*

**Pull request merged**
