### PR TITLE
Add incremental build ID and build fingerprint as AndroidDevice build info properties

### PR DESCRIPTION
**Pull request by xianyuanjia**
The incremental build ID is used for distinguishing non-release builds which may lack a release build ID.
The build fingerprint provides detailed build naming for CTS-V tests.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/774)

### CODE REVIEW

**Comment by xpconanfan** [comment]
so we need this to distinguish release and non-release builds?

**Review by booneng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/774)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @booneng and @xianyuanjia)

*[a discussion](https://reviewable.io/reviews/google/mobly/774#-MqShWBR-jkXKOjIhSeU:-MqShWBR-jkXKOjIhSeV:bpr9j07) (no related file):*
Would it be possible to add ro.build.fingerprint in this PR as well? would be useful for CTS-V tests.

---

**Review by xpconanfan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/774)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @booneng and @xpconanfan)

*[a discussion](https://reviewable.io/reviews/google/mobly/774#-MqShWBR-jkXKOjIhSeU:-MqSiUQJ2ZY5A7ESU_gz:b-zb878r) (no related file):*
<details><summary><i>Previously, booneng (boon) wrote…</i></summary><blockquote>

Would it be possible to add ro.build.fingerprint in this PR as well? would be useful for CTS-V tests.
</blockquote></details>

If we add fingerprint, do we still need incremental?

---

**Review by booneng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly/774)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @booneng and @xpconanfan)

*[a discussion](https://reviewable.io/reviews/google/mobly/774#-MqShWBR-jkXKOjIhSeU:-MqSj2qS6ahKquMyO9Cy:b-k7hasx) (no related file):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

If we add fingerprint, do we still need incremental?
</blockquote></details>

It is possible to get incremental build ID from fingerprint using regex. But might still be useful to keep the incremental anyway for convenience if it will be used elsewhere.

---

**Review by xianyuanjia — COMMENTED** [review]
The build ID is mainly used to label test efforts for certain automated test tracking tools. Non-release builds like master will have ro.build.id=MASTER, which cannot be used to distinguish between individual builds. Therefore, the ro.build.version.incremental will be used in that situation. 

> *[Reviewable](https://reviewable.io/reviews/google/mobly/774#-:-MqW2ag319AMBbbpSoBH:b-nt2sv7)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @booneng and @xpconanfan)

*[a discussion](https://reviewable.io/reviews/google/mobly/774#-MqShWBR-jkXKOjIhSeU:-MqWBYMP4pYI5fUkNqG3:b-896fix) (no related file):*
<details><summary><i>Previously, booneng (boon) wrote…</i></summary><blockquote>

It is possible to get incremental build ID from fingerprint using regex. But might still be useful to keep the incremental anyway for convenience if it will be used elsewhere.
</blockquote></details>

Done.

---

**Review by booneng — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/774)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xianyuanjia)

*[a discussion](https://reviewable.io/reviews/google/mobly/774#-MqShWBR-jkXKOjIhSeU:-MqXU7B16anEpydKEd6x:b-ucfknh) (no related file):*
<details><summary><i>Previously, xianyuanjia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

---

**Pull request merged**
