### PR TITLE
Fix a bug where internal controller registry is exposed.

### LINKED ISSUE #217: `register_controller` exposes Mobly's internal object registry.
`register_controller` returns a ref to the actual list Mobly uses to keep track of controller objects.
So if a test manipulates this list, it'll mess up the controller's teardown.
E.g. if the test removes controller objs from the list returned by `register_controller`, the removed controller objs won't be torn down.

### PR DESCRIPTION
**Pull request by xpconanfan**
Fixes #217

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/218)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/test_runner_test.py, line 113 at r1](https://reviewable.io:443/reviews/google/mobly/218#-Kl-HMOrqDRNGSwuZp9I:-Kl-HMOrqDRNGSwuZp9J:ba5tea4) ([raw file](https://github.com/google/mobly/blob/3b0f0b6eaaa0cf1229c2513820ef4d4fa5a625a5/tests/mobly/test_runner_test.py#L113)):*
> ```Python
>         self.assertEqual(magic_devices[1].magic, 'magic2')
> 
>     def test_register_controller_change_return_value(self):
> ```

Just so I'm clear on intent, this is to allow users to still modify the original individual controller objects *and* the list they get returned, without affecting the list Mobly tracks.

Can we add a unit test to make sure the individual controller is still modifiable (just so no one later changes this to deep copy)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/test_runner_test.py, line 113 at r1](https://reviewable.io:443/reviews/google/mobly/218#-Kl-HMOrqDRNGSwuZp9I:-Kl-LDH87wFwXxrNval4:bogylse) ([raw file](https://github.com/google/mobly/blob/3b0f0b6eaaa0cf1229c2513820ef4d4fa5a625a5/tests/mobly/test_runner_test.py#L113)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Just so I'm clear on intent, this is to allow users to still modify the original individual controller objects *and* the list they get returned, without affecting the list Mobly tracks.

Can we add a unit test to make sure the individual controller is still modifiable (just so no one later changes this to deep copy)?
</blockquote></details>

Yes.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 407 at r2](https://reviewable.io:443/reviews/google/mobly/218#-Kl0QtX4yKncCzbqPsFy:-Kl0QtX4yKncCzbqPsFz:b-emumpy) ([raw file](https://github.com/google/mobly/blob/289165976be976598b888e4e06394c21de6a68a6/mobly/test_runner.py#L407)):*
> ```Python
>         # Implementation of 'get_info' is optional for a controller module.
>         if hasattr(module, 'get_info'):
>             controller_info = module.get_info(objects)
> ```

There's other calls into user code, like get_info. If we're trying to be safe we should probably just copy the one that goes into self._controller_registry so we can clean up properly, and let the user code real with 'their' copy however they want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 407 at r2](https://reviewable.io:443/reviews/google/mobly/218#-Kl0QtX4yKncCzbqPsFy:-Kl0TlknABcasio0C-f6:b352r32) ([raw file](https://github.com/google/mobly/blob/289165976be976598b888e4e06394c21de6a68a6/mobly/test_runner.py#L407)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

There's other calls into user code, like get_info. If we're trying to be safe we should probably just copy the one that goes into self._controller_registry so we can clean up properly, and let the user code real with 'their' copy however they want.
</blockquote></details>

Hmm, shouldn't we collect info regardless of what user does to the obj list?
`get_info` is also an internal mobly operation, so I don't think what user does to the list in their test should affect how mobly internal operation works.
I'd think it's better to return the copy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 407 at r2](https://reviewable.io:443/reviews/google/mobly/218#-Kl0QtX4yKncCzbqPsFy:-Kl0UND7tfiB4tEdcatV:b-3k0ii0) ([raw file](https://github.com/google/mobly/blob/289165976be976598b888e4e06394c21de6a68a6/mobly/test_runner.py#L407)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, shouldn't we collect info regardless of what user does to the obj list?
`get_info` is also an internal mobly operation, so I don't think what user does to the list in their test should affect how mobly internal operation works.
I'd think it's better to return the copy?
</blockquote></details>

I thought `get_info` was implemented by the user? Not sure what you mean when you say it's an internal mobly operation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 407 at r2](https://reviewable.io:443/reviews/google/mobly/218#-Kl0QtX4yKncCzbqPsFy:-Kl0Wdnh7pZ_9gz6k4m5:bymwqib) ([raw file](https://github.com/google/mobly/blob/289165976be976598b888e4e06394c21de6a68a6/mobly/test_runner.py#L407)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I thought `get_info` was implemented by the user? Not sure what you mean when you say it's an internal mobly operation.
</blockquote></details>

Calling `get_info` is an internal operation like calling `destroy`.

Which list we use decides which objs are used to call these functions.

So it would be inconsistent to call `destroy` with the copy list and call `get_info` with the original list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 407 at r2](https://reviewable.io:443/reviews/google/mobly/218#-Kl0QtX4yKncCzbqPsFy:-Kl0Z-AaVqdWjqcBAXkP:bq0kvjk) ([raw file](https://github.com/google/mobly/blob/289165976be976598b888e4e06394c21de6a68a6/mobly/test_runner.py#L407)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Calling `get_info` is an internal operation like calling `destroy`.

Which list we use decides which objs are used to call these functions.

So it would be inconsistent to call `destroy` with the copy list and call `get_info` with the original list.
</blockquote></details>

Sure, that sounds good. All I'm saying is that, as of the latest patchset, the following implementation of `get_info` would still trigger the bug you're trying to fix:

```
def get_info(self, objects):
  objects.clear()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_runner.py, line 407 at r2](https://reviewable.io:443/reviews/google/mobly/218#-Kl0QtX4yKncCzbqPsFy:-Kl0aV1XylDYfV2KCDXk:b-v802qq) ([raw file](https://github.com/google/mobly/blob/289165976be976598b888e4e06394c21de6a68a6/mobly/test_runner.py#L407)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Sure, that sounds good. All I'm saying is that, as of the latest patchset, the following implementation of `get_info` would still trigger the bug you're trying to fix:

```
def get_info(self, objects):
  objects.clear()
```
</blockquote></details>

Ah good point.
Fixed.

Perhaps we should move `get_info` to unregister controller phase too (later)...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/218#-:-Kl1Ac3eXFspVt7kIONb:bnfp4nl)*

**Pull request merged**
