### PR TITLE
Making function _parse_device_list public

### PR DESCRIPTION
**Pull request by gauravkatoch007**
By making this function public, we can also filter for devices which are connected but in un-authorized or offline state. Can be useful for raising proper exceptions when device is not found in connected state.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/390)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/android_device.py, line 165 at r1](https://reviewable.io:443/reviews/google/mobly/390#-L3o6TFrM3TNdaimxmk6:-L3o6TFrM3TNdaimxmk7:b-kznrkh) ([raw file](https://github.com/google/mobly/blob/7957d8f279ab3e19ef381e0cf401dded7e8ba33d/mobly/controllers/android_device.py#L165)):*
> ```Python
> 
> 
> def parse_device_list(device_list_str, key):
> ```

pls alias the old name to the new name and mark the old name for deprecation and will be removed in 1.9

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/390)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 167 at r2](https://reviewable.io:443/reviews/google/mobly/390#-L3oNV5IBNF2NwQR4KUS:-L3oNV5J6AbPlxVyzzCs:b-z25bc9) ([raw file](https://github.com/google/mobly/blob/a16d4dc08ade9837e940cd27fe5365890f148294/mobly/controllers/android_device.py#L167)):*
> ```Python
> def _parse_device_list(device_list_str, key):
>     """Parses a byte string representing a list of devices.
>     
> ```

trailing spaces
did you run `yapf`

---

*[mobly/controllers/android_device.py, line 169 at r2](https://reviewable.io:443/reviews/google/mobly/390#-L3oNj1lZ2RK1HGL3W8y:-L3oNj1lZ2RK1HGL3W8z:b8ay255) ([raw file](https://github.com/google/mobly/blob/a16d4dc08ade9837e940cd27fe5365890f148294/mobly/controllers/android_device.py#L169)):*
> ```Python
>     
>     Deprecated, use `parse_device_list(device_list_str, key)` instead.
>     This method will be removed in 1.9.
> ```

stop here is fine. No need to repeat the rest

---

*[mobly/controllers/android_device.py, line 170 at r2](https://reviewable.io:443/reviews/google/mobly/390#-L3oNWHh90DacUWDSb9x:-L3oNWHh90DacUWDSb9y:b88ta8c) ([raw file](https://github.com/google/mobly/blob/a16d4dc08ade9837e940cd27fe5365890f148294/mobly/controllers/android_device.py#L170)):*
> ```Python
>     Deprecated, use `parse_device_list(device_list_str, key)` instead.
>     This method will be removed in 1.9.
>     
> ```

trailing spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/390)*

**Comment by gauravkatoch007** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 167 at r2](https://reviewable.io:443/reviews/google/mobly/390#-L3oNV5IBNF2NwQR4KUS:-L3owxWBaV-PjwMRHv3M:bvm7z8d) ([raw file](https://github.com/google/mobly/blob/a16d4dc08ade9837e940cd27fe5365890f148294/mobly/controllers/android_device.py#L167)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

trailing spaces
did you run `yapf`
</blockquote></details>

Resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/390)*

**Comment by gauravkatoch007** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/controllers/android_device.py, line 165 at r1](https://reviewable.io:443/reviews/google/mobly/390#-L3o6TFrM3TNdaimxmk6:-L3oxaTX1u8r8Fu-Mxaq:b-896fix) ([raw file](https://github.com/google/mobly/blob/7957d8f279ab3e19ef381e0cf401dded7e8ba33d/mobly/controllers/android_device.py#L165)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

pls alias the old name to the new name and mark the old name for deprecation and will be removed in 1.9
</blockquote></details>

Done.

---

*[mobly/controllers/android_device.py, line 167 at r2](https://reviewable.io:443/reviews/google/mobly/390#-L3oNV5IBNF2NwQR4KUS:-L3oxcOngBPXTzrYRjNO:b-896fix) ([raw file](https://github.com/google/mobly/blob/a16d4dc08ade9837e940cd27fe5365890f148294/mobly/controllers/android_device.py#L167)):*
<details><summary><i>Previously, gauravkatoch007 (Gaurav Katoch) wrote…</i></summary><blockquote>

Resolved
</blockquote></details>

Done.

---

*[mobly/controllers/android_device.py, line 169 at r2](https://reviewable.io:443/reviews/google/mobly/390#-L3oNj1lZ2RK1HGL3W8y:-L3oxbd5x0iynVemnXhA:b-896fix) ([raw file](https://github.com/google/mobly/blob/a16d4dc08ade9837e940cd27fe5365890f148294/mobly/controllers/android_device.py#L169)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

stop here is fine. No need to repeat the rest
</blockquote></details>

Done.

---

*[mobly/controllers/android_device.py, line 170 at r2](https://reviewable.io:443/reviews/google/mobly/390#-L3oNWHh90DacUWDSb9x:-L3oxb4jsBnTNSRJHHW_:b-896fix) ([raw file](https://github.com/google/mobly/blob/a16d4dc08ade9837e940cd27fe5365890f148294/mobly/controllers/android_device.py#L170)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

trailing spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/390)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/390#-:-L3oy8uBcakGG3hQF8F7:bnfp4nl)*

**Pull request merged**
