### PR TITLE
update test_get_available_port_returns_free_port for ipv6 sockets

### PR DESCRIPTION
**Pull request by malvarezrohena**
updating test_get_available_port_returns_free_port so test also passes with ipv6 sockets

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/209)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 69 at r1](https://reviewable.io:443/reviews/google/mobly/209#-KkIVWVn3VPzPyk79oQm:-KkIVWVoZHoq-96Si7j_:b13d7t6) ([raw file](https://github.com/google/mobly/blob/5de1851bdfd8bda40bbca53709920bd7aac4cfa6/tests/mobly/utils_test.py#L69)):*
> ```Python
>         port = utils.get_available_host_port()
>         got_socket = False
>         for family in (socket.AF_INET6, socket.AF_INET):
> ```

let's split this into two separate test cases for ivp4 and ipv6.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by malvarezrohena** [comment]
*[tests/mobly/utils_test.py, line 69 at r1](https://reviewable.io:443/reviews/google/mobly/209#-KkIVWVn3VPzPyk79oQm:-KkIZPuRMY0-Z18rwY-8:b-gxjx06) ([raw file](https://github.com/google/mobly/blob/5de1851bdfd8bda40bbca53709920bd7aac4cfa6/tests/mobly/utils_test.py#L69)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

let's split this into two separate test cases for ivp4 and ipv6.
</blockquote></details>

The idea is for the test to work regardless of the socket family type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 69 at r1](https://reviewable.io:443/reviews/google/mobly/209#-KkIVWVn3VPzPyk79oQm:-KkIaUjec1BEIq1hgHX_:b-g9aosg) ([raw file](https://github.com/google/mobly/blob/5de1851bdfd8bda40bbca53709920bd7aac4cfa6/tests/mobly/utils_test.py#L69)):*
<details><summary><i>Previously, malvarezrohena wrote…</i></summary><blockquote>

The idea is for the test to work regardless of the socket family type
</blockquote></details>

Ang, an ipv4 testcase would always fail in an ipv6-only environment. So splitting into two testcases wouldn't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/utils_test.py, line 69 at r1](https://reviewable.io:443/reviews/google/mobly/209#-KkIVWVn3VPzPyk79oQm:-KkIdDtvhXNNHVZRVmAw:bi20hdu) ([raw file](https://github.com/google/mobly/blob/5de1851bdfd8bda40bbca53709920bd7aac4cfa6/tests/mobly/utils_test.py#L69)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Ang, an ipv4 testcase would always fail in an ipv6-only environment. So splitting into two testcases wouldn't work.
</blockquote></details>

Ok, let's add a docstring for this test specifying that we are happy as long as one of ipv4 and ipv6 gets through.

---

*[tests/mobly/utils_test.py, line 76 at r1](https://reviewable.io:443/reviews/google/mobly/209#-KkIZueUGVvZVCPQXJAA:-KkIZueVSwC4tFPkl8Ys:b-djtw77) ([raw file](https://github.com/google/mobly/blob/5de1851bdfd8bda40bbca53709920bd7aac4cfa6/tests/mobly/utils_test.py#L76)):*
> ```Python
>                 continue
>             s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
>             try:                
> ```

trailing spaces.
could you run yapf on this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by malvarezrohena** [comment]
*[tests/mobly/utils_test.py, line 76 at r1](https://reviewable.io:443/reviews/google/mobly/209#-KkIZueUGVvZVCPQXJAA:-KkIeBn1XkAFcicjUqtR:b-7qr3kg) ([raw file](https://github.com/google/mobly/blob/5de1851bdfd8bda40bbca53709920bd7aac4cfa6/tests/mobly/utils_test.py#L76)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

trailing spaces.
could you run yapf on this file?
</blockquote></details>

I already fix that on the next update

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209#-:-KkIk7o5gcA1LAO3B5CC:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/utils_test.py, line 69 at r2](https://reviewable.io:443/reviews/google/mobly/209#-KkInMEZkaYUarwvZggV:-KkInMEZkaYUarwvZggW:b-akebrq) ([raw file](https://github.com/google/mobly/blob/1b309f3e9f44ad8c60830488684353bc057d121f/tests/mobly/utils_test.py#L69)):*
> ```Python
>         """This test checks we can bind to a socket on the port returned by portpicker 
>         and should pass as long as we can bind to either an ipv4 or ipv6 socket on 
>         such port."""
> ```

`"""` should be on a new line

Also generally the first sentence should be short and fit within one line.
More context can be explained in the following paragraph.

```
"""Verifies the logic to pick a free port on the host.

[More context]
"""
```

---

*[tests/mobly/utils_test.py, line 78 at r2](https://reviewable.io:443/reviews/google/mobly/209#-KkIo3M5EHftosMwHyyM:-KkIo3M6i8pO2WvKWWVr:betl853) ([raw file](https://github.com/google/mobly/blob/1b309f3e9f44ad8c60830488684353bc057d121f/tests/mobly/utils_test.py#L78)):*
> ```Python
>             except socket.error:
>                 continue
>             s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
> ```

seems like the code below this line could be moved out of the `for` loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by malvarezrohena** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/mobly/utils_test.py, line 78 at r2](https://reviewable.io:443/reviews/google/mobly/209#-KkIo3M5EHftosMwHyyM:-KkMeIqfdkFiQWsdbdIy:b-896fix) ([raw file](https://github.com/google/mobly/blob/1b309f3e9f44ad8c60830488684353bc057d121f/tests/mobly/utils_test.py#L78)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

seems like the code below this line could be moved out of the `for` loop?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/mobly/utils_test.py, line 69 at r2](https://reviewable.io:443/reviews/google/mobly/209#-KkInMEZkaYUarwvZggV:-KkMfv0kD3K2IdGsDNsO:b-a6s438) ([raw file](https://github.com/google/mobly/blob/1b309f3e9f44ad8c60830488684353bc057d121f/tests/mobly/utils_test.py#L69)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`"""` should be on a new line

Also generally the first sentence should be short and fit within one line.
More context can be explained in the following paragraph.

```
"""Verifies the logic to pick a free port on the host.

[More context]
"""
```
</blockquote></details>

Let's not mention implementation detail (that it uses `portpicker` underneath) of the function under test.
Also the closing `"""` should be on its own line.

---

*[tests/mobly/utils_test.py, line 76 at r3](https://reviewable.io:443/reviews/google/mobly/209#-KkMggVucDw2npoRz4hZ:-KkMggVvo8cbX7Koo9SS:bbwrwo) ([raw file](https://github.com/google/mobly/blob/bc26e1c616f05d0c25c2131dc4eb0443f34678e3/tests/mobly/utils_test.py#L76)):*
> ```Python
>             try:
>                 s = socket.socket(family, socket.SOCK_STREAM)
>                 got_socket = True
> ```

Shouldn't we break out of the loop here if we got a socket?

Also let's put the default value `AF_INET` in front of `AF_INET6`?

---

*[tests/mobly/utils_test.py, line 85 at r3](https://reviewable.io:443/reviews/google/mobly/209#-KkMg5RnDHqOh3oLgZbC:-KkMg5RnDHqOh3oLgZbD:bgs827z) ([raw file](https://github.com/google/mobly/blob/bc26e1c616f05d0c25c2131dc4eb0443f34678e3/tests/mobly/utils_test.py#L85)):*
> ```Python
>         finally:
>             s.close()
>         self.assertTrue(got_socket)
> ```

duplicate assert?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by malvarezrohena** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/mobly/utils_test.py, line 69 at r2](https://reviewable.io:443/reviews/google/mobly/209#-KkInMEZkaYUarwvZggV:-KkMp2Bq4nktUB-sw1Uy:b-896fix) ([raw file](https://github.com/google/mobly/blob/1b309f3e9f44ad8c60830488684353bc057d121f/tests/mobly/utils_test.py#L69)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Let's not mention implementation detail (that it uses `portpicker` underneath) of the function under test.
Also the closing `"""` should be on its own line.
</blockquote></details>

Done.

---

*[tests/mobly/utils_test.py, line 76 at r3](https://reviewable.io:443/reviews/google/mobly/209#-KkMggVucDw2npoRz4hZ:-KkMoi5qS_LsFiOBQlN0:b-896fix) ([raw file](https://github.com/google/mobly/blob/bc26e1c616f05d0c25c2131dc4eb0443f34678e3/tests/mobly/utils_test.py#L76)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Shouldn't we break out of the loop here if we got a socket?

Also let's put the default value `AF_INET` in front of `AF_INET6`?
</blockquote></details>

Done.

---

*[tests/mobly/utils_test.py, line 85 at r3](https://reviewable.io:443/reviews/google/mobly/209#-KkMg5RnDHqOh3oLgZbC:-KkMoOlpgzRdYEc04_-E:b-srrd56) ([raw file](https://github.com/google/mobly/blob/bc26e1c616f05d0c25c2131dc4eb0443f34678e3/tests/mobly/utils_test.py#L85)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

duplicate assert?
</blockquote></details>

weird I remember deleting that... ok re-deleted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 76 at r3](https://reviewable.io:443/reviews/google/mobly/209#-KkMggVucDw2npoRz4hZ:-KkMpXGhCJTw492S2NCJ:b-5wn5dd) ([raw file](https://github.com/google/mobly/blob/bc26e1c616f05d0c25c2131dc4eb0443f34678e3/tests/mobly/utils_test.py#L76)):*
<details><summary><i>Previously, malvarezrohena wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't we break out of the loop if the one is successful?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by malvarezrohena** [comment]
*[tests/mobly/utils_test.py, line 76 at r3](https://reviewable.io:443/reviews/google/mobly/209#-KkMggVucDw2npoRz4hZ:-KkMxkJjO_9uEkjO2E9A:bkjdzk7) ([raw file](https://github.com/google/mobly/blob/bc26e1c616f05d0c25c2131dc4eb0443f34678e3/tests/mobly/utils_test.py#L76)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Shouldn't we break out of the loop if the one is successful?
</blockquote></details>

Yes we should

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by malvarezrohena** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/mobly/utils_test.py, line 76 at r3](https://reviewable.io:443/reviews/google/mobly/209#-KkMggVucDw2npoRz4hZ:-KkMxlxqqlM6SmJzWQOR:b-896fix) ([raw file](https://github.com/google/mobly/blob/bc26e1c616f05d0c25c2131dc4eb0443f34678e3/tests/mobly/utils_test.py#L76)):*
<details><summary><i>Previously, malvarezrohena wrote…</i></summary><blockquote>

Yes we should
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/209#-:-KkNUIYNAnLEu_O4wWAg:bnfp4nl)*

**Pull request merged**
