### PR TITLE
Monsoon dictionary config support

### PR DESCRIPTION
**Pull request by dthkao**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/385)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/monsoon.py, line 47 at r1](https://reviewable.io:443/reviews/google/mobly/385#-L34LZLNu1PQRAuH8YzJ:-L34LZLNu1PQRAuH8YzK:bx4i4ir) ([raw file](https://github.com/google/mobly/blob/69f42d6cf9396352a4e4a6e976b10b2369cd8999/mobly/controllers/monsoon.py#L47)):*
> ```Python
>     if not configs:
>         raise MonsoonError('Configuration is empty, abort!')
>     elif not isinstance(configs, list):
> ```

type check should be in front of emptiness check?

---

*[mobly/controllers/monsoon.py, line 56 at r1](https://reviewable.io:443/reviews/google/mobly/385#-L34LhFVvqrGL3bv039i:-L34LhFVvqrGL3bv039j:bn2szv6) ([raw file](https://github.com/google/mobly/blob/69f42d6cf9396352a4e4a6e976b10b2369cd8999/mobly/controllers/monsoon.py#L56)):*
> ```Python
>         objs = get_instances(configs)
>     else:
>         raise Error('No valid config found in: %s' % configs)i
> ```

what's the trailing `i`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/monsoon.py, line 52 at r2](https://reviewable.io:443/reviews/google/mobly/385#-L34Nm6quB8GoY0RWUDX:-L34Nm6quB8GoY0RWUDY:bmdpzxl) ([raw file](https://github.com/google/mobly/blob/72f9f4585f1027026e534928a4b7a3032d257ac3/mobly/controllers/monsoon.py#L52)):*
> ```Python
>         # Configs is a list of dicts.
>         objs = get_instances_with_configs(configs)
>     elif isinstance(configs[0], basestring):
> ```

Looking at `android_device`, I think the `basestring` is supposed to be
`from past.builtins import basestring`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/monsoon.py, line 47 at r1](https://reviewable.io:443/reviews/google/mobly/385#-L34LZLNu1PQRAuH8YzJ:-L34Np5O41t0Cvv510D1:bmz3kjv) ([raw file](https://github.com/google/mobly/blob/69f42d6cf9396352a4e4a6e976b10b2369cd8999/mobly/controllers/monsoon.py#L47)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

type check should be in front of emptiness check?
</blockquote></details>

The flow is the same as Android?

---

*[mobly/controllers/monsoon.py, line 56 at r1](https://reviewable.io:443/reviews/google/mobly/385#-L34LhFVvqrGL3bv039i:-L34NvHuE3OQgYNqL6hi:b-l276bk) ([raw file](https://github.com/google/mobly/blob/69f42d6cf9396352a4e4a6e976b10b2369cd8999/mobly/controllers/monsoon.py#L56)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what's the trailing `i`?
</blockquote></details>

vi typo fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mobly/controllers/monsoon.py, line 52 at r2](https://reviewable.io:443/reviews/google/mobly/385#-L34Nm6quB8GoY0RWUDX:-L34OTVClUnR09lKdrdE:bmmj5fu) ([raw file](https://github.com/google/mobly/blob/72f9f4585f1027026e534928a4b7a3032d257ac3/mobly/controllers/monsoon.py#L52)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Looking at `android_device`, I think the `basestring` is supposed to be
`from past.builtins import basestring`
</blockquote></details>

added import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/monsoon.py, line 62 at r3](https://reviewable.io:443/reviews/google/mobly/385#-L34Pu99La8TBpbqfaDp:-L34Pu99La8TBpbqfaDq:b-q6w00l) ([raw file](https://github.com/google/mobly/blob/fbc8573b6b06feb177d99b98e89c281124662e90/mobly/controllers/monsoon.py#L62)):*
> ```Python
>  
>  
> def get_instances_with_configs(configs):
> ```

can we add docstring for this and `get_instances`, now that there are two similar functions?
This is also consistent with `android_device`

Also can this simply call the `get_instances`?
Maybe something like
```
return get_instances([c['serial'] for c in configs])
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/monsoon.py, line 62 at r3](https://reviewable.io:443/reviews/google/mobly/385#-L34Pu99La8TBpbqfaDp:-L34SMFxm8mIjuSPgKZx:b-896fix) ([raw file](https://github.com/google/mobly/blob/fbc8573b6b06feb177d99b98e89c281124662e90/mobly/controllers/monsoon.py#L62)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

can we add docstring for this and `get_instances`, now that there are two similar functions?
This is also consistent with `android_device`

Also can this simply call the `get_instances`?
Maybe something like
```
return get_instances([c['serial'] for c in configs])
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/controllers/monsoon.py, line 54 at r4](https://reviewable.io:443/reviews/google/mobly/385#-L34Scql4v0OKn2wFpaf:-L34Scql4v0OKn2wFpag:bwqs0ac) ([raw file](https://github.com/google/mobly/blob/b8183d1b8be80faf82dbfa055885077ff1c70fa3/mobly/controllers/monsoon.py#L54)):*
> ```Python
>         # Configs is a list of dicts.
>         objs = get_instances_with_configs(configs)
>     elif isinstance(configs[0], basestring):
> ```

actually, isn't the flat list format a list of ints instead of a list of strings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/monsoon.py, line 54 at r4](https://reviewable.io:443/reviews/google/mobly/385#-L34Scql4v0OKn2wFpaf:-L34lXVxuUOrdAA0fBwu:b-896fix) ([raw file](https://github.com/google/mobly/blob/b8183d1b8be80faf82dbfa055885077ff1c70fa3/mobly/controllers/monsoon.py#L54)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

actually, isn't the flat list format a list of ints instead of a list of strings?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/monsoon.py, line 55 at r5](https://reviewable.io:443/reviews/google/mobly/385#-L34ltAB4xqbXh8YvP30:-L34ltAB4xqbXh8YvP31:b-6gnoa1) ([raw file](https://github.com/google/mobly/blob/c480a60fb6f879ae19a06840758b8d72035fb4c7/mobly/controllers/monsoon.py#L55)):*
> ```Python
>         objs = get_instances_with_configs(configs)
>     elif isinstance(configs[0], int):
>         # Configs is a list of strings representing serials.
> ```

comment still says "strings"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/controllers/monsoon.py, line 55 at r5](https://reviewable.io:443/reviews/google/mobly/385#-L34ltAB4xqbXh8YvP30:-L34qHizs30PJeqo1_LK:b-896fix) ([raw file](https://github.com/google/mobly/blob/c480a60fb6f879ae19a06840758b8d72035fb4c7/mobly/controllers/monsoon.py#L55)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

comment still says "strings"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/385#-:-L34rDJTAeQyaS3P98Jq:bnfp4nl)*

**Comment by dthkao** [comment]
python setup.py test and python3 setup.py test all green. Not waiting for travis to merge.

**Pull request merged**
