### PR TITLE
Expose more test runtime info.

### LINKED ISSUE #240: Provide a log directory for each test
When there are multiple tests in a class, it is very helpful to group output files per each test for debugging purposes.

To achieve this, Mobly should provide such directory for each test. This way, the test could dump debug info to this directory in `on_fail`.

We choose this design because it maintains the separation of controller and framework responsibilities. The controller module does not need to be aware of the execution phase of a test, e.g. `AndroidDevice` does not need to worry about dumping logs at a particular point in test execution.

And the Mobly framework does not need to know how to get a particular type of log for a particular test. A test class could decide at which point of execution to dump which type of log for a test.

### PR DESCRIPTION
**Pull request by xpconanfan**
Add a `TestInfo` class to expose more runtime info of the test.
This way we don't have to keep adding more attributes to base class.

Fixes #240

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly/330)

### CODE REVIEW

**Comment by kdart** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330#-:-KviSDe_S490ubXZsgPd:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[mobly/test_info.py, line 44 at r2](https://reviewable.io:443/reviews/google/mobly/330#-KviTfNso_VRUJnkCkxp:-KviTfNso_VRUJnkCkxq:b-53160n) ([raw file](https://github.com/google/mobly/blob/7412482640b51c8b271391b895c4277eb2ffbf46/mobly/test_info.py#L44)):*
> ```Python
> 
>     @property
>     def test_name(self):
> ```

should we simplify the names of these attributes to 'name', 'signature', 'record' etc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330)*

**Comment by xpconanfan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_info.py, line 21 at r2](https://reviewable.io:443/reviews/google/mobly/330#-KviTuQoxyDrY-QgOn_w:-KviTuQoxyDrY-QgOn_x:bb7kx8) ([raw file](https://github.com/google/mobly/blob/7412482640b51c8b271391b895c4277eb2ffbf46/mobly/test_info.py#L21)):*
> ```Python
> 
> 
> class TestInfo(object):
> ```

Maybe this can be `TestRuntimeInfo` to be more clear?
`TestInfo` can also mean the information passed to the test from config.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330)*

**Comment by kdart** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/test_info.py, line 21 at r2](https://reviewable.io:443/reviews/google/mobly/330#-KviTuQoxyDrY-QgOn_w:-KviX87WbWM8LuS34si3:b-6n8wk1) ([raw file](https://github.com/google/mobly/blob/7412482640b51c8b271391b895c4277eb2ffbf46/mobly/test_info.py#L21)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Maybe this can be `TestRuntimeInfo` to be more clear?
`TestInfo` can also mean the information passed to the test from config.
</blockquote></details>

The user is not exposed to this, only sees the instance in the test cases. So I don't think it matters much. But.. yes, a better name would be `RuntimeTestInfo` because some might confuse names beginning with `Test` as some kind of unit test class. 

---

*[mobly/test_info.py, line 44 at r2](https://reviewable.io:443/reviews/google/mobly/330#-KviTfNso_VRUJnkCkxp:-KviWxPkcRwzdtyblQ0D:bqibudm) ([raw file](https://github.com/google/mobly/blob/7412482640b51c8b271391b895c4277eb2ffbf46/mobly/test_info.py#L44)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should we simplify the names of these attributes to 'name', 'signature', 'record' etc?
</blockquote></details>

I think that's a good idea. using `current_test_info.test_name` is rather redundant. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[mobly/runtime_test_info.py, line 21 at r2](https://reviewable.io:443/reviews/google/mobly/330#-KviTuQoxyDrY-QgOn_w:-Kvo-j48eHAeH-Wl89Cc:b-896fix) ([raw file](https://github.com/google/mobly/blob/7412482640b51c8b271391b895c4277eb2ffbf46/mobly/runtime_test_info.py#L21)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

The user is not exposed to this, only sees the instance in the test cases. So I don't think it matters much. But.. yes, a better name would be `RuntimeTestInfo` because some might confuse names beginning with `Test` as some kind of unit test class. 
</blockquote></details>

Done.

---

*[mobly/runtime_test_info.py, line 44 at r2](https://reviewable.io:443/reviews/google/mobly/330#-KviTfNso_VRUJnkCkxp:-Kvo-fxOM0eelmJ4P9nM:b-896fix) ([raw file](https://github.com/google/mobly/blob/7412482640b51c8b271391b895c4277eb2ffbf46/mobly/runtime_test_info.py#L44)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

I think that's a good idea. using `current_test_info.test_name` is rather redundant. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330)*

**Comment by k2fong** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/base_test.py, line 347 at r3](https://reviewable.io:443/reviews/google/mobly/330#-Kvo8-TsNTZzSY3LFy35:-Kvo8-TsNTZzSY3LFy36:bgvfvli) ([raw file](https://github.com/google/mobly/blob/41764dfaf7e3a6ea729f92ffd2edeb20c97294d6/mobly/base_test.py#L347)):*
> ```Python
>         tr_record.test_begin()
>         self.current_test_info = runtime_test_info.RuntimeTestInfo(
>             test_name, self.log_path, tr_record)
> ```

nit, will it make sense to have RuntimeTestInfo create the TestResultRecord to be use below?  so that all runtime test info related stuff will originate from RuntimeTestInfo.  

Also, it seems like test_name might be duplicated in both the RuntimeTestInfo and TestResultRecord now. 

---

*[mobly/runtime_test_info.py, line 57 at r3](https://reviewable.io:443/reviews/google/mobly/330#-Kvo4Rgiwd7neqzTsg0g:-Kvo4Rgiwd7neqzTsg0h:b-7vmhs2) ([raw file](https://github.com/google/mobly/blob/41764dfaf7e3a6ea729f92ffd2edeb20c97294d6/mobly/runtime_test_info.py#L57)):*
> ```Python
>     @property
>     def output_path(self):
>         utils.create_dir(self._output_dir_path)
> ```

should the directory be created in __init__()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[mobly/base_test.py, line 347 at r3](https://reviewable.io:443/reviews/google/mobly/330#-Kvo8-TsNTZzSY3LFy35:-KvoArGUnJT7atLbcXU7:b-kpc8f4) ([raw file](https://github.com/google/mobly/blob/41764dfaf7e3a6ea729f92ffd2edeb20c97294d6/mobly/base_test.py#L347)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

nit, will it make sense to have RuntimeTestInfo create the TestResultRecord to be use below?  so that all runtime test info related stuff will originate from RuntimeTestInfo.  

Also, it seems like test_name might be duplicated in both the RuntimeTestInfo and TestResultRecord now. 
</blockquote></details>

The runtime info is strictly for tests to read, the record is used for tracking test's execution states.
I don't see any significant difference.

test record is actively modified by mobly itself, whereas runtime info is a passive reference to some runtime info. so i don't think it's beneficial to complicate the role of runtime info at this moment.

---

*[mobly/runtime_test_info.py, line 57 at r3](https://reviewable.io:443/reviews/google/mobly/330#-Kvo4Rgiwd7neqzTsg0g:-KvoAm01PMpQnefAqpdS:b-edf4js) ([raw file](https://github.com/google/mobly/blob/41764dfaf7e3a6ea729f92ffd2edeb20c97294d6/mobly/runtime_test_info.py#L57)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

should the directory be created in __init__()?
</blockquote></details>

No, if the dir is never accessed we don't want to create it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330)*

**Comment by kdart** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330)*

**Comment by k2fong** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly/330#-:-KvzO1dEb72As2KZWyOq:bnfp4nl)*

**Pull request merged**
